// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	automationServiceServiceID = iota + 1
)

// Stream IDs
const (
	activityPauseStreamID = iota + 1
	callFanOutActivityAStreamID
	callFanOutActivityBStreamID
	callFanOutActivityCStreamID
	callSequentialActivityAStreamID
	callSequentialActivityBStreamID
	consumeActivityJobStreamID
	consumeFanOutActivityAStreamID
	consumeFanOutActivityBStreamID
	consumeFanOutActivityCStreamID
	consumeFanOutWorkflowJobStreamID
	consumeSequentialActivityAStreamID
	consumeSequentialActivityBStreamID
	consumeWorkflowJobStreamID
	localScheduleStreamID
	observeActivityResultStreamID
	observeFanOutActivityBStreamID
	observeFanOutActivityCStreamID
	observeWorkflowResultStreamID
	processActivityJobStreamID
	processFanOutActivityAStreamID
	processFanOutActivityBStreamID
	processFanOutActivityCStreamID
	processScheduledActivityStreamID
	processScheduledWorkflowStreamID
	processSequentialActivityAStreamID
	processSequentialActivityBStreamID
	processWorkflowJobStreamID
	scheduledActivityPauseStreamID
	scheduledWorkflowPauseStreamID
	splitActivityAResultStreamID
	splitOnDemandJobsStreamID
	submitActivityJobStreamID
	submitFanOutWorkflowJobStreamID
	submitWorkflowJobStreamID
	temporalActivityScheduleStreamID
	temporalWorkflowScheduleStreamID
	workflowPauseStreamID
)

// Endpoint IDs
const (
	activityJobEndpointID = iota + 1
	fanOutActivityAEndpointID
	fanOutActivityBEndpointID
	fanOutActivityCEndpointID
	fanOutWorkflowJobEndpointID
	localScheduleEndpointID
	sequentialActivityAEndpointID
	sequentialActivityBEndpointID
	temporalActivityScheduleEndpointID
	temporalWorkflowScheduleEndpointID
	workflowJobEndpointID
)

// Connector IDs
const (
	localCronConnectorID = iota + 1
	temporalConnectorID
)

type Config struct {
	Services struct {
		AutomationService cfg.ServiceConfig `yaml:"automationService" mapstructure:"automationService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		ActivityPause              cfg.DelayStreamConfig `yaml:"activityPause" mapstructure:"activityPause"`
		CallFanOutActivityA        cfg.SinkStreamConfig  `yaml:"callFanOutActivityA" mapstructure:"callFanOutActivityA"`
		CallFanOutActivityB        cfg.SinkStreamConfig  `yaml:"callFanOutActivityB" mapstructure:"callFanOutActivityB"`
		CallFanOutActivityC        cfg.SinkStreamConfig  `yaml:"callFanOutActivityC" mapstructure:"callFanOutActivityC"`
		CallSequentialActivityA    cfg.SinkStreamConfig  `yaml:"callSequentialActivityA" mapstructure:"callSequentialActivityA"`
		CallSequentialActivityB    cfg.SinkStreamConfig  `yaml:"callSequentialActivityB" mapstructure:"callSequentialActivityB"`
		ConsumeActivityJob         cfg.InputStreamConfig `yaml:"consumeActivityJob" mapstructure:"consumeActivityJob"`
		ConsumeFanOutActivityA     cfg.InputStreamConfig `yaml:"consumeFanOutActivityA" mapstructure:"consumeFanOutActivityA"`
		ConsumeFanOutActivityB     cfg.InputStreamConfig `yaml:"consumeFanOutActivityB" mapstructure:"consumeFanOutActivityB"`
		ConsumeFanOutActivityC     cfg.InputStreamConfig `yaml:"consumeFanOutActivityC" mapstructure:"consumeFanOutActivityC"`
		ConsumeFanOutWorkflowJob   cfg.InputStreamConfig `yaml:"consumeFanOutWorkflowJob" mapstructure:"consumeFanOutWorkflowJob"`
		ConsumeSequentialActivityA cfg.InputStreamConfig `yaml:"consumeSequentialActivityA" mapstructure:"consumeSequentialActivityA"`
		ConsumeSequentialActivityB cfg.InputStreamConfig `yaml:"consumeSequentialActivityB" mapstructure:"consumeSequentialActivityB"`
		ConsumeWorkflowJob         cfg.InputStreamConfig `yaml:"consumeWorkflowJob" mapstructure:"consumeWorkflowJob"`
		LocalSchedule              cfg.InputStreamConfig `yaml:"localSchedule" mapstructure:"localSchedule"`
		ObserveActivityResult      cfg.MapStreamConfig   `yaml:"observeActivityResult" mapstructure:"observeActivityResult"`
		ObserveFanOutActivityB     cfg.MapStreamConfig   `yaml:"observeFanOutActivityB" mapstructure:"observeFanOutActivityB"`
		ObserveFanOutActivityC     cfg.MapStreamConfig   `yaml:"observeFanOutActivityC" mapstructure:"observeFanOutActivityC"`
		ObserveWorkflowResult      cfg.MapStreamConfig   `yaml:"observeWorkflowResult" mapstructure:"observeWorkflowResult"`
		ProcessActivityJob         cfg.MapStreamConfig   `yaml:"processActivityJob" mapstructure:"processActivityJob"`
		ProcessFanOutActivityA     cfg.MapStreamConfig   `yaml:"processFanOutActivityA" mapstructure:"processFanOutActivityA"`
		ProcessFanOutActivityB     cfg.MapStreamConfig   `yaml:"processFanOutActivityB" mapstructure:"processFanOutActivityB"`
		ProcessFanOutActivityC     cfg.MapStreamConfig   `yaml:"processFanOutActivityC" mapstructure:"processFanOutActivityC"`
		ProcessScheduledActivity   cfg.MapStreamConfig   `yaml:"processScheduledActivity" mapstructure:"processScheduledActivity"`
		ProcessScheduledWorkflow   cfg.MapStreamConfig   `yaml:"processScheduledWorkflow" mapstructure:"processScheduledWorkflow"`
		ProcessSequentialActivityA cfg.MapStreamConfig   `yaml:"processSequentialActivityA" mapstructure:"processSequentialActivityA"`
		ProcessSequentialActivityB cfg.MapStreamConfig   `yaml:"processSequentialActivityB" mapstructure:"processSequentialActivityB"`
		ProcessWorkflowJob         cfg.MapStreamConfig   `yaml:"processWorkflowJob" mapstructure:"processWorkflowJob"`
		ScheduledActivityPause     cfg.DelayStreamConfig `yaml:"scheduledActivityPause" mapstructure:"scheduledActivityPause"`
		ScheduledWorkflowPause     cfg.DelayStreamConfig `yaml:"scheduledWorkflowPause" mapstructure:"scheduledWorkflowPause"`
		SplitActivityAResult       cfg.SplitStreamConfig `yaml:"splitActivityAResult" mapstructure:"splitActivityAResult"`
		SplitOnDemandJobs          cfg.SplitStreamConfig `yaml:"splitOnDemandJobs" mapstructure:"splitOnDemandJobs"`
		SubmitActivityJob          cfg.SinkStreamConfig  `yaml:"submitActivityJob" mapstructure:"submitActivityJob"`
		SubmitFanOutWorkflowJob    cfg.SinkStreamConfig  `yaml:"submitFanOutWorkflowJob" mapstructure:"submitFanOutWorkflowJob"`
		SubmitWorkflowJob          cfg.SinkStreamConfig  `yaml:"submitWorkflowJob" mapstructure:"submitWorkflowJob"`
		TemporalActivitySchedule   cfg.InputStreamConfig `yaml:"temporalActivitySchedule" mapstructure:"temporalActivitySchedule"`
		TemporalWorkflowSchedule   cfg.InputStreamConfig `yaml:"temporalWorkflowSchedule" mapstructure:"temporalWorkflowSchedule"`
		WorkflowPause              cfg.DelayStreamConfig `yaml:"workflowPause" mapstructure:"workflowPause"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		LocalCron cfg.CronDataConnectorConfig     `yaml:"localCron" mapstructure:"localCron"`
		Temporal  cfg.TemporalDataConnectorConfig `yaml:"temporal" mapstructure:"temporal"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		ActivityJob cfg.TemporalEndpointConfig `yaml:"activityJob" mapstructure:"activityJob"`

		FanOutActivityA cfg.TemporalEndpointConfig `yaml:"fanOutActivityA" mapstructure:"fanOutActivityA"`

		FanOutActivityB cfg.TemporalEndpointConfig `yaml:"fanOutActivityB" mapstructure:"fanOutActivityB"`

		FanOutActivityC cfg.TemporalEndpointConfig `yaml:"fanOutActivityC" mapstructure:"fanOutActivityC"`

		FanOutWorkflowJob cfg.TemporalEndpointConfig `yaml:"fanOutWorkflowJob" mapstructure:"fanOutWorkflowJob"`

		LocalSchedule cfg.CronEndpointConfig `yaml:"localSchedule" mapstructure:"localSchedule"`

		SequentialActivityA cfg.TemporalEndpointConfig `yaml:"sequentialActivityA" mapstructure:"sequentialActivityA"`

		SequentialActivityB cfg.TemporalEndpointConfig `yaml:"sequentialActivityB" mapstructure:"sequentialActivityB"`

		TemporalActivitySchedule cfg.TemporalEndpointConfig `yaml:"temporalActivitySchedule" mapstructure:"temporalActivitySchedule"`

		TemporalWorkflowSchedule cfg.TemporalEndpointConfig `yaml:"temporalWorkflowSchedule" mapstructure:"temporalWorkflowSchedule"`

		WorkflowJob cfg.TemporalEndpointConfig `yaml:"workflowJob" mapstructure:"workflowJob"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
		DefaultPool cfg.PoolConfig `yaml:"defaultPool" mapstructure:"defaultPool"`
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
		CallSequentialActivityAToCallSequentialActivityB       cfg.LinkConfig `yaml:"callSequentialActivityAToCallSequentialActivityB" mapstructure:"callSequentialActivityAToCallSequentialActivityB"`
		CallSequentialActivityBToProcessWorkflowJob            cfg.LinkConfig `yaml:"callSequentialActivityBToProcessWorkflowJob" mapstructure:"callSequentialActivityBToProcessWorkflowJob"`
		ConsumeActivityJobToActivityPause                      cfg.LinkConfig `yaml:"consumeActivityJobToActivityPause" mapstructure:"consumeActivityJobToActivityPause"`
		ConsumeFanOutActivityAToProcessFanOutActivityA         cfg.LinkConfig `yaml:"consumeFanOutActivityAToProcessFanOutActivityA" mapstructure:"consumeFanOutActivityAToProcessFanOutActivityA"`
		ConsumeFanOutActivityBToProcessFanOutActivityB         cfg.LinkConfig `yaml:"consumeFanOutActivityBToProcessFanOutActivityB" mapstructure:"consumeFanOutActivityBToProcessFanOutActivityB"`
		ConsumeFanOutActivityCToProcessFanOutActivityC         cfg.LinkConfig `yaml:"consumeFanOutActivityCToProcessFanOutActivityC" mapstructure:"consumeFanOutActivityCToProcessFanOutActivityC"`
		ConsumeFanOutWorkflowJobToCallFanOutActivityA          cfg.LinkConfig `yaml:"consumeFanOutWorkflowJobToCallFanOutActivityA" mapstructure:"consumeFanOutWorkflowJobToCallFanOutActivityA"`
		ConsumeSequentialActivityAToProcessSequentialActivityA cfg.LinkConfig `yaml:"consumeSequentialActivityAToProcessSequentialActivityA" mapstructure:"consumeSequentialActivityAToProcessSequentialActivityA"`
		ConsumeSequentialActivityBToProcessSequentialActivityB cfg.LinkConfig `yaml:"consumeSequentialActivityBToProcessSequentialActivityB" mapstructure:"consumeSequentialActivityBToProcessSequentialActivityB"`
		ConsumeWorkflowJobToWorkflowPause                      cfg.LinkConfig `yaml:"consumeWorkflowJobToWorkflowPause" mapstructure:"consumeWorkflowJobToWorkflowPause"`
		SplitActivityAResultToCallFanOutActivityB              cfg.LinkConfig `yaml:"splitActivityAResultToCallFanOutActivityB" mapstructure:"splitActivityAResultToCallFanOutActivityB"`
		SplitActivityAResultToCallFanOutActivityC              cfg.LinkConfig `yaml:"splitActivityAResultToCallFanOutActivityC" mapstructure:"splitActivityAResultToCallFanOutActivityC"`
		WorkflowPauseToCallSequentialActivityA                 cfg.LinkConfig `yaml:"workflowPauseToCallSequentialActivityA" mapstructure:"workflowPauseToCallSequentialActivityA"`
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		AutomationJob cfg.TypeConfig `yaml:"automationJob" mapstructure:"automationJob"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.AutomationService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.ActivityPause,
		&c.Streams.CallFanOutActivityA,
		&c.Streams.CallFanOutActivityB,
		&c.Streams.CallFanOutActivityC,
		&c.Streams.CallSequentialActivityA,
		&c.Streams.CallSequentialActivityB,
		&c.Streams.ConsumeActivityJob,
		&c.Streams.ConsumeFanOutActivityA,
		&c.Streams.ConsumeFanOutActivityB,
		&c.Streams.ConsumeFanOutActivityC,
		&c.Streams.ConsumeFanOutWorkflowJob,
		&c.Streams.ConsumeSequentialActivityA,
		&c.Streams.ConsumeSequentialActivityB,
		&c.Streams.ConsumeWorkflowJob,
		&c.Streams.LocalSchedule,
		&c.Streams.ObserveActivityResult,
		&c.Streams.ObserveFanOutActivityB,
		&c.Streams.ObserveFanOutActivityC,
		&c.Streams.ObserveWorkflowResult,
		&c.Streams.ProcessActivityJob,
		&c.Streams.ProcessFanOutActivityA,
		&c.Streams.ProcessFanOutActivityB,
		&c.Streams.ProcessFanOutActivityC,
		&c.Streams.ProcessScheduledActivity,
		&c.Streams.ProcessScheduledWorkflow,
		&c.Streams.ProcessSequentialActivityA,
		&c.Streams.ProcessSequentialActivityB,
		&c.Streams.ProcessWorkflowJob,
		&c.Streams.ScheduledActivityPause,
		&c.Streams.ScheduledWorkflowPause,
		&c.Streams.SplitActivityAResult,
		&c.Streams.SplitOnDemandJobs,
		&c.Streams.SubmitActivityJob,
		&c.Streams.SubmitFanOutWorkflowJob,
		&c.Streams.SubmitWorkflowJob,
		&c.Streams.TemporalActivitySchedule,
		&c.Streams.TemporalWorkflowSchedule,
		&c.Streams.WorkflowPause,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.LocalCron,
		&c.DataConnectors.Temporal,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.ActivityJob,
		&c.Endpoints.FanOutActivityA,
		&c.Endpoints.FanOutActivityB,
		&c.Endpoints.FanOutActivityC,
		&c.Endpoints.FanOutWorkflowJob,
		&c.Endpoints.LocalSchedule,
		&c.Endpoints.SequentialActivityA,
		&c.Endpoints.SequentialActivityB,
		&c.Endpoints.TemporalActivitySchedule,
		&c.Endpoints.TemporalWorkflowSchedule,
		&c.Endpoints.WorkflowJob,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{
		&c.Pools.DefaultPool,
	}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{
		&c.Links.CallSequentialActivityAToCallSequentialActivityB,
		&c.Links.CallSequentialActivityBToProcessWorkflowJob,
		&c.Links.ConsumeActivityJobToActivityPause,
		&c.Links.ConsumeFanOutActivityAToProcessFanOutActivityA,
		&c.Links.ConsumeFanOutActivityBToProcessFanOutActivityB,
		&c.Links.ConsumeFanOutActivityCToProcessFanOutActivityC,
		&c.Links.ConsumeFanOutWorkflowJobToCallFanOutActivityA,
		&c.Links.ConsumeSequentialActivityAToProcessSequentialActivityA,
		&c.Links.ConsumeSequentialActivityBToProcessSequentialActivityB,
		&c.Links.ConsumeWorkflowJobToWorkflowPause,
		&c.Links.SplitActivityAResultToCallFanOutActivityB,
		&c.Links.SplitActivityAResultToCallFanOutActivityC,
		&c.Links.WorkflowPauseToCallSequentialActivityA,
	}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.AutomationJob,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyActivityJobEnabled(); err != nil {
		return err
	}
	if err := c.applyActivityJobTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyActivityPauseDuration(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceDefaultGrpcTimeout(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyAutomationServiceHttpPort(); err != nil {
		return err
	}
	if err := c.applyDefaultPoolExecutorsCount(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityAEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityATracingEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityBEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityBTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityCEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutActivityCTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutWorkflowJobEnabled(); err != nil {
		return err
	}
	if err := c.applyFanOutWorkflowJobTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyLocalScheduleEnabled(); err != nil {
		return err
	}
	if err := c.applyLocalScheduleTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyScheduledActivityPauseDuration(); err != nil {
		return err
	}
	if err := c.applyScheduledWorkflowPauseDuration(); err != nil {
		return err
	}
	if err := c.applySequentialActivityAEnabled(); err != nil {
		return err
	}
	if err := c.applySequentialActivityATracingEnabled(); err != nil {
		return err
	}
	if err := c.applySequentialActivityBEnabled(); err != nil {
		return err
	}
	if err := c.applySequentialActivityBTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyTemporalActivityScheduleEnabled(); err != nil {
		return err
	}
	if err := c.applyTemporalActivityScheduleTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyTemporalAddress(); err != nil {
		return err
	}
	if err := c.applyTemporalWorkflowScheduleEnabled(); err != nil {
		return err
	}
	if err := c.applyTemporalWorkflowScheduleTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyWorkflowJobEnabled(); err != nil {
		return err
	}
	if err := c.applyWorkflowJobTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyWorkflowPauseDuration(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyActivityJobEnabled() error {
	value, exists := os.LookupEnv("ACTIVITY_JOB_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ACTIVITY_JOB_ENABLED to bool: %w", err)
	}
	c.Endpoints.ActivityJob.Enabled = boolVal

	return nil
}

func (c *Config) applyActivityJobTracingEnabled() error {
	value, exists := os.LookupEnv("ACTIVITY_JOB_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ACTIVITY_JOB_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.ActivityJob.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyActivityPauseDuration() error {
	value, exists := os.LookupEnv("ACTIVITY_PAUSE_DURATION")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ACTIVITY_PAUSE_DURATION to int: %w", err)
	}
	c.Streams.ActivityPause.Duration = intVal

	return nil
}

func (c *Config) applyAutomationServiceDefaultGrpcTimeout() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_DEFAULT_GRPC_TIMEOUT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert AUTOMATION_SERVICE_DEFAULT_GRPC_TIMEOUT to int: %w", err)
	}
	c.Services.AutomationService.DefaultGrpcTimeout = intVal

	return nil
}

func (c *Config) applyAutomationServiceEnvironment() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.AutomationService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyAutomationServiceGrpcHost() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.AutomationService.GrpcHost = value

	return nil
}

func (c *Config) applyAutomationServiceGrpcPort() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert AUTOMATION_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.AutomationService.GrpcPort = intVal

	return nil
}

func (c *Config) applyAutomationServiceHttpHost() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.AutomationService.HttpHost = value

	return nil
}

func (c *Config) applyAutomationServiceHttpPort() error {
	value, exists := os.LookupEnv("AUTOMATION_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert AUTOMATION_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.AutomationService.HttpPort = intVal

	return nil
}

func (c *Config) applyDefaultPoolExecutorsCount() error {
	value, exists := os.LookupEnv("DEFAULT_POOL_EXECUTORS_COUNT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert DEFAULT_POOL_EXECUTORS_COUNT to int: %w", err)
	}
	c.Pools.DefaultPool.ExecutorsCount = intVal

	return nil
}

func (c *Config) applyFanOutActivityAEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_A_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_A_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityA.Enabled = boolVal

	return nil
}

func (c *Config) applyFanOutActivityATracingEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_A_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_A_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityA.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyFanOutActivityBEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_B_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_B_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityB.Enabled = boolVal

	return nil
}

func (c *Config) applyFanOutActivityBTracingEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_B_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_B_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityB.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyFanOutActivityCEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_C_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_C_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityC.Enabled = boolVal

	return nil
}

func (c *Config) applyFanOutActivityCTracingEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_ACTIVITY_C_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_ACTIVITY_C_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutActivityC.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyFanOutWorkflowJobEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_WORKFLOW_JOB_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_WORKFLOW_JOB_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutWorkflowJob.Enabled = boolVal

	return nil
}

func (c *Config) applyFanOutWorkflowJobTracingEnabled() error {
	value, exists := os.LookupEnv("FAN_OUT_WORKFLOW_JOB_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert FAN_OUT_WORKFLOW_JOB_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.FanOutWorkflowJob.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyLocalScheduleEnabled() error {
	value, exists := os.LookupEnv("LOCAL_SCHEDULE_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert LOCAL_SCHEDULE_ENABLED to bool: %w", err)
	}
	c.Endpoints.LocalSchedule.Enabled = boolVal

	return nil
}

func (c *Config) applyLocalScheduleTracingEnabled() error {
	value, exists := os.LookupEnv("LOCAL_SCHEDULE_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert LOCAL_SCHEDULE_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.LocalSchedule.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyScheduledActivityPauseDuration() error {
	value, exists := os.LookupEnv("SCHEDULED_ACTIVITY_PAUSE_DURATION")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert SCHEDULED_ACTIVITY_PAUSE_DURATION to int: %w", err)
	}
	c.Streams.ScheduledActivityPause.Duration = intVal

	return nil
}

func (c *Config) applyScheduledWorkflowPauseDuration() error {
	value, exists := os.LookupEnv("SCHEDULED_WORKFLOW_PAUSE_DURATION")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert SCHEDULED_WORKFLOW_PAUSE_DURATION to int: %w", err)
	}
	c.Streams.ScheduledWorkflowPause.Duration = intVal

	return nil
}

func (c *Config) applySequentialActivityAEnabled() error {
	value, exists := os.LookupEnv("SEQUENTIAL_ACTIVITY_A_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert SEQUENTIAL_ACTIVITY_A_ENABLED to bool: %w", err)
	}
	c.Endpoints.SequentialActivityA.Enabled = boolVal

	return nil
}

func (c *Config) applySequentialActivityATracingEnabled() error {
	value, exists := os.LookupEnv("SEQUENTIAL_ACTIVITY_A_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert SEQUENTIAL_ACTIVITY_A_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.SequentialActivityA.TracingEnabled = boolVal

	return nil
}

func (c *Config) applySequentialActivityBEnabled() error {
	value, exists := os.LookupEnv("SEQUENTIAL_ACTIVITY_B_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert SEQUENTIAL_ACTIVITY_B_ENABLED to bool: %w", err)
	}
	c.Endpoints.SequentialActivityB.Enabled = boolVal

	return nil
}

func (c *Config) applySequentialActivityBTracingEnabled() error {
	value, exists := os.LookupEnv("SEQUENTIAL_ACTIVITY_B_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert SEQUENTIAL_ACTIVITY_B_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.SequentialActivityB.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyTemporalActivityScheduleEnabled() error {
	value, exists := os.LookupEnv("TEMPORAL_ACTIVITY_SCHEDULE_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert TEMPORAL_ACTIVITY_SCHEDULE_ENABLED to bool: %w", err)
	}
	c.Endpoints.TemporalActivitySchedule.Enabled = boolVal

	return nil
}

func (c *Config) applyTemporalActivityScheduleTracingEnabled() error {
	value, exists := os.LookupEnv("TEMPORAL_ACTIVITY_SCHEDULE_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert TEMPORAL_ACTIVITY_SCHEDULE_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.TemporalActivitySchedule.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyTemporalAddress() error {
	value, exists := os.LookupEnv("TEMPORAL_ADDRESS")
	if !exists {
		return nil
	}

	c.DataConnectors.Temporal.Address = value

	return nil
}

func (c *Config) applyTemporalWorkflowScheduleEnabled() error {
	value, exists := os.LookupEnv("TEMPORAL_WORKFLOW_SCHEDULE_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert TEMPORAL_WORKFLOW_SCHEDULE_ENABLED to bool: %w", err)
	}
	c.Endpoints.TemporalWorkflowSchedule.Enabled = boolVal

	return nil
}

func (c *Config) applyTemporalWorkflowScheduleTracingEnabled() error {
	value, exists := os.LookupEnv("TEMPORAL_WORKFLOW_SCHEDULE_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert TEMPORAL_WORKFLOW_SCHEDULE_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.TemporalWorkflowSchedule.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyWorkflowJobEnabled() error {
	value, exists := os.LookupEnv("WORKFLOW_JOB_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert WORKFLOW_JOB_ENABLED to bool: %w", err)
	}
	c.Endpoints.WorkflowJob.Enabled = boolVal

	return nil
}

func (c *Config) applyWorkflowJobTracingEnabled() error {
	value, exists := os.LookupEnv("WORKFLOW_JOB_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert WORKFLOW_JOB_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.WorkflowJob.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyWorkflowPauseDuration() error {
	value, exists := os.LookupEnv("WORKFLOW_PAUSE_DURATION")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert WORKFLOW_PAUSE_DURATION to int: %w", err)
	}
	c.Streams.WorkflowPause.Duration = intVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			AutomationService cfg.ServiceConfig `yaml:"automationService" mapstructure:"automationService"`
		}{
			AutomationService: cfg.ServiceConfig{
				ID:    automationServiceServiceID,
				Name:  "Automation Service",
				Color: "#00A86B",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:               "0.0.0.0",
				GrpcPort:               9204,
				HttpHost:               "0.0.0.0",
				HttpPort:               9094,
				MetricsHandler:         "metrics",
				StartupHandler:         "health/startup",
				ReadinessHandler:       "health/ready",
				LivenessHandler:        "health/live",
				KubernetesWorkloadType: "Deployment",
				ShutdownTimeout:        30000,
				StatusHandler:          "status",
				GolangVersion:          "1.25.4",
				ModulePath:             "github.com/gorundebug/rustexample-automationservice",
			},
		},
		Streams: struct {
			ActivityPause              cfg.DelayStreamConfig `yaml:"activityPause" mapstructure:"activityPause"`
			CallFanOutActivityA        cfg.SinkStreamConfig  `yaml:"callFanOutActivityA" mapstructure:"callFanOutActivityA"`
			CallFanOutActivityB        cfg.SinkStreamConfig  `yaml:"callFanOutActivityB" mapstructure:"callFanOutActivityB"`
			CallFanOutActivityC        cfg.SinkStreamConfig  `yaml:"callFanOutActivityC" mapstructure:"callFanOutActivityC"`
			CallSequentialActivityA    cfg.SinkStreamConfig  `yaml:"callSequentialActivityA" mapstructure:"callSequentialActivityA"`
			CallSequentialActivityB    cfg.SinkStreamConfig  `yaml:"callSequentialActivityB" mapstructure:"callSequentialActivityB"`
			ConsumeActivityJob         cfg.InputStreamConfig `yaml:"consumeActivityJob" mapstructure:"consumeActivityJob"`
			ConsumeFanOutActivityA     cfg.InputStreamConfig `yaml:"consumeFanOutActivityA" mapstructure:"consumeFanOutActivityA"`
			ConsumeFanOutActivityB     cfg.InputStreamConfig `yaml:"consumeFanOutActivityB" mapstructure:"consumeFanOutActivityB"`
			ConsumeFanOutActivityC     cfg.InputStreamConfig `yaml:"consumeFanOutActivityC" mapstructure:"consumeFanOutActivityC"`
			ConsumeFanOutWorkflowJob   cfg.InputStreamConfig `yaml:"consumeFanOutWorkflowJob" mapstructure:"consumeFanOutWorkflowJob"`
			ConsumeSequentialActivityA cfg.InputStreamConfig `yaml:"consumeSequentialActivityA" mapstructure:"consumeSequentialActivityA"`
			ConsumeSequentialActivityB cfg.InputStreamConfig `yaml:"consumeSequentialActivityB" mapstructure:"consumeSequentialActivityB"`
			ConsumeWorkflowJob         cfg.InputStreamConfig `yaml:"consumeWorkflowJob" mapstructure:"consumeWorkflowJob"`
			LocalSchedule              cfg.InputStreamConfig `yaml:"localSchedule" mapstructure:"localSchedule"`
			ObserveActivityResult      cfg.MapStreamConfig   `yaml:"observeActivityResult" mapstructure:"observeActivityResult"`
			ObserveFanOutActivityB     cfg.MapStreamConfig   `yaml:"observeFanOutActivityB" mapstructure:"observeFanOutActivityB"`
			ObserveFanOutActivityC     cfg.MapStreamConfig   `yaml:"observeFanOutActivityC" mapstructure:"observeFanOutActivityC"`
			ObserveWorkflowResult      cfg.MapStreamConfig   `yaml:"observeWorkflowResult" mapstructure:"observeWorkflowResult"`
			ProcessActivityJob         cfg.MapStreamConfig   `yaml:"processActivityJob" mapstructure:"processActivityJob"`
			ProcessFanOutActivityA     cfg.MapStreamConfig   `yaml:"processFanOutActivityA" mapstructure:"processFanOutActivityA"`
			ProcessFanOutActivityB     cfg.MapStreamConfig   `yaml:"processFanOutActivityB" mapstructure:"processFanOutActivityB"`
			ProcessFanOutActivityC     cfg.MapStreamConfig   `yaml:"processFanOutActivityC" mapstructure:"processFanOutActivityC"`
			ProcessScheduledActivity   cfg.MapStreamConfig   `yaml:"processScheduledActivity" mapstructure:"processScheduledActivity"`
			ProcessScheduledWorkflow   cfg.MapStreamConfig   `yaml:"processScheduledWorkflow" mapstructure:"processScheduledWorkflow"`
			ProcessSequentialActivityA cfg.MapStreamConfig   `yaml:"processSequentialActivityA" mapstructure:"processSequentialActivityA"`
			ProcessSequentialActivityB cfg.MapStreamConfig   `yaml:"processSequentialActivityB" mapstructure:"processSequentialActivityB"`
			ProcessWorkflowJob         cfg.MapStreamConfig   `yaml:"processWorkflowJob" mapstructure:"processWorkflowJob"`
			ScheduledActivityPause     cfg.DelayStreamConfig `yaml:"scheduledActivityPause" mapstructure:"scheduledActivityPause"`
			ScheduledWorkflowPause     cfg.DelayStreamConfig `yaml:"scheduledWorkflowPause" mapstructure:"scheduledWorkflowPause"`
			SplitActivityAResult       cfg.SplitStreamConfig `yaml:"splitActivityAResult" mapstructure:"splitActivityAResult"`
			SplitOnDemandJobs          cfg.SplitStreamConfig `yaml:"splitOnDemandJobs" mapstructure:"splitOnDemandJobs"`
			SubmitActivityJob          cfg.SinkStreamConfig  `yaml:"submitActivityJob" mapstructure:"submitActivityJob"`
			SubmitFanOutWorkflowJob    cfg.SinkStreamConfig  `yaml:"submitFanOutWorkflowJob" mapstructure:"submitFanOutWorkflowJob"`
			SubmitWorkflowJob          cfg.SinkStreamConfig  `yaml:"submitWorkflowJob" mapstructure:"submitWorkflowJob"`
			TemporalActivitySchedule   cfg.InputStreamConfig `yaml:"temporalActivitySchedule" mapstructure:"temporalActivitySchedule"`
			TemporalWorkflowSchedule   cfg.InputStreamConfig `yaml:"temporalWorkflowSchedule" mapstructure:"temporalWorkflowSchedule"`
			WorkflowPause              cfg.DelayStreamConfig `yaml:"workflowPause" mapstructure:"workflowPause"`
		}{
			ActivityPause: cfg.DelayStreamConfig{
				ID:                  activityPauseStreamID,
				Name:                "Activity Pause",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeActivityJobStreamID,
				XPos:                -251,
				YPos:                219,
				Duration:            250,
				FunctionPackage:     "automation",
				FunctionName:        "ActivityPause",
				FunctionDescription: "Apply the ordinary local Delay while processing an on-demand Temporal Activity.\n",
			},

			CallFanOutActivityA: cfg.SinkStreamConfig{
				ID:         callFanOutActivityAStreamID,
				Name:       "Call Fan-Out Activity A",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   consumeFanOutWorkflowJobStreamID,
				XPos:       -271,
				YPos:       1284,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityAEndpointID,
			},

			CallFanOutActivityB: cfg.SinkStreamConfig{
				ID:         callFanOutActivityBStreamID,
				Name:       "Call Fan-Out Activity B",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   splitActivityAResultStreamID,
				XPos:       7,
				YPos:       990,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityBEndpointID,
			},

			CallFanOutActivityC: cfg.SinkStreamConfig{
				ID:         callFanOutActivityCStreamID,
				Name:       "Call Fan-Out Activity C",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   splitActivityAResultStreamID,
				XPos:       317,
				YPos:       1313,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityCEndpointID,
			},

			CallSequentialActivityA: cfg.SinkStreamConfig{
				ID:         callSequentialActivityAStreamID,
				Name:       "Call Sequential Activity A",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   workflowPauseStreamID,
				XPos:       49,
				YPos:       473,
				ValueType:  "AutomationJob",
				IdEndpoint: sequentialActivityAEndpointID,
			},

			CallSequentialActivityB: cfg.SinkStreamConfig{
				ID:         callSequentialActivityBStreamID,
				Name:       "Call Sequential Activity B",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   callSequentialActivityAStreamID,
				XPos:       270,
				YPos:       650,
				ValueType:  "AutomationJob",
				IdEndpoint: sequentialActivityBEndpointID,
			},

			ConsumeActivityJob: cfg.InputStreamConfig{
				ID:         consumeActivityJobStreamID,
				Name:       "Consume Activity Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processActivityJobStreamID,
				XPos:       -500,
				YPos:       350,
				ValueType:  "AutomationJob",
				IdEndpoint: activityJobEndpointID,
			},

			ConsumeFanOutActivityA: cfg.InputStreamConfig{
				ID:         consumeFanOutActivityAStreamID,
				Name:       "Consume Fan-Out Activity A",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processFanOutActivityAStreamID,
				XPos:       -277,
				YPos:       1051,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityAEndpointID,
			},

			ConsumeFanOutActivityB: cfg.InputStreamConfig{
				ID:         consumeFanOutActivityBStreamID,
				Name:       "Consume Fan-Out Activity B",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processFanOutActivityBStreamID,
				XPos:       295,
				YPos:       996,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityBEndpointID,
			},

			ConsumeFanOutActivityC: cfg.InputStreamConfig{
				ID:         consumeFanOutActivityCStreamID,
				Name:       "Consume Fan-Out Activity C",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processFanOutActivityCStreamID,
				XPos:       553,
				YPos:       1503,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutActivityCEndpointID,
			},

			ConsumeFanOutWorkflowJob: cfg.InputStreamConfig{
				ID:         consumeFanOutWorkflowJobStreamID,
				Name:       "Consume Fan-Out Workflow Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				XPos:       -635,
				YPos:       1287,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutWorkflowJobEndpointID,
			},

			ConsumeSequentialActivityA: cfg.InputStreamConfig{
				ID:         consumeSequentialActivityAStreamID,
				Name:       "Consume Sequential Activity A",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processSequentialActivityAStreamID,
				XPos:       302,
				YPos:       489,
				ValueType:  "AutomationJob",
				IdEndpoint: sequentialActivityAEndpointID,
			},

			ConsumeSequentialActivityB: cfg.InputStreamConfig{
				ID:         consumeSequentialActivityBStreamID,
				Name:       "Consume Sequential Activity B",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processSequentialActivityBStreamID,
				XPos:       503,
				YPos:       658,
				ValueType:  "AutomationJob",
				IdEndpoint: sequentialActivityBEndpointID,
			},

			ConsumeWorkflowJob: cfg.InputStreamConfig{
				ID:         consumeWorkflowJobStreamID,
				Name:       "Consume Workflow Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processWorkflowJobStreamID,
				XPos:       -515,
				YPos:       635,
				ValueType:  "AutomationJob",
				IdEndpoint: workflowJobEndpointID,
			},

			LocalSchedule: cfg.InputStreamConfig{
				ID:         localScheduleStreamID,
				Name:       "Local Schedule",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				XPos:       -1250,
				YPos:       500,
				ValueType:  "AutomationJob",
				IdEndpoint: localScheduleEndpointID,
			},

			ObserveActivityResult: cfg.MapStreamConfig{
				ID:                  observeActivityResultStreamID,
				Name:                "Observe Activity Result",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            submitActivityJobStreamID,
				XPos:                -500,
				YPos:                500,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ObserveActivityResult",
				FunctionDescription: "Preserve the result returned through the on-demand Activity endpoint.\n",
			},

			ObserveFanOutActivityB: cfg.MapStreamConfig{
				ID:                  observeFanOutActivityBStreamID,
				Name:                "Observe Fan-Out Activity B",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            callFanOutActivityBStreamID,
				XPos:                -11,
				YPos:                793,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ObserveFanoutActivityB",
				FunctionDescription: "Observe the typed result returned by the Activity B fan-out branch.\n",
			},

			ObserveFanOutActivityC: cfg.MapStreamConfig{
				ID:                  observeFanOutActivityCStreamID,
				Name:                "Observe Fan-Out Activity C",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            callFanOutActivityCStreamID,
				XPos:                587,
				YPos:                1121,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ObserveFanoutActivityC",
				FunctionDescription: "Observe the typed result returned by the Activity C fan-out branch.\n",
			},

			ObserveWorkflowResult: cfg.MapStreamConfig{
				ID:                  observeWorkflowResultStreamID,
				Name:                "Observe Workflow Result",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            submitWorkflowJobStreamID,
				XPos:                -650,
				YPos:                788,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ObserveWorkflowResult",
				FunctionDescription: "Preserve the result returned through the on-demand Workflow endpoint.\n",
			},

			ProcessActivityJob: cfg.MapStreamConfig{
				ID:                  processActivityJobStreamID,
				Name:                "Process Activity Job",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            activityPauseStreamID,
				XPos:                10,
				YPos:                350,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessActivityJob",
				FunctionDescription: "Record Activity progress with DurableCallHeartbeat and return the processed job result.\n",
			},

			ProcessFanOutActivityA: cfg.MapStreamConfig{
				ID:                  processFanOutActivityAStreamID,
				Name:                "Process Fan-Out Activity A",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeFanOutActivityAStreamID,
				XPos:                -268,
				YPos:                819,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessFanoutActivityA",
				FunctionDescription: "Return Activity A's typed result before the Workflow Split.\n",
			},

			ProcessFanOutActivityB: cfg.MapStreamConfig{
				ID:                  processFanOutActivityBStreamID,
				Name:                "Process Fan-Out Activity B",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeFanOutActivityBStreamID,
				XPos:                705,
				YPos:                1001,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessFanoutActivityB",
				FunctionDescription: "Return Activity B's typed fan-out result.\n",
			},

			ProcessFanOutActivityC: cfg.MapStreamConfig{
				ID:                  processFanOutActivityCStreamID,
				Name:                "Process Fan-Out Activity C",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeFanOutActivityCStreamID,
				XPos:                931,
				YPos:                1493,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessFanoutActivityC",
				FunctionDescription: "Return Activity C's typed fan-out result.\n",
			},

			ProcessScheduledActivity: cfg.MapStreamConfig{
				ID:                  processScheduledActivityStreamID,
				Name:                "Process Scheduled Activity",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            scheduledActivityPauseStreamID,
				XPos:                -1442,
				YPos:                655,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessScheduledActivity",
				FunctionDescription: "Return the visible result of one scheduled Activity execution.\n",
			},

			ProcessScheduledWorkflow: cfg.MapStreamConfig{
				ID:                  processScheduledWorkflowStreamID,
				Name:                "Process Scheduled Workflow",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            scheduledWorkflowPauseStreamID,
				XPos:                -1411,
				YPos:                856,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessScheduledWorkflow",
				FunctionDescription: "Return the visible result of one scheduled Workflow execution.\n",
			},

			ProcessSequentialActivityA: cfg.MapStreamConfig{
				ID:                  processSequentialActivityAStreamID,
				Name:                "Process Sequential Activity A",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeSequentialActivityAStreamID,
				XPos:                568,
				YPos:                486,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessSequentialActivityA",
				FunctionDescription: "Return sequential Activity A's typed result to its Temporal sink.\n",
			},

			ProcessSequentialActivityB: cfg.MapStreamConfig{
				ID:                  processSequentialActivityBStreamID,
				Name:                "Process Sequential Activity B",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeSequentialActivityBStreamID,
				XPos:                804,
				YPos:                660,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessSequentialActivityB",
				FunctionDescription: "Return sequential Activity B's typed result to its Temporal sink.\n",
			},

			ProcessWorkflowJob: cfg.MapStreamConfig{
				ID:                  processWorkflowJobStreamID,
				Name:                "Process Workflow Job",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            callSequentialActivityBStreamID,
				XPos:                -59,
				YPos:                654,
				ValueType:           "AutomationJob",
				FunctionPackage:     "automation",
				FunctionName:        "ProcessWorkflowJob",
				FunctionDescription: "Continue the Workflow as new once, then return its final result.\n",
			},

			ScheduledActivityPause: cfg.DelayStreamConfig{
				ID:                  scheduledActivityPauseStreamID,
				Name:                "Scheduled Activity Pause",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            temporalActivityScheduleStreamID,
				XPos:                -1661,
				YPos:                402,
				Duration:            250,
				FunctionPackage:     "automation",
				FunctionName:        "ScheduledActivityPause",
				FunctionDescription: "Apply the ordinary local Delay inside an Activity started by Temporal Schedule.\n",
			},

			ScheduledWorkflowPause: cfg.DelayStreamConfig{
				ID:                  scheduledWorkflowPauseStreamID,
				Name:                "Scheduled Workflow Pause",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            temporalWorkflowScheduleStreamID,
				XPos:                -1684,
				YPos:                1167,
				Duration:            250,
				FunctionPackage:     "automation",
				FunctionName:        "ScheduledWorkflowPause",
				FunctionDescription: "Use the official Temporal Workflow timer for a scheduled Workflow.\n",
			},

			SplitActivityAResult: cfg.SplitStreamConfig{
				ID:        splitActivityAResultStreamID,
				Name:      "Split Activity A Result",
				Pipeline:  "automation",
				IdService: automationServiceServiceID,
				IdSource:  callFanOutActivityAStreamID,
				XPos:      40,
				YPos:      1312,
			},

			SplitOnDemandJobs: cfg.SplitStreamConfig{
				ID:        splitOnDemandJobsStreamID,
				Name:      "Split On-Demand Jobs",
				Pipeline:  "automation",
				IdService: automationServiceServiceID,
				IdSource:  localScheduleStreamID,
				XPos:      -1010,
				YPos:      500,
			},

			SubmitActivityJob: cfg.SinkStreamConfig{
				ID:         submitActivityJobStreamID,
				Name:       "Submit Activity Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   splitOnDemandJobsStreamID,
				XPos:       -760,
				YPos:       350,
				ValueType:  "AutomationJob",
				IdEndpoint: activityJobEndpointID,
			},

			SubmitFanOutWorkflowJob: cfg.SinkStreamConfig{
				ID:         submitFanOutWorkflowJobStreamID,
				Name:       "Submit Fan-Out Workflow Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   splitOnDemandJobsStreamID,
				XPos:       -967,
				YPos:       1034,
				ValueType:  "AutomationJob",
				IdEndpoint: fanOutWorkflowJobEndpointID,
			},

			SubmitWorkflowJob: cfg.SinkStreamConfig{
				ID:         submitWorkflowJobStreamID,
				Name:       "Submit Workflow Job",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   splitOnDemandJobsStreamID,
				XPos:       -807,
				YPos:       629,
				ValueType:  "AutomationJob",
				IdEndpoint: workflowJobEndpointID,
			},

			TemporalActivitySchedule: cfg.InputStreamConfig{
				ID:         temporalActivityScheduleStreamID,
				Name:       "Temporal Activity Schedule",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processScheduledActivityStreamID,
				XPos:       -1917,
				YPos:       639,
				ValueType:  "AutomationJob",
				IdEndpoint: temporalActivityScheduleEndpointID,
			},

			TemporalWorkflowSchedule: cfg.InputStreamConfig{
				ID:         temporalWorkflowScheduleStreamID,
				Name:       "Temporal Workflow Schedule",
				Pipeline:   "automation",
				IdService:  automationServiceServiceID,
				IdSource:   processScheduledWorkflowStreamID,
				XPos:       -1906,
				YPos:       846,
				ValueType:  "AutomationJob",
				IdEndpoint: temporalWorkflowScheduleEndpointID,
			},

			WorkflowPause: cfg.DelayStreamConfig{
				ID:                  workflowPauseStreamID,
				Name:                "Workflow Pause",
				Pipeline:            "automation",
				IdService:           automationServiceServiceID,
				IdSource:            consumeWorkflowJobStreamID,
				XPos:                -233,
				YPos:                504,
				Duration:            250,
				FunctionPackage:     "automation",
				FunctionName:        "WorkflowPause",
				FunctionDescription: "Use the same Delay contract backed by the Temporal Workflow timer.\n",
			},
		},
		DataConnectors: struct {
			LocalCron cfg.CronDataConnectorConfig     `yaml:"localCron" mapstructure:"localCron"`
			Temporal  cfg.TemporalDataConnectorConfig `yaml:"temporal" mapstructure:"temporal"`
		}{
			LocalCron: cfg.CronDataConnectorConfig{
				ID:             localCronConnectorID,
				Name:           "Local Cron",
				Implementation: api.DataConnectorImplementationGoGocron,
			},

			Temporal: cfg.TemporalDataConnectorConfig{
				ID:                      temporalConnectorID,
				Name:                    "Temporal",
				Implementation:          api.DataConnectorImplementationTemporalGo,
				Address:                 "temporal:7233",
				Namespace:               "default",
				Identity:                "example-automation",
				MaxConcurrentActivities: 2,
				MaxConcurrentWorkflows:  4,
			},
		},
		Endpoints: struct {
			ActivityJob              cfg.TemporalEndpointConfig `yaml:"activityJob" mapstructure:"activityJob"`
			FanOutActivityA          cfg.TemporalEndpointConfig `yaml:"fanOutActivityA" mapstructure:"fanOutActivityA"`
			FanOutActivityB          cfg.TemporalEndpointConfig `yaml:"fanOutActivityB" mapstructure:"fanOutActivityB"`
			FanOutActivityC          cfg.TemporalEndpointConfig `yaml:"fanOutActivityC" mapstructure:"fanOutActivityC"`
			FanOutWorkflowJob        cfg.TemporalEndpointConfig `yaml:"fanOutWorkflowJob" mapstructure:"fanOutWorkflowJob"`
			LocalSchedule            cfg.CronEndpointConfig     `yaml:"localSchedule" mapstructure:"localSchedule"`
			SequentialActivityA      cfg.TemporalEndpointConfig `yaml:"sequentialActivityA" mapstructure:"sequentialActivityA"`
			SequentialActivityB      cfg.TemporalEndpointConfig `yaml:"sequentialActivityB" mapstructure:"sequentialActivityB"`
			TemporalActivitySchedule cfg.TemporalEndpointConfig `yaml:"temporalActivitySchedule" mapstructure:"temporalActivitySchedule"`
			TemporalWorkflowSchedule cfg.TemporalEndpointConfig `yaml:"temporalWorkflowSchedule" mapstructure:"temporalWorkflowSchedule"`
			WorkflowJob              cfg.TemporalEndpointConfig `yaml:"workflowJob" mapstructure:"workflowJob"`
		}{
			ActivityJob: cfg.TemporalEndpointConfig{
				ID:                          activityJobEndpointID,
				Name:                        "Activity Job",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			FanOutActivityA: cfg.TemporalEndpointConfig{
				ID:                          fanOutActivityAEndpointID,
				Name:                        "Fan-Out Activity A",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			FanOutActivityB: cfg.TemporalEndpointConfig{
				ID:                          fanOutActivityBEndpointID,
				Name:                        "Fan-Out Activity B",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			FanOutActivityC: cfg.TemporalEndpointConfig{
				ID:                          fanOutActivityCEndpointID,
				Name:                        "Fan-Out Activity C",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			FanOutWorkflowJob: cfg.TemporalEndpointConfig{
				ID:                       fanOutWorkflowJobEndpointID,
				Name:                     "Fan-Out Workflow Job",
				IdDataConnector:          temporalConnectorID,
				Enabled:                  true,
				TaskQueue:                "automation-workflow-jobs",
				TemporalExecutionType:    api.Workflow,
				Timezone:                 "UTC",
				OverlapPolicy:            api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:          api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout: 60000,
				MaximumAttempts:          3,
			},

			LocalSchedule: cfg.CronEndpointConfig{
				ID:              localScheduleEndpointID,
				Name:            "Local Schedule",
				IdDataConnector: localCronConnectorID,
				Enabled:         true,
				Schedule:        "*/5 * * * *",
				Timezone:        "UTC",
				OverlapPolicy:   api.ScheduleOverlapPolicySkip,
				MissedRunPolicy: api.ScheduleMissedRunPolicyFireOnce,
			},

			SequentialActivityA: cfg.TemporalEndpointConfig{
				ID:                          sequentialActivityAEndpointID,
				Name:                        "Sequential Activity A",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			SequentialActivityB: cfg.TemporalEndpointConfig{
				ID:                          sequentialActivityBEndpointID,
				Name:                        "Sequential Activity B",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-jobs",
				TemporalExecutionType:       api.Activity,
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			TemporalActivitySchedule: cfg.TemporalEndpointConfig{
				ID:                          temporalActivityScheduleEndpointID,
				Name:                        "Temporal Activity Schedule",
				IdDataConnector:             temporalConnectorID,
				Enabled:                     true,
				TaskQueue:                   "automation-activity-schedules",
				TemporalExecutionType:       api.Activity,
				Schedule:                    "*/10 * * * *",
				ScheduleID:                  "example-automation-activity-schedule",
				Timezone:                    "UTC",
				OverlapPolicy:               api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:             api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout:    60000,
				ActivityStartToCloseTimeout: 30000,
				ActivityHeartbeatTimeout:    5000,
				MaximumAttempts:             3,
			},

			TemporalWorkflowSchedule: cfg.TemporalEndpointConfig{
				ID:                       temporalWorkflowScheduleEndpointID,
				Name:                     "Temporal Workflow Schedule",
				IdDataConnector:          temporalConnectorID,
				Enabled:                  true,
				TaskQueue:                "automation-workflow-schedules",
				TemporalExecutionType:    api.Workflow,
				Schedule:                 "*/10 * * * *",
				ScheduleID:               "example-automation-workflow-schedule",
				Timezone:                 "UTC",
				OverlapPolicy:            api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:          api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout: 60000,
				MaximumAttempts:          3,
			},

			WorkflowJob: cfg.TemporalEndpointConfig{
				ID:                       workflowJobEndpointID,
				Name:                     "Workflow Job",
				IdDataConnector:          temporalConnectorID,
				Enabled:                  true,
				TaskQueue:                "automation-workflow-jobs",
				TemporalExecutionType:    api.Workflow,
				Timezone:                 "UTC",
				OverlapPolicy:            api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:          api.ScheduleMissedRunPolicyFireOnce,
				WorkflowExecutionTimeout: 60000,
				MaximumAttempts:          3,
			},
		},
		Pools: struct {
			DefaultPool cfg.PoolConfig `yaml:"defaultPool" mapstructure:"defaultPool"`
		}{
			DefaultPool: cfg.PoolConfig{
				Name:           "Default Pool",
				ExecutorsCount: 2,
			},
		},
		Links: struct {
			CallSequentialActivityAToCallSequentialActivityB       cfg.LinkConfig `yaml:"callSequentialActivityAToCallSequentialActivityB" mapstructure:"callSequentialActivityAToCallSequentialActivityB"`
			CallSequentialActivityBToProcessWorkflowJob            cfg.LinkConfig `yaml:"callSequentialActivityBToProcessWorkflowJob" mapstructure:"callSequentialActivityBToProcessWorkflowJob"`
			ConsumeActivityJobToActivityPause                      cfg.LinkConfig `yaml:"consumeActivityJobToActivityPause" mapstructure:"consumeActivityJobToActivityPause"`
			ConsumeFanOutActivityAToProcessFanOutActivityA         cfg.LinkConfig `yaml:"consumeFanOutActivityAToProcessFanOutActivityA" mapstructure:"consumeFanOutActivityAToProcessFanOutActivityA"`
			ConsumeFanOutActivityBToProcessFanOutActivityB         cfg.LinkConfig `yaml:"consumeFanOutActivityBToProcessFanOutActivityB" mapstructure:"consumeFanOutActivityBToProcessFanOutActivityB"`
			ConsumeFanOutActivityCToProcessFanOutActivityC         cfg.LinkConfig `yaml:"consumeFanOutActivityCToProcessFanOutActivityC" mapstructure:"consumeFanOutActivityCToProcessFanOutActivityC"`
			ConsumeFanOutWorkflowJobToCallFanOutActivityA          cfg.LinkConfig `yaml:"consumeFanOutWorkflowJobToCallFanOutActivityA" mapstructure:"consumeFanOutWorkflowJobToCallFanOutActivityA"`
			ConsumeSequentialActivityAToProcessSequentialActivityA cfg.LinkConfig `yaml:"consumeSequentialActivityAToProcessSequentialActivityA" mapstructure:"consumeSequentialActivityAToProcessSequentialActivityA"`
			ConsumeSequentialActivityBToProcessSequentialActivityB cfg.LinkConfig `yaml:"consumeSequentialActivityBToProcessSequentialActivityB" mapstructure:"consumeSequentialActivityBToProcessSequentialActivityB"`
			ConsumeWorkflowJobToWorkflowPause                      cfg.LinkConfig `yaml:"consumeWorkflowJobToWorkflowPause" mapstructure:"consumeWorkflowJobToWorkflowPause"`
			SplitActivityAResultToCallFanOutActivityB              cfg.LinkConfig `yaml:"splitActivityAResultToCallFanOutActivityB" mapstructure:"splitActivityAResultToCallFanOutActivityB"`
			SplitActivityAResultToCallFanOutActivityC              cfg.LinkConfig `yaml:"splitActivityAResultToCallFanOutActivityC" mapstructure:"splitActivityAResultToCallFanOutActivityC"`
			WorkflowPauseToCallSequentialActivityA                 cfg.LinkConfig `yaml:"workflowPauseToCallSequentialActivityA" mapstructure:"workflowPauseToCallSequentialActivityA"`
		}{
			CallSequentialActivityAToCallSequentialActivityB: cfg.LinkConfig{
				From: callSequentialActivityAStreamID,
				To:   callSequentialActivityBStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			CallSequentialActivityBToProcessWorkflowJob: cfg.LinkConfig{
				From: callSequentialActivityBStreamID,
				To:   processWorkflowJobStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeActivityJobToActivityPause: cfg.LinkConfig{
				From: consumeActivityJobStreamID,
				To:   activityPauseStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeFanOutActivityAToProcessFanOutActivityA: cfg.LinkConfig{
				From: consumeFanOutActivityAStreamID,
				To:   processFanOutActivityAStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeFanOutActivityBToProcessFanOutActivityB: cfg.LinkConfig{
				From: consumeFanOutActivityBStreamID,
				To:   processFanOutActivityBStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeFanOutActivityCToProcessFanOutActivityC: cfg.LinkConfig{
				From: consumeFanOutActivityCStreamID,
				To:   processFanOutActivityCStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeFanOutWorkflowJobToCallFanOutActivityA: cfg.LinkConfig{
				From: consumeFanOutWorkflowJobStreamID,
				To:   callFanOutActivityAStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeSequentialActivityAToProcessSequentialActivityA: cfg.LinkConfig{
				From: consumeSequentialActivityAStreamID,
				To:   processSequentialActivityAStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeSequentialActivityBToProcessSequentialActivityB: cfg.LinkConfig{
				From: consumeSequentialActivityBStreamID,
				To:   processSequentialActivityBStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ConsumeWorkflowJobToWorkflowPause: cfg.LinkConfig{
				From: consumeWorkflowJobStreamID,
				To:   workflowPauseStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			SplitActivityAResultToCallFanOutActivityB: cfg.LinkConfig{
				From: splitActivityAResultStreamID,
				To:   callFanOutActivityBStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			SplitActivityAResultToCallFanOutActivityC: cfg.LinkConfig{
				From: splitActivityAResultStreamID,
				To:   callFanOutActivityCStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			WorkflowPauseToCallSequentialActivityA: cfg.LinkConfig{
				From: workflowPauseStreamID,
				To:   callSequentialActivityAStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
		},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/rustexample-inventory-service-api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/rustexample/model_go",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/rustexample-order-service-api",
			},
		},
		Types: struct {
			AutomationJob cfg.TypeConfig `yaml:"automationJob" mapstructure:"automationJob"`
		}{
			AutomationJob: cfg.TypeConfig{
				Name:       "AutomationJob",
				Type:       api.DataTypeString,
				Module:     "model",
				PublicType: true,
			},
		},
	}
}
