// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"fmt"

	datasourcetemporal "github.com/gorundebug/servicelib/datasource/temporal"
	"github.com/gorundebug/servicelib/runtime"

	config "github.com/gorundebug/rustexample-automationservice/internal/config"
)

// Connector resources are owned and registered by the runtime environment.
// Do not keep a duplicate registry in the generated service.
func initConnectors(cfg *config.Config, env runtime.RuntimeEnvironment) error {

	if _, err := datasourcetemporal.MakeConnector(cfg.DataConnectors.Temporal.ID, env); err != nil {
		return fmt.Errorf("init Temporal connector 'Temporal' failed: %w", err)
	}

	return nil
}
