// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"github.com/gorundebug/servicelib/runtime"

	activity "github.com/gorundebug/rustexample-automationservice/internal/functions/activity"
	cron "github.com/gorundebug/rustexample-automationservice/internal/functions/cron"
	datasink "github.com/gorundebug/servicelib/datasink"
	datasource "github.com/gorundebug/servicelib/datasource"
)

type serviceHandlers struct {
}

type serviceEndpoints struct {
	handlers serviceHandlers

	activityJob              runtime.Consumer[string]
	fanOutActivityA          runtime.Consumer[string]
	fanOutActivityB          runtime.Consumer[string]
	fanOutActivityC          runtime.Consumer[string]
	fanOutWorkflowJob        runtime.Consumer[string]
	sequentialActivityA      runtime.Consumer[string]
	sequentialActivityB      runtime.Consumer[string]
	workflowJob              runtime.Consumer[string]
	localSchedule            runtime.Consumer[string]
	temporalActivitySchedule runtime.Consumer[string]
	temporalWorkflowSchedule runtime.Consumer[string]

	callFanOutActivityAFanOutActivityA         runtime.Consumer[string]
	callFanOutActivityBFanOutActivityB         runtime.Consumer[string]
	callFanOutActivityCFanOutActivityC         runtime.Consumer[string]
	callSequentialActivityASequentialActivityA runtime.Consumer[string]
	callSequentialActivityBSequentialActivityB runtime.Consumer[string]
	submitActivityJobActivityJob               runtime.Consumer[string]
	submitFanOutWorkflowJobFanOutWorkflowJob   runtime.Consumer[string]
	submitWorkflowJobWorkflowJob               runtime.Consumer[string]
}

func (endpoints *serviceEndpoints) initEndpoints(s *Service) error {
	var err error

	if endpoints.activityJob, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeActivityJob, s.functions.activityActivityJobEndpointSource); err != nil {
		return err
	}
	if endpoints.fanOutActivityA, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeFanOutActivityA, s.functions.activityFanoutActivityAEndpointSource); err != nil {
		return err
	}
	if endpoints.fanOutActivityB, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeFanOutActivityB, s.functions.activityFanoutActivityBEndpointSource); err != nil {
		return err
	}
	if endpoints.fanOutActivityC, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeFanOutActivityC, s.functions.activityFanoutActivityCEndpointSource); err != nil {
		return err
	}
	if endpoints.fanOutWorkflowJob, err = datasource.TemporalWorkflowEndpointConsumerWithHandler(s.streams.consumeFanOutWorkflowJob, s.functions.workflowFanoutWorkflowJobEndpointSource, temporalWorkflowFanOutWorkflowJob); err != nil {
		return err
	}
	if endpoints.sequentialActivityA, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeSequentialActivityA, s.functions.activitySequentialActivityAEndpointSource); err != nil {
		return err
	}
	if endpoints.sequentialActivityB, err = datasource.TemporalEndpointConsumerWithHandler(s.streams.consumeSequentialActivityB, s.functions.activitySequentialActivityBEndpointSource); err != nil {
		return err
	}
	if endpoints.workflowJob, err = datasource.TemporalWorkflowEndpointConsumerWithHandler(s.streams.consumeWorkflowJob, s.functions.workflowWorkflowJobEndpointSource, temporalWorkflowWorkflowJob); err != nil {
		return err
	}
	if endpoints.localSchedule, err = cron.MakeEndpointConsumerLocalScheduleSource(s.streams.localSchedule, s.functions.cronLocalScheduleSource); err != nil {
		return err
	}
	if endpoints.temporalActivitySchedule, err = activity.MakeEndpointConsumerTemporalActivityScheduleSource(s.streams.temporalActivitySchedule, s.functions.activityTemporalActivityScheduleSource); err != nil {
		return err
	}
	if endpoints.temporalWorkflowSchedule, err = datasource.TemporalScheduleWorkflowEndpointConsumer(s.streams.temporalWorkflowSchedule, s.functions.workflowTemporalWorkflowScheduleSource, temporalWorkflowTemporalWorkflowSchedule); err != nil {
		return err
	}

	if endpoints.callFanOutActivityAFanOutActivityA, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.callFanOutActivityA, s.functions.activityFanoutActivityAEndpointSink); err != nil {
		return err
	}
	if endpoints.callFanOutActivityBFanOutActivityB, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.callFanOutActivityB, s.functions.activityFanoutActivityBEndpointSink); err != nil {
		return err
	}
	if endpoints.callFanOutActivityCFanOutActivityC, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.callFanOutActivityC, s.functions.activityFanoutActivityCEndpointSink); err != nil {
		return err
	}
	if endpoints.callSequentialActivityASequentialActivityA, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.callSequentialActivityA, s.functions.activitySequentialActivityAEndpointSink); err != nil {
		return err
	}
	if endpoints.callSequentialActivityBSequentialActivityB, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.callSequentialActivityB, s.functions.activitySequentialActivityBEndpointSink); err != nil {
		return err
	}
	if endpoints.submitActivityJobActivityJob, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.submitActivityJob, s.functions.activityActivityJobEndpointSink); err != nil {
		return err
	}
	if endpoints.submitFanOutWorkflowJobFanOutWorkflowJob, err = datasink.TemporalEndpointConsumerWithHandler(s.streams.submitFanOutWorkflowJob, s.functions.workflowFanoutWorkflowJobEndpointSink); err != nil {
		return err
	}
	if endpoints.submitWorkflowJobWorkflowJob, err = datasink.TemporalEndpointConsumerWithResultAndHandler(s.streams.submitWorkflowJob, s.functions.workflowWorkflowJobEndpointSink); err != nil {
		return err
	}
	return err
}
