// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/environment"
	"net/http"

	activity "github.com/gorundebug/rustexample-automationservice/internal/functions/activity"
	automation "github.com/gorundebug/rustexample-automationservice/internal/functions/automation"
	cron "github.com/gorundebug/rustexample-automationservice/internal/functions/cron"
	workflow "github.com/gorundebug/rustexample-automationservice/internal/functions/workflow"
)

type serviceMakers struct {
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)

	automationActivityPauseMaker              func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ActivityPause, error)
	automationProcessActivityJobMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessActivityJob, error)
	automationProcessFanoutActivityAMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityA, error)
	automationProcessFanoutActivityBMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityB, error)
	automationProcessFanoutActivityCMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityC, error)
	automationObserveFanoutActivityBMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveFanoutActivityB, error)
	automationObserveFanoutActivityCMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveFanoutActivityC, error)
	automationProcessSequentialActivityAMaker func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessSequentialActivityA, error)
	automationProcessSequentialActivityBMaker func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessSequentialActivityB, error)
	automationWorkflowPauseMaker              func(ctx context.Context, env environment.ServiceEnvironment) (*automation.WorkflowPause, error)
	automationProcessWorkflowJobMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessWorkflowJob, error)
	automationObserveActivityResultMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveActivityResult, error)
	automationObserveWorkflowResultMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveWorkflowResult, error)
	automationScheduledActivityPauseMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ScheduledActivityPause, error)
	automationProcessScheduledActivityMaker   func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessScheduledActivity, error)
	automationScheduledWorkflowPauseMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ScheduledWorkflowPause, error)
	automationProcessScheduledWorkflowMaker   func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessScheduledWorkflow, error)

	activityActivityJobEndpointSourceMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*activity.ActivityJobEndpointSource, error)
	activityFanoutActivityAEndpointSourceMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityAEndpointSource, error)
	activityFanoutActivityBEndpointSourceMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityBEndpointSource, error)
	activityFanoutActivityCEndpointSourceMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityCEndpointSource, error)
	workflowFanoutWorkflowJobEndpointSourceMaker   func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.FanoutWorkflowJobEndpointSource, error)
	activitySequentialActivityAEndpointSourceMaker func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityAEndpointSource, error)
	activitySequentialActivityBEndpointSourceMaker func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityBEndpointSource, error)
	workflowWorkflowJobEndpointSourceMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.WorkflowJobEndpointSource, error)
	cronLocalScheduleSourceMaker                   func(ctx context.Context, env environment.ServiceEnvironment) (*cron.LocalScheduleSource, error)
	activityTemporalActivityScheduleSourceMaker    func(ctx context.Context, env environment.ServiceEnvironment) (*activity.TemporalActivityScheduleSource, error)
	workflowTemporalWorkflowScheduleSourceMaker    func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.TemporalWorkflowScheduleSource, error)

	activityFanoutActivityAEndpointSinkMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityAEndpointSink, error)
	activityFanoutActivityBEndpointSinkMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityBEndpointSink, error)
	activityFanoutActivityCEndpointSinkMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityCEndpointSink, error)
	activitySequentialActivityAEndpointSinkMaker func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityAEndpointSink, error)
	activitySequentialActivityBEndpointSinkMaker func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityBEndpointSink, error)
	activityActivityJobEndpointSinkMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*activity.ActivityJobEndpointSink, error)
	workflowFanoutWorkflowJobEndpointSinkMaker   func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.FanoutWorkflowJobEndpointSink, error)
	workflowWorkflowJobEndpointSinkMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.WorkflowJobEndpointSink, error)
}

func (makers *serviceMakers) initMakers(ctx context.Context) error {

	if makers.automationActivityPauseMaker == nil {
		makers.automationActivityPauseMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ActivityPause, error) {
			return automation.MakeActivityPause(ctx, env)
		}
	}
	if makers.automationProcessActivityJobMaker == nil {
		makers.automationProcessActivityJobMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessActivityJob, error) {
			return automation.MakeProcessActivityJob(ctx, env)
		}
	}
	if makers.automationProcessFanoutActivityAMaker == nil {
		makers.automationProcessFanoutActivityAMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityA, error) {
			return automation.MakeProcessFanoutActivityA(ctx, env)
		}
	}
	if makers.automationProcessFanoutActivityBMaker == nil {
		makers.automationProcessFanoutActivityBMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityB, error) {
			return automation.MakeProcessFanoutActivityB(ctx, env)
		}
	}
	if makers.automationProcessFanoutActivityCMaker == nil {
		makers.automationProcessFanoutActivityCMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessFanoutActivityC, error) {
			return automation.MakeProcessFanoutActivityC(ctx, env)
		}
	}
	if makers.automationObserveFanoutActivityBMaker == nil {
		makers.automationObserveFanoutActivityBMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveFanoutActivityB, error) {
			return automation.MakeObserveFanoutActivityB(ctx, env)
		}
	}
	if makers.automationObserveFanoutActivityCMaker == nil {
		makers.automationObserveFanoutActivityCMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveFanoutActivityC, error) {
			return automation.MakeObserveFanoutActivityC(ctx, env)
		}
	}
	if makers.automationProcessSequentialActivityAMaker == nil {
		makers.automationProcessSequentialActivityAMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessSequentialActivityA, error) {
			return automation.MakeProcessSequentialActivityA(ctx, env)
		}
	}
	if makers.automationProcessSequentialActivityBMaker == nil {
		makers.automationProcessSequentialActivityBMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessSequentialActivityB, error) {
			return automation.MakeProcessSequentialActivityB(ctx, env)
		}
	}
	if makers.automationWorkflowPauseMaker == nil {
		makers.automationWorkflowPauseMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.WorkflowPause, error) {
			return automation.MakeWorkflowPause(ctx, env)
		}
	}
	if makers.automationProcessWorkflowJobMaker == nil {
		makers.automationProcessWorkflowJobMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessWorkflowJob, error) {
			return automation.MakeProcessWorkflowJob(ctx, env)
		}
	}
	if makers.automationObserveActivityResultMaker == nil {
		makers.automationObserveActivityResultMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveActivityResult, error) {
			return automation.MakeObserveActivityResult(ctx, env)
		}
	}
	if makers.automationObserveWorkflowResultMaker == nil {
		makers.automationObserveWorkflowResultMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ObserveWorkflowResult, error) {
			return automation.MakeObserveWorkflowResult(ctx, env)
		}
	}
	if makers.automationScheduledActivityPauseMaker == nil {
		makers.automationScheduledActivityPauseMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ScheduledActivityPause, error) {
			return automation.MakeScheduledActivityPause(ctx, env)
		}
	}
	if makers.automationProcessScheduledActivityMaker == nil {
		makers.automationProcessScheduledActivityMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessScheduledActivity, error) {
			return automation.MakeProcessScheduledActivity(ctx, env)
		}
	}
	if makers.automationScheduledWorkflowPauseMaker == nil {
		makers.automationScheduledWorkflowPauseMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ScheduledWorkflowPause, error) {
			return automation.MakeScheduledWorkflowPause(ctx, env)
		}
	}
	if makers.automationProcessScheduledWorkflowMaker == nil {
		makers.automationProcessScheduledWorkflowMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*automation.ProcessScheduledWorkflow, error) {
			return automation.MakeProcessScheduledWorkflow(ctx, env)
		}
	}

	if makers.activityActivityJobEndpointSourceMaker == nil {
		makers.activityActivityJobEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.ActivityJobEndpointSource, error) {
			return activity.MakeActivityJobEndpointSource(ctx, env)
		}
	}
	if makers.activityFanoutActivityAEndpointSourceMaker == nil {
		makers.activityFanoutActivityAEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityAEndpointSource, error) {
			return activity.MakeFanoutActivityAEndpointSource(ctx, env)
		}
	}
	if makers.activityFanoutActivityBEndpointSourceMaker == nil {
		makers.activityFanoutActivityBEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityBEndpointSource, error) {
			return activity.MakeFanoutActivityBEndpointSource(ctx, env)
		}
	}
	if makers.activityFanoutActivityCEndpointSourceMaker == nil {
		makers.activityFanoutActivityCEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityCEndpointSource, error) {
			return activity.MakeFanoutActivityCEndpointSource(ctx, env)
		}
	}
	if makers.workflowFanoutWorkflowJobEndpointSourceMaker == nil {
		makers.workflowFanoutWorkflowJobEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.FanoutWorkflowJobEndpointSource, error) {
			return workflow.MakeFanoutWorkflowJobEndpointSource(ctx, env)
		}
	}
	if makers.activitySequentialActivityAEndpointSourceMaker == nil {
		makers.activitySequentialActivityAEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityAEndpointSource, error) {
			return activity.MakeSequentialActivityAEndpointSource(ctx, env)
		}
	}
	if makers.activitySequentialActivityBEndpointSourceMaker == nil {
		makers.activitySequentialActivityBEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityBEndpointSource, error) {
			return activity.MakeSequentialActivityBEndpointSource(ctx, env)
		}
	}
	if makers.workflowWorkflowJobEndpointSourceMaker == nil {
		makers.workflowWorkflowJobEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.WorkflowJobEndpointSource, error) {
			return workflow.MakeWorkflowJobEndpointSource(ctx, env)
		}
	}
	if makers.cronLocalScheduleSourceMaker == nil {
		makers.cronLocalScheduleSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*cron.LocalScheduleSource, error) {
			return cron.MakeLocalScheduleSource(ctx, env)
		}
	}
	if makers.activityTemporalActivityScheduleSourceMaker == nil {
		makers.activityTemporalActivityScheduleSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.TemporalActivityScheduleSource, error) {
			return activity.MakeTemporalActivityScheduleSource(ctx, env)
		}
	}
	if makers.workflowTemporalWorkflowScheduleSourceMaker == nil {
		makers.workflowTemporalWorkflowScheduleSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.TemporalWorkflowScheduleSource, error) {
			return workflow.MakeTemporalWorkflowScheduleSource(ctx, env)
		}
	}

	if makers.activityFanoutActivityAEndpointSinkMaker == nil {
		makers.activityFanoutActivityAEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityAEndpointSink, error) {
			return activity.MakeFanoutActivityAEndpointSink(ctx, env)
		}
	}
	if makers.activityFanoutActivityBEndpointSinkMaker == nil {
		makers.activityFanoutActivityBEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityBEndpointSink, error) {
			return activity.MakeFanoutActivityBEndpointSink(ctx, env)
		}
	}
	if makers.activityFanoutActivityCEndpointSinkMaker == nil {
		makers.activityFanoutActivityCEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.FanoutActivityCEndpointSink, error) {
			return activity.MakeFanoutActivityCEndpointSink(ctx, env)
		}
	}
	if makers.activitySequentialActivityAEndpointSinkMaker == nil {
		makers.activitySequentialActivityAEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityAEndpointSink, error) {
			return activity.MakeSequentialActivityAEndpointSink(ctx, env)
		}
	}
	if makers.activitySequentialActivityBEndpointSinkMaker == nil {
		makers.activitySequentialActivityBEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.SequentialActivityBEndpointSink, error) {
			return activity.MakeSequentialActivityBEndpointSink(ctx, env)
		}
	}
	if makers.activityActivityJobEndpointSinkMaker == nil {
		makers.activityActivityJobEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*activity.ActivityJobEndpointSink, error) {
			return activity.MakeActivityJobEndpointSink(ctx, env)
		}
	}
	if makers.workflowFanoutWorkflowJobEndpointSinkMaker == nil {
		makers.workflowFanoutWorkflowJobEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.FanoutWorkflowJobEndpointSink, error) {
			return workflow.MakeFanoutWorkflowJobEndpointSink(ctx, env)
		}
	}
	if makers.workflowWorkflowJobEndpointSinkMaker == nil {
		makers.workflowWorkflowJobEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*workflow.WorkflowJobEndpointSink, error) {
			return workflow.MakeWorkflowJobEndpointSink(ctx, env)
		}
	}

	return nil
}
