// Code generated by servicegen. DO NOT EDIT.
package app

import (
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"reflect"
)

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	}
	return nil, nil
}
