// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"

	"github.com/gorundebug/rustexample-automationservice/internal/config"
	"github.com/gorundebug/rustexample-automationservice/internal/functions"
	datasink "github.com/gorundebug/servicelib/datasink"
	datasource "github.com/gorundebug/servicelib/datasource"
	datasourcetemporal "github.com/gorundebug/servicelib/datasource/temporal"
)

type serviceMakers struct {
	//stream function makers
	activityPauseMaker            func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ActivityPause, error)
	processActivityJobMaker       func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessActivityJob, error)
	workflowPauseMaker            func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.WorkflowPause, error)
	processWorkflowJobMaker       func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessWorkflowJob, error)
	observeActivityResultMaker    func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveActivityResult, error)
	observeWorkflowResultMaker    func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveWorkflowResult, error)
	scheduledActivityPauseMaker   func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledActivityPause, error)
	processScheduledActivityMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledActivity, error)
	scheduledWorkflowPauseMaker   func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledWorkflowPause, error)
	processScheduledWorkflowMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledWorkflow, error)
	//data source function makers
	localScheduleMaker            func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*functions.LocalSchedule, error)
	temporalActivityScheduleMaker func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalActivitySchedule, error)
	temporalWorkflowScheduleMaker func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalWorkflowSchedule, error)
	//data sink function makers
}

type serviceFunctions struct {
	//stream functions
	activityPause            *functions.ActivityPause
	processActivityJob       *functions.ProcessActivityJob
	workflowPause            *functions.WorkflowPause
	processWorkflowJob       *functions.ProcessWorkflowJob
	observeActivityResult    *functions.ObserveActivityResult
	observeWorkflowResult    *functions.ObserveWorkflowResult
	scheduledActivityPause   *functions.ScheduledActivityPause
	processScheduledActivity *functions.ProcessScheduledActivity
	scheduledWorkflowPause   *functions.ScheduledWorkflowPause
	processScheduledWorkflow *functions.ProcessScheduledWorkflow
	//data source functions
	localSchedule            *functions.LocalSchedule
	temporalActivitySchedule *functions.TemporalActivitySchedule
	temporalWorkflowSchedule *functions.TemporalWorkflowSchedule
	//data sink functions
}

type serviceStreams struct {
	//streams
	consumeActivityJob       runtime.TypedInputStream[string, string, error]
	activityPause            runtime.TypedConsumedStream[string]
	processActivityJob       runtime.TypedTransformConsumedStream[string, string]
	consumeWorkflowJob       runtime.TypedInputStream[string, string, error]
	workflowPause            runtime.TypedConsumedStream[string]
	processWorkflowJob       runtime.TypedTransformConsumedStream[string, string]
	localSchedule            runtime.TypedInputStream[string, any, error]
	splitOnDemandJobs        runtime.TypedSplitStream[string]
	submitActivityJob        runtime.TypedSinkStreamWithResult[string, string, error]
	observeActivityResult    runtime.TypedTransformConsumedStream[string, string]
	submitWorkflowJob        runtime.TypedSinkStreamWithResult[string, string, error]
	observeWorkflowResult    runtime.TypedTransformConsumedStream[string, string]
	temporalActivitySchedule runtime.TypedInputStream[string, string, error]
	scheduledActivityPause   runtime.TypedConsumedStream[string]
	processScheduledActivity runtime.TypedTransformConsumedStream[string, string]
	temporalWorkflowSchedule runtime.TypedInputStream[string, string, error]
	scheduledWorkflowPause   runtime.TypedConsumedStream[string]
	processScheduledWorkflow runtime.TypedTransformConsumedStream[string, string]
}

type serviceHandlers struct {
	//data source handlers
}

type serviceDataConnectors struct {
	//data sources
	activityJob              runtime.Consumer[string]
	workflowJob              runtime.Consumer[string]
	localSchedule            runtime.Consumer[string]
	temporalActivitySchedule runtime.Consumer[string]
	temporalWorkflowSchedule runtime.Consumer[string]
	//data sinks
	submitActivityJobActivityJob runtime.Consumer[string]
	submitWorkflowJobWorkflowJob runtime.Consumer[string]
}

type Service struct {
	runtime.ServiceApp
	makers          serviceMakers
	functions       serviceFunctions
	streams         serviceStreams
	handlers        serviceHandlers
	dataConnectors  serviceDataConnectors
	httpServer      *http.Server
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux         *http.ServeMux
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone  chan struct{}
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	if s.makers.activityPauseMaker == nil {
		s.makers.activityPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ActivityPause, error) {
			return functions.MakeActivityPause(ctx, env, cfg)
		}
	}
	if s.makers.processActivityJobMaker == nil {
		s.makers.processActivityJobMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessActivityJob, error) {
			return functions.MakeProcessActivityJob(ctx, env, cfg)
		}
	}
	if s.makers.workflowPauseMaker == nil {
		s.makers.workflowPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.WorkflowPause, error) {
			return functions.MakeWorkflowPause(ctx, env, cfg)
		}
	}
	if s.makers.processWorkflowJobMaker == nil {
		s.makers.processWorkflowJobMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessWorkflowJob, error) {
			return functions.MakeProcessWorkflowJob(ctx, env, cfg)
		}
	}
	if s.makers.observeActivityResultMaker == nil {
		s.makers.observeActivityResultMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveActivityResult, error) {
			return functions.MakeObserveActivityResult(ctx, env, cfg)
		}
	}
	if s.makers.observeWorkflowResultMaker == nil {
		s.makers.observeWorkflowResultMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveWorkflowResult, error) {
			return functions.MakeObserveWorkflowResult(ctx, env, cfg)
		}
	}
	if s.makers.scheduledActivityPauseMaker == nil {
		s.makers.scheduledActivityPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledActivityPause, error) {
			return functions.MakeScheduledActivityPause(ctx, env, cfg)
		}
	}
	if s.makers.processScheduledActivityMaker == nil {
		s.makers.processScheduledActivityMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledActivity, error) {
			return functions.MakeProcessScheduledActivity(ctx, env, cfg)
		}
	}
	if s.makers.scheduledWorkflowPauseMaker == nil {
		s.makers.scheduledWorkflowPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledWorkflowPause, error) {
			return functions.MakeScheduledWorkflowPause(ctx, env, cfg)
		}
	}
	if s.makers.processScheduledWorkflowMaker == nil {
		s.makers.processScheduledWorkflowMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledWorkflow, error) {
			return functions.MakeProcessScheduledWorkflow(ctx, env, cfg)
		}
	}
	if s.makers.localScheduleMaker == nil {
		s.makers.localScheduleMaker = func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*functions.LocalSchedule, error) {
			return functions.MakeLocalSchedule(ctx, env, cfg)
		}
	}
	if s.makers.temporalActivityScheduleMaker == nil {
		s.makers.temporalActivityScheduleMaker = func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalActivitySchedule, error) {
			return functions.MakeTemporalActivitySchedule(ctx, env, cfg)
		}
	}
	if s.makers.temporalWorkflowScheduleMaker == nil {
		s.makers.temporalWorkflowScheduleMaker = func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalWorkflowSchedule, error) {
			return functions.MakeTemporalWorkflowSchedule(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error
	if _, err = datasourcetemporal.MakeConnector(cfg.DataConnectors.Temporal.ID, s); err != nil {
		return fmt.Errorf("init Temporal connector 'Temporal' failed: %w", err)
	}

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}

	if err := s.initFunctions(ctx, cfg); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context) error {
	cfg := s.Config()
	var err error
	if s.streams.consumeActivityJob, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeActivityJob, s); err != nil {
		return err
	}
	if s.streams.activityPause, err = transformation.Delay[string](&cfg.Streams.ActivityPause, s.streams.consumeActivityJob, s.functions.activityPause); err != nil {
		return err
	}
	if s.streams.processActivityJob, err = transformation.Map[string, string](&cfg.Streams.ProcessActivityJob, s.streams.activityPause, s.functions.processActivityJob); err != nil {
		return err
	}
	if s.streams.consumeWorkflowJob, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeWorkflowJob, s); err != nil {
		return err
	}
	if s.streams.workflowPause, err = transformation.Delay[string](&cfg.Streams.WorkflowPause, s.streams.consumeWorkflowJob, s.functions.workflowPause); err != nil {
		return err
	}
	if s.streams.processWorkflowJob, err = transformation.Map[string, string](&cfg.Streams.ProcessWorkflowJob, s.streams.workflowPause, s.functions.processWorkflowJob); err != nil {
		return err
	}
	if s.streams.localSchedule, err = transformation.Input[string, any, error](&cfg.Streams.LocalSchedule, s); err != nil {
		return err
	}
	if s.streams.splitOnDemandJobs, err = transformation.Split[string](&cfg.Streams.SplitOnDemandJobs, s.streams.localSchedule); err != nil {
		return err
	}
	if s.streams.submitActivityJob, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.SubmitActivityJob, s.streams.splitOnDemandJobs.AddStream()); err != nil {
		return err
	}
	if s.streams.observeActivityResult, err = transformation.Map[string, string](&cfg.Streams.ObserveActivityResult, s.streams.submitActivityJob, s.functions.observeActivityResult); err != nil {
		return err
	}
	if s.streams.submitWorkflowJob, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.SubmitWorkflowJob, s.streams.splitOnDemandJobs.AddStream()); err != nil {
		return err
	}
	if s.streams.observeWorkflowResult, err = transformation.Map[string, string](&cfg.Streams.ObserveWorkflowResult, s.streams.submitWorkflowJob, s.functions.observeWorkflowResult); err != nil {
		return err
	}
	if s.streams.temporalActivitySchedule, err = transformation.Input[string, string, error](&cfg.Streams.TemporalActivitySchedule, s); err != nil {
		return err
	}
	if s.streams.scheduledActivityPause, err = transformation.Delay[string](&cfg.Streams.ScheduledActivityPause, s.streams.temporalActivitySchedule, s.functions.scheduledActivityPause); err != nil {
		return err
	}
	if s.streams.processScheduledActivity, err = transformation.Map[string, string](&cfg.Streams.ProcessScheduledActivity, s.streams.scheduledActivityPause, s.functions.processScheduledActivity); err != nil {
		return err
	}
	if s.streams.temporalWorkflowSchedule, err = transformation.Input[string, string, error](&cfg.Streams.TemporalWorkflowSchedule, s); err != nil {
		return err
	}
	if s.streams.scheduledWorkflowPause, err = transformation.Delay[string](&cfg.Streams.ScheduledWorkflowPause, s.streams.temporalWorkflowSchedule, s.functions.scheduledWorkflowPause); err != nil {
		return err
	}
	if s.streams.processScheduledWorkflow, err = transformation.Map[string, string](&cfg.Streams.ProcessScheduledWorkflow, s.streams.scheduledWorkflowPause, s.functions.processScheduledWorkflow); err != nil {
		return err
	}
	if err = s.streams.consumeActivityJob.SetSource(s.streams.processActivityJob); err != nil {
		return err
	}
	if err = s.streams.consumeWorkflowJob.SetSource(s.streams.processWorkflowJob); err != nil {
		return err
	}
	if err = s.streams.temporalActivitySchedule.SetSource(s.streams.processScheduledActivity); err != nil {
		return err
	}
	if err = s.streams.temporalWorkflowSchedule.SetSource(s.streams.processScheduledWorkflow); err != nil {
		return err
	}
	if s.dataConnectors.activityJob, err = datasource.TemporalEndpointConsumer(s.streams.consumeActivityJob); err != nil {
		return err
	}
	if s.dataConnectors.workflowJob, err = datasource.TemporalEndpointConsumer(s.streams.consumeWorkflowJob); err != nil {
		return err
	}
	if s.dataConnectors.localSchedule, err = functions.MakeEndpointConsumerLocalSchedule(s.streams.localSchedule, s.functions.localSchedule); err != nil {
		return err
	}
	if s.dataConnectors.temporalActivitySchedule, err = functions.MakeEndpointConsumerTemporalActivitySchedule(s.streams.temporalActivitySchedule, s.functions.temporalActivitySchedule); err != nil {
		return err
	}
	if s.dataConnectors.temporalWorkflowSchedule, err = functions.MakeEndpointConsumerTemporalWorkflowSchedule(s.streams.temporalWorkflowSchedule, s.functions.temporalWorkflowSchedule); err != nil {
		return err
	}
	if s.dataConnectors.submitActivityJobActivityJob, err = datasink.TemporalEndpointConsumerWithResult(s.streams.submitActivityJob); err != nil {
		return err
	}
	if s.dataConnectors.submitWorkflowJobWorkflowJob, err = datasink.TemporalEndpointConsumerWithResult(s.streams.submitWorkflowJob); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.activityPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.activityPause, err = s.makers.activityPauseMaker(egCtx, &cfg.Streams.ActivityPause, s)
			return err
		})
	}
	if s.makers.processActivityJobMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processActivityJob, err = s.makers.processActivityJobMaker(egCtx, &cfg.Streams.ProcessActivityJob, s)
			return err
		})
	}
	if s.makers.workflowPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.workflowPause, err = s.makers.workflowPauseMaker(egCtx, &cfg.Streams.WorkflowPause, s)
			return err
		})
	}
	if s.makers.processWorkflowJobMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processWorkflowJob, err = s.makers.processWorkflowJobMaker(egCtx, &cfg.Streams.ProcessWorkflowJob, s)
			return err
		})
	}
	if s.makers.observeActivityResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeActivityResult, err = s.makers.observeActivityResultMaker(egCtx, &cfg.Streams.ObserveActivityResult, s)
			return err
		})
	}
	if s.makers.observeWorkflowResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeWorkflowResult, err = s.makers.observeWorkflowResultMaker(egCtx, &cfg.Streams.ObserveWorkflowResult, s)
			return err
		})
	}
	if s.makers.scheduledActivityPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.scheduledActivityPause, err = s.makers.scheduledActivityPauseMaker(egCtx, &cfg.Streams.ScheduledActivityPause, s)
			return err
		})
	}
	if s.makers.processScheduledActivityMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processScheduledActivity, err = s.makers.processScheduledActivityMaker(egCtx, &cfg.Streams.ProcessScheduledActivity, s)
			return err
		})
	}
	if s.makers.scheduledWorkflowPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.scheduledWorkflowPause, err = s.makers.scheduledWorkflowPauseMaker(egCtx, &cfg.Streams.ScheduledWorkflowPause, s)
			return err
		})
	}
	if s.makers.processScheduledWorkflowMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processScheduledWorkflow, err = s.makers.processScheduledWorkflowMaker(egCtx, &cfg.Streams.ProcessScheduledWorkflow, s)
			return err
		})
	}
	if s.makers.localScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.localSchedule, err = s.makers.localScheduleMaker(egCtx, &cfg.Endpoints.LocalSchedule, s)
			return err
		})
	}
	if s.makers.temporalActivityScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.temporalActivitySchedule, err = s.makers.temporalActivityScheduleMaker(egCtx, &cfg.Endpoints.TemporalActivitySchedule, s)
			return err
		})
	}
	if s.makers.temporalWorkflowScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.temporalWorkflowSchedule, err = s.makers.temporalWorkflowScheduleMaker(egCtx, &cfg.Endpoints.TemporalWorkflowSchedule, s)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}

func (s *Service) ServiceInit() error {
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()
	wg := sync.WaitGroup{}
	done := make(chan struct{})
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.ServiceApp.Stop(timeoutCtx)
	}()

	var httpStopDone chan struct{}
	if s.httpServer != nil {
		httpStopDone = make(chan struct{})
		wg.Add(1)
		go func() {
			defer wg.Done()
			defer close(httpStopDone)
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.stop(timeoutCtx)
	}()
	go func() {
		wg.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-timeoutCtx.Done():
		if httpStopDone != nil {
			select {
			case <-httpStopDone:
			default:
				s.Log().Warn(timeoutCtx, "HTTP server stop timed out", log.Err(timeoutCtx.Err()))
			}
		}
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Automation Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
