// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"

	"github.com/gorundebug/rustexample-automationservice/internal/config"
	"github.com/gorundebug/rustexample-automationservice/internal/functions"
	datasink "github.com/gorundebug/servicelib/datasink"
	datasource "github.com/gorundebug/servicelib/datasource"
	datasourcetemporal "github.com/gorundebug/servicelib/datasource/temporal"
)

type serviceMakers struct {
	//stream function makers
	activityPauseMaker              func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ActivityPause, error)
	processActivityJobMaker         func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessActivityJob, error)
	processFanoutActivityAMaker     func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityA, error)
	processFanoutActivityBMaker     func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityB, error)
	processFanoutActivityCMaker     func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityC, error)
	observeFanoutActivityBMaker     func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveFanoutActivityB, error)
	observeFanoutActivityCMaker     func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveFanoutActivityC, error)
	processSequentialActivityAMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessSequentialActivityA, error)
	processSequentialActivityBMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessSequentialActivityB, error)
	workflowPauseMaker              func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.WorkflowPause, error)
	processWorkflowJobMaker         func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessWorkflowJob, error)
	observeActivityResultMaker      func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveActivityResult, error)
	observeWorkflowResultMaker      func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveWorkflowResult, error)
	scheduledActivityPauseMaker     func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledActivityPause, error)
	processScheduledActivityMaker   func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledActivity, error)
	scheduledWorkflowPauseMaker     func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledWorkflowPause, error)
	processScheduledWorkflowMaker   func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledWorkflow, error)
	//data source function makers
	localScheduleMaker            func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*functions.LocalSchedule, error)
	temporalActivityScheduleMaker func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalActivitySchedule, error)
	temporalWorkflowScheduleMaker func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalWorkflowSchedule, error)
	//data sink function makers
}

type serviceFunctions struct {
	//stream functions
	activityPause              *functions.ActivityPause
	processActivityJob         *functions.ProcessActivityJob
	processFanoutActivityA     *functions.ProcessFanoutActivityA
	processFanoutActivityB     *functions.ProcessFanoutActivityB
	processFanoutActivityC     *functions.ProcessFanoutActivityC
	observeFanoutActivityB     *functions.ObserveFanoutActivityB
	observeFanoutActivityC     *functions.ObserveFanoutActivityC
	processSequentialActivityA *functions.ProcessSequentialActivityA
	processSequentialActivityB *functions.ProcessSequentialActivityB
	workflowPause              *functions.WorkflowPause
	processWorkflowJob         *functions.ProcessWorkflowJob
	observeActivityResult      *functions.ObserveActivityResult
	observeWorkflowResult      *functions.ObserveWorkflowResult
	scheduledActivityPause     *functions.ScheduledActivityPause
	processScheduledActivity   *functions.ProcessScheduledActivity
	scheduledWorkflowPause     *functions.ScheduledWorkflowPause
	processScheduledWorkflow   *functions.ProcessScheduledWorkflow
	//data source functions
	localSchedule            *functions.LocalSchedule
	temporalActivitySchedule *functions.TemporalActivitySchedule
	temporalWorkflowSchedule *functions.TemporalWorkflowSchedule
	//data sink functions
}

type serviceStreams struct {
	//streams
	consumeActivityJob         runtime.TypedInputStream[string, string, error]
	activityPause              runtime.TypedConsumedStream[string]
	processActivityJob         runtime.TypedTransformConsumedStream[string, string]
	consumeFanOutActivityA     runtime.TypedInputStream[string, string, error]
	processFanOutActivityA     runtime.TypedTransformConsumedStream[string, string]
	consumeFanOutActivityB     runtime.TypedInputStream[string, string, error]
	processFanOutActivityB     runtime.TypedTransformConsumedStream[string, string]
	consumeFanOutActivityC     runtime.TypedInputStream[string, string, error]
	processFanOutActivityC     runtime.TypedTransformConsumedStream[string, string]
	consumeFanOutWorkflowJob   runtime.TypedInputStream[string, any, error]
	callFanOutActivityA        runtime.TypedSinkStreamWithResult[string, string, error]
	splitActivityAResult       runtime.TypedSplitStream[string]
	callFanOutActivityB        runtime.TypedSinkStreamWithResult[string, string, error]
	observeFanOutActivityB     runtime.TypedTransformConsumedStream[string, string]
	callFanOutActivityC        runtime.TypedSinkStreamWithResult[string, string, error]
	observeFanOutActivityC     runtime.TypedTransformConsumedStream[string, string]
	consumeSequentialActivityA runtime.TypedInputStream[string, string, error]
	processSequentialActivityA runtime.TypedTransformConsumedStream[string, string]
	consumeSequentialActivityB runtime.TypedInputStream[string, string, error]
	processSequentialActivityB runtime.TypedTransformConsumedStream[string, string]
	consumeWorkflowJob         runtime.TypedInputStream[string, string, error]
	workflowPause              runtime.TypedConsumedStream[string]
	callSequentialActivityA    runtime.TypedSinkStreamWithResult[string, string, error]
	callSequentialActivityB    runtime.TypedSinkStreamWithResult[string, string, error]
	processWorkflowJob         runtime.TypedTransformConsumedStream[string, string]
	localSchedule              runtime.TypedInputStream[string, any, error]
	splitOnDemandJobs          runtime.TypedSplitStream[string]
	submitActivityJob          runtime.TypedSinkStreamWithResult[string, string, error]
	observeActivityResult      runtime.TypedTransformConsumedStream[string, string]
	submitFanOutWorkflowJob    runtime.TypedSinkStream[string, error]
	submitWorkflowJob          runtime.TypedSinkStreamWithResult[string, string, error]
	observeWorkflowResult      runtime.TypedTransformConsumedStream[string, string]
	temporalActivitySchedule   runtime.TypedInputStream[string, string, error]
	scheduledActivityPause     runtime.TypedConsumedStream[string]
	processScheduledActivity   runtime.TypedTransformConsumedStream[string, string]
	temporalWorkflowSchedule   runtime.TypedInputStream[string, string, error]
	scheduledWorkflowPause     runtime.TypedConsumedStream[string]
	processScheduledWorkflow   runtime.TypedTransformConsumedStream[string, string]
}

type serviceHandlers struct {
	//data source handlers
}

type serviceDataConnectors struct {
	//data sources
	activityJob              runtime.Consumer[string]
	fanOutActivityA          runtime.Consumer[string]
	fanOutActivityB          runtime.Consumer[string]
	fanOutActivityC          runtime.Consumer[string]
	fanOutWorkflowJob        runtime.Consumer[string]
	sequentialActivityA      runtime.Consumer[string]
	sequentialActivityB      runtime.Consumer[string]
	workflowJob              runtime.Consumer[string]
	localSchedule            runtime.Consumer[string]
	temporalActivitySchedule runtime.Consumer[string]
	temporalWorkflowSchedule runtime.Consumer[string]
	//data sinks
	callFanOutActivityAFanOutActivityA         runtime.Consumer[string]
	callFanOutActivityBFanOutActivityB         runtime.Consumer[string]
	callFanOutActivityCFanOutActivityC         runtime.Consumer[string]
	callSequentialActivityASequentialActivityA runtime.Consumer[string]
	callSequentialActivityBSequentialActivityB runtime.Consumer[string]
	submitActivityJobActivityJob               runtime.Consumer[string]
	submitFanOutWorkflowJobFanOutWorkflowJob   runtime.Consumer[string]
	submitWorkflowJobWorkflowJob               runtime.Consumer[string]
}

type Service struct {
	runtime.ServiceApp
	makers          serviceMakers
	functions       serviceFunctions
	streams         serviceStreams
	handlers        serviceHandlers
	dataConnectors  serviceDataConnectors
	httpServer      *http.Server
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux         *http.ServeMux
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone  chan struct{}
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	if s.makers.activityPauseMaker == nil {
		s.makers.activityPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ActivityPause, error) {
			return functions.MakeActivityPause(ctx, env, cfg)
		}
	}
	if s.makers.processActivityJobMaker == nil {
		s.makers.processActivityJobMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessActivityJob, error) {
			return functions.MakeProcessActivityJob(ctx, env, cfg)
		}
	}
	if s.makers.processFanoutActivityAMaker == nil {
		s.makers.processFanoutActivityAMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityA, error) {
			return functions.MakeProcessFanoutActivityA(ctx, env, cfg)
		}
	}
	if s.makers.processFanoutActivityBMaker == nil {
		s.makers.processFanoutActivityBMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityB, error) {
			return functions.MakeProcessFanoutActivityB(ctx, env, cfg)
		}
	}
	if s.makers.processFanoutActivityCMaker == nil {
		s.makers.processFanoutActivityCMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessFanoutActivityC, error) {
			return functions.MakeProcessFanoutActivityC(ctx, env, cfg)
		}
	}
	if s.makers.observeFanoutActivityBMaker == nil {
		s.makers.observeFanoutActivityBMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveFanoutActivityB, error) {
			return functions.MakeObserveFanoutActivityB(ctx, env, cfg)
		}
	}
	if s.makers.observeFanoutActivityCMaker == nil {
		s.makers.observeFanoutActivityCMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveFanoutActivityC, error) {
			return functions.MakeObserveFanoutActivityC(ctx, env, cfg)
		}
	}
	if s.makers.processSequentialActivityAMaker == nil {
		s.makers.processSequentialActivityAMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessSequentialActivityA, error) {
			return functions.MakeProcessSequentialActivityA(ctx, env, cfg)
		}
	}
	if s.makers.processSequentialActivityBMaker == nil {
		s.makers.processSequentialActivityBMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessSequentialActivityB, error) {
			return functions.MakeProcessSequentialActivityB(ctx, env, cfg)
		}
	}
	if s.makers.workflowPauseMaker == nil {
		s.makers.workflowPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.WorkflowPause, error) {
			return functions.MakeWorkflowPause(ctx, env, cfg)
		}
	}
	if s.makers.processWorkflowJobMaker == nil {
		s.makers.processWorkflowJobMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessWorkflowJob, error) {
			return functions.MakeProcessWorkflowJob(ctx, env, cfg)
		}
	}
	if s.makers.observeActivityResultMaker == nil {
		s.makers.observeActivityResultMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveActivityResult, error) {
			return functions.MakeObserveActivityResult(ctx, env, cfg)
		}
	}
	if s.makers.observeWorkflowResultMaker == nil {
		s.makers.observeWorkflowResultMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ObserveWorkflowResult, error) {
			return functions.MakeObserveWorkflowResult(ctx, env, cfg)
		}
	}
	if s.makers.scheduledActivityPauseMaker == nil {
		s.makers.scheduledActivityPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledActivityPause, error) {
			return functions.MakeScheduledActivityPause(ctx, env, cfg)
		}
	}
	if s.makers.processScheduledActivityMaker == nil {
		s.makers.processScheduledActivityMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledActivity, error) {
			return functions.MakeProcessScheduledActivity(ctx, env, cfg)
		}
	}
	if s.makers.scheduledWorkflowPauseMaker == nil {
		s.makers.scheduledWorkflowPauseMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.ScheduledWorkflowPause, error) {
			return functions.MakeScheduledWorkflowPause(ctx, env, cfg)
		}
	}
	if s.makers.processScheduledWorkflowMaker == nil {
		s.makers.processScheduledWorkflowMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessScheduledWorkflow, error) {
			return functions.MakeProcessScheduledWorkflow(ctx, env, cfg)
		}
	}
	if s.makers.localScheduleMaker == nil {
		s.makers.localScheduleMaker = func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*functions.LocalSchedule, error) {
			return functions.MakeLocalSchedule(ctx, env, cfg)
		}
	}
	if s.makers.temporalActivityScheduleMaker == nil {
		s.makers.temporalActivityScheduleMaker = func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalActivitySchedule, error) {
			return functions.MakeTemporalActivitySchedule(ctx, env, cfg)
		}
	}
	if s.makers.temporalWorkflowScheduleMaker == nil {
		s.makers.temporalWorkflowScheduleMaker = func(ctx context.Context, cfg *runtimecfg.TemporalEndpointConfig, env environment.ServiceEnvironment) (*functions.TemporalWorkflowSchedule, error) {
			return functions.MakeTemporalWorkflowSchedule(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error
	if _, err = datasourcetemporal.MakeConnector(cfg.DataConnectors.Temporal.ID, s); err != nil {
		return fmt.Errorf("init Temporal connector 'Temporal' failed: %w", err)
	}

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}

	if err := s.initFunctions(ctx, cfg, s); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx, cfg, s); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	var err error
	if s.streams.consumeActivityJob, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeActivityJob, env); err != nil {
		return err
	}
	if s.streams.activityPause, err = transformation.Delay[string](&cfg.Streams.ActivityPause, s.streams.consumeActivityJob, s.functions.activityPause); err != nil {
		return err
	}
	if s.streams.processActivityJob, err = transformation.Map[string, string](&cfg.Streams.ProcessActivityJob, s.streams.activityPause, s.functions.processActivityJob); err != nil {
		return err
	}
	if s.streams.consumeFanOutActivityA, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeFanOutActivityA, env); err != nil {
		return err
	}
	if s.streams.processFanOutActivityA, err = transformation.Map[string, string](&cfg.Streams.ProcessFanOutActivityA, s.streams.consumeFanOutActivityA, s.functions.processFanoutActivityA); err != nil {
		return err
	}
	if s.streams.consumeFanOutActivityB, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeFanOutActivityB, env); err != nil {
		return err
	}
	if s.streams.processFanOutActivityB, err = transformation.Map[string, string](&cfg.Streams.ProcessFanOutActivityB, s.streams.consumeFanOutActivityB, s.functions.processFanoutActivityB); err != nil {
		return err
	}
	if s.streams.consumeFanOutActivityC, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeFanOutActivityC, env); err != nil {
		return err
	}
	if s.streams.processFanOutActivityC, err = transformation.Map[string, string](&cfg.Streams.ProcessFanOutActivityC, s.streams.consumeFanOutActivityC, s.functions.processFanoutActivityC); err != nil {
		return err
	}
	if s.streams.consumeFanOutWorkflowJob, err = transformation.Input[string, any, error](&cfg.Streams.ConsumeFanOutWorkflowJob, env); err != nil {
		return err
	}
	if s.streams.callFanOutActivityA, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.CallFanOutActivityA, s.streams.consumeFanOutWorkflowJob); err != nil {
		return err
	}
	if s.streams.splitActivityAResult, err = transformation.Split[string](&cfg.Streams.SplitActivityAResult, s.streams.callFanOutActivityA); err != nil {
		return err
	}
	if s.streams.callFanOutActivityB, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.CallFanOutActivityB, s.streams.splitActivityAResult.AddStream()); err != nil {
		return err
	}
	if s.streams.observeFanOutActivityB, err = transformation.Map[string, string](&cfg.Streams.ObserveFanOutActivityB, s.streams.callFanOutActivityB, s.functions.observeFanoutActivityB); err != nil {
		return err
	}
	if s.streams.callFanOutActivityC, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.CallFanOutActivityC, s.streams.splitActivityAResult.AddStream()); err != nil {
		return err
	}
	if s.streams.observeFanOutActivityC, err = transformation.Map[string, string](&cfg.Streams.ObserveFanOutActivityC, s.streams.callFanOutActivityC, s.functions.observeFanoutActivityC); err != nil {
		return err
	}
	if s.streams.consumeSequentialActivityA, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeSequentialActivityA, env); err != nil {
		return err
	}
	if s.streams.processSequentialActivityA, err = transformation.Map[string, string](&cfg.Streams.ProcessSequentialActivityA, s.streams.consumeSequentialActivityA, s.functions.processSequentialActivityA); err != nil {
		return err
	}
	if s.streams.consumeSequentialActivityB, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeSequentialActivityB, env); err != nil {
		return err
	}
	if s.streams.processSequentialActivityB, err = transformation.Map[string, string](&cfg.Streams.ProcessSequentialActivityB, s.streams.consumeSequentialActivityB, s.functions.processSequentialActivityB); err != nil {
		return err
	}
	if s.streams.consumeWorkflowJob, err = transformation.Input[string, string, error](&cfg.Streams.ConsumeWorkflowJob, env); err != nil {
		return err
	}
	if s.streams.workflowPause, err = transformation.Delay[string](&cfg.Streams.WorkflowPause, s.streams.consumeWorkflowJob, s.functions.workflowPause); err != nil {
		return err
	}
	if s.streams.callSequentialActivityA, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.CallSequentialActivityA, s.streams.workflowPause); err != nil {
		return err
	}
	if s.streams.callSequentialActivityB, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.CallSequentialActivityB, s.streams.callSequentialActivityA); err != nil {
		return err
	}
	if s.streams.processWorkflowJob, err = transformation.Map[string, string](&cfg.Streams.ProcessWorkflowJob, s.streams.callSequentialActivityB, s.functions.processWorkflowJob); err != nil {
		return err
	}
	if s.streams.localSchedule, err = transformation.Input[string, any, error](&cfg.Streams.LocalSchedule, env); err != nil {
		return err
	}
	if s.streams.splitOnDemandJobs, err = transformation.Split[string](&cfg.Streams.SplitOnDemandJobs, s.streams.localSchedule); err != nil {
		return err
	}
	if s.streams.submitActivityJob, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.SubmitActivityJob, s.streams.splitOnDemandJobs.AddStream()); err != nil {
		return err
	}
	if s.streams.observeActivityResult, err = transformation.Map[string, string](&cfg.Streams.ObserveActivityResult, s.streams.submitActivityJob, s.functions.observeActivityResult); err != nil {
		return err
	}
	if s.streams.submitFanOutWorkflowJob, err = transformation.Sink[string, error](&cfg.Streams.SubmitFanOutWorkflowJob, s.streams.splitOnDemandJobs.AddStream()); err != nil {
		return err
	}
	if s.streams.submitWorkflowJob, err = transformation.SinkWithResult[string, string, error](&cfg.Streams.SubmitWorkflowJob, s.streams.splitOnDemandJobs.AddStream()); err != nil {
		return err
	}
	if s.streams.observeWorkflowResult, err = transformation.Map[string, string](&cfg.Streams.ObserveWorkflowResult, s.streams.submitWorkflowJob, s.functions.observeWorkflowResult); err != nil {
		return err
	}
	if s.streams.temporalActivitySchedule, err = transformation.Input[string, string, error](&cfg.Streams.TemporalActivitySchedule, env); err != nil {
		return err
	}
	if s.streams.scheduledActivityPause, err = transformation.Delay[string](&cfg.Streams.ScheduledActivityPause, s.streams.temporalActivitySchedule, s.functions.scheduledActivityPause); err != nil {
		return err
	}
	if s.streams.processScheduledActivity, err = transformation.Map[string, string](&cfg.Streams.ProcessScheduledActivity, s.streams.scheduledActivityPause, s.functions.processScheduledActivity); err != nil {
		return err
	}
	if s.streams.temporalWorkflowSchedule, err = transformation.Input[string, string, error](&cfg.Streams.TemporalWorkflowSchedule, env); err != nil {
		return err
	}
	if s.streams.scheduledWorkflowPause, err = transformation.Delay[string](&cfg.Streams.ScheduledWorkflowPause, s.streams.temporalWorkflowSchedule, s.functions.scheduledWorkflowPause); err != nil {
		return err
	}
	if s.streams.processScheduledWorkflow, err = transformation.Map[string, string](&cfg.Streams.ProcessScheduledWorkflow, s.streams.scheduledWorkflowPause, s.functions.processScheduledWorkflow); err != nil {
		return err
	}
	if err = s.streams.consumeActivityJob.SetSource(s.streams.processActivityJob); err != nil {
		return err
	}
	if err = s.streams.consumeFanOutActivityA.SetSource(s.streams.processFanOutActivityA); err != nil {
		return err
	}
	if err = s.streams.consumeFanOutActivityB.SetSource(s.streams.processFanOutActivityB); err != nil {
		return err
	}
	if err = s.streams.consumeFanOutActivityC.SetSource(s.streams.processFanOutActivityC); err != nil {
		return err
	}
	if err = s.streams.consumeSequentialActivityA.SetSource(s.streams.processSequentialActivityA); err != nil {
		return err
	}
	if err = s.streams.consumeSequentialActivityB.SetSource(s.streams.processSequentialActivityB); err != nil {
		return err
	}
	if err = s.streams.consumeWorkflowJob.SetSource(s.streams.processWorkflowJob); err != nil {
		return err
	}
	if err = s.streams.temporalActivitySchedule.SetSource(s.streams.processScheduledActivity); err != nil {
		return err
	}
	if err = s.streams.temporalWorkflowSchedule.SetSource(s.streams.processScheduledWorkflow); err != nil {
		return err
	}
	if s.dataConnectors.activityJob, err = datasource.TemporalEndpointConsumer(s.streams.consumeActivityJob); err != nil {
		return err
	}
	if s.dataConnectors.fanOutActivityA, err = datasource.TemporalEndpointConsumer(s.streams.consumeFanOutActivityA); err != nil {
		return err
	}
	if s.dataConnectors.fanOutActivityB, err = datasource.TemporalEndpointConsumer(s.streams.consumeFanOutActivityB); err != nil {
		return err
	}
	if s.dataConnectors.fanOutActivityC, err = datasource.TemporalEndpointConsumer(s.streams.consumeFanOutActivityC); err != nil {
		return err
	}
	if s.dataConnectors.fanOutWorkflowJob, err = datasource.TemporalWorkflowEndpointConsumer(s.streams.consumeFanOutWorkflowJob, temporalWorkflowFanOutWorkflowJob); err != nil {
		return err
	}
	if s.dataConnectors.sequentialActivityA, err = datasource.TemporalEndpointConsumer(s.streams.consumeSequentialActivityA); err != nil {
		return err
	}
	if s.dataConnectors.sequentialActivityB, err = datasource.TemporalEndpointConsumer(s.streams.consumeSequentialActivityB); err != nil {
		return err
	}
	if s.dataConnectors.workflowJob, err = datasource.TemporalWorkflowEndpointConsumer(s.streams.consumeWorkflowJob, temporalWorkflowWorkflowJob); err != nil {
		return err
	}
	if s.dataConnectors.localSchedule, err = functions.MakeEndpointConsumerLocalSchedule(s.streams.localSchedule, s.functions.localSchedule); err != nil {
		return err
	}
	if s.dataConnectors.temporalActivitySchedule, err = functions.MakeEndpointConsumerTemporalActivitySchedule(s.streams.temporalActivitySchedule, s.functions.temporalActivitySchedule); err != nil {
		return err
	}
	if s.dataConnectors.temporalWorkflowSchedule, err = datasource.TemporalScheduleWorkflowEndpointConsumer(s.streams.temporalWorkflowSchedule, s.functions.temporalWorkflowSchedule, temporalWorkflowTemporalWorkflowSchedule); err != nil {
		return err
	}
	if s.dataConnectors.callFanOutActivityAFanOutActivityA, err = datasink.TemporalEndpointConsumerWithResult(s.streams.callFanOutActivityA); err != nil {
		return err
	}
	if s.dataConnectors.callFanOutActivityBFanOutActivityB, err = datasink.TemporalEndpointConsumerWithResult(s.streams.callFanOutActivityB); err != nil {
		return err
	}
	if s.dataConnectors.callFanOutActivityCFanOutActivityC, err = datasink.TemporalEndpointConsumerWithResult(s.streams.callFanOutActivityC); err != nil {
		return err
	}
	if s.dataConnectors.callSequentialActivityASequentialActivityA, err = datasink.TemporalEndpointConsumerWithResult(s.streams.callSequentialActivityA); err != nil {
		return err
	}
	if s.dataConnectors.callSequentialActivityBSequentialActivityB, err = datasink.TemporalEndpointConsumerWithResult(s.streams.callSequentialActivityB); err != nil {
		return err
	}
	if s.dataConnectors.submitActivityJobActivityJob, err = datasink.TemporalEndpointConsumerWithResult(s.streams.submitActivityJob); err != nil {
		return err
	}
	if s.dataConnectors.submitFanOutWorkflowJobFanOutWorkflowJob, err = datasink.TemporalEndpointConsumer(s.streams.submitFanOutWorkflowJob); err != nil {
		return err
	}
	if s.dataConnectors.submitWorkflowJobWorkflowJob, err = datasink.TemporalEndpointConsumerWithResult(s.streams.submitWorkflowJob); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.activityPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.activityPause, err = s.makers.activityPauseMaker(egCtx, &cfg.Streams.ActivityPause, env)
			return err
		})
	}
	if s.makers.processActivityJobMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processActivityJob, err = s.makers.processActivityJobMaker(egCtx, &cfg.Streams.ProcessActivityJob, env)
			return err
		})
	}
	if s.makers.processFanoutActivityAMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processFanoutActivityA, err = s.makers.processFanoutActivityAMaker(egCtx, &cfg.Streams.ProcessFanOutActivityA, env)
			return err
		})
	}
	if s.makers.processFanoutActivityBMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processFanoutActivityB, err = s.makers.processFanoutActivityBMaker(egCtx, &cfg.Streams.ProcessFanOutActivityB, env)
			return err
		})
	}
	if s.makers.processFanoutActivityCMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processFanoutActivityC, err = s.makers.processFanoutActivityCMaker(egCtx, &cfg.Streams.ProcessFanOutActivityC, env)
			return err
		})
	}
	if s.makers.observeFanoutActivityBMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeFanoutActivityB, err = s.makers.observeFanoutActivityBMaker(egCtx, &cfg.Streams.ObserveFanOutActivityB, env)
			return err
		})
	}
	if s.makers.observeFanoutActivityCMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeFanoutActivityC, err = s.makers.observeFanoutActivityCMaker(egCtx, &cfg.Streams.ObserveFanOutActivityC, env)
			return err
		})
	}
	if s.makers.processSequentialActivityAMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processSequentialActivityA, err = s.makers.processSequentialActivityAMaker(egCtx, &cfg.Streams.ProcessSequentialActivityA, env)
			return err
		})
	}
	if s.makers.processSequentialActivityBMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processSequentialActivityB, err = s.makers.processSequentialActivityBMaker(egCtx, &cfg.Streams.ProcessSequentialActivityB, env)
			return err
		})
	}
	if s.makers.workflowPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.workflowPause, err = s.makers.workflowPauseMaker(egCtx, &cfg.Streams.WorkflowPause, env)
			return err
		})
	}
	if s.makers.processWorkflowJobMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processWorkflowJob, err = s.makers.processWorkflowJobMaker(egCtx, &cfg.Streams.ProcessWorkflowJob, env)
			return err
		})
	}
	if s.makers.observeActivityResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeActivityResult, err = s.makers.observeActivityResultMaker(egCtx, &cfg.Streams.ObserveActivityResult, env)
			return err
		})
	}
	if s.makers.observeWorkflowResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.observeWorkflowResult, err = s.makers.observeWorkflowResultMaker(egCtx, &cfg.Streams.ObserveWorkflowResult, env)
			return err
		})
	}
	if s.makers.scheduledActivityPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.scheduledActivityPause, err = s.makers.scheduledActivityPauseMaker(egCtx, &cfg.Streams.ScheduledActivityPause, env)
			return err
		})
	}
	if s.makers.processScheduledActivityMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processScheduledActivity, err = s.makers.processScheduledActivityMaker(egCtx, &cfg.Streams.ProcessScheduledActivity, env)
			return err
		})
	}
	if s.makers.scheduledWorkflowPauseMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.scheduledWorkflowPause, err = s.makers.scheduledWorkflowPauseMaker(egCtx, &cfg.Streams.ScheduledWorkflowPause, env)
			return err
		})
	}
	if s.makers.processScheduledWorkflowMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processScheduledWorkflow, err = s.makers.processScheduledWorkflowMaker(egCtx, &cfg.Streams.ProcessScheduledWorkflow, env)
			return err
		})
	}
	if s.makers.localScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.localSchedule, err = s.makers.localScheduleMaker(egCtx, &cfg.Endpoints.LocalSchedule, env)
			return err
		})
	}
	if s.makers.temporalActivityScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.temporalActivitySchedule, err = s.makers.temporalActivityScheduleMaker(egCtx, &cfg.Endpoints.TemporalActivitySchedule, env)
			return err
		})
	}
	if s.makers.temporalWorkflowScheduleMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.temporalWorkflowSchedule, err = s.makers.temporalWorkflowScheduleMaker(egCtx, &cfg.Endpoints.TemporalWorkflowSchedule, env)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}

// buildWorkflowGraph constructs a fresh graph without creating process-owned
// servers, clients, exporters, watchers or OS-backed executors.
func (s *Service) buildWorkflowGraph(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init Workflow makers failed: %w", err)
	}
	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom Workflow makers failed: %w", err)
	}
	if err := s.initWorkflowFunctions(ctx, cfg, env); err != nil {
		return fmt.Errorf("init Workflow functions failed: %w", err)
	}
	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom Workflow functions failed: %w", err)
	}
	if err := s.initStreams(ctx, cfg, env); err != nil {
		return fmt.Errorf("init Workflow streams failed: %w", err)
	}
	return nil
}

// Workflow function makers run in a stable generated order. The ordinary
// service keeps initializer-group goroutines; a Temporal Workflow must not use
// process goroutines during replayable graph construction.
func (s *Service) initWorkflowFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	if s.makers.activityPauseMaker != nil {
		value, err := s.makers.activityPauseMaker(ctx, &cfg.Streams.ActivityPause, env)
		if err != nil {
			return err
		}
		s.functions.activityPause = value
	}
	if s.makers.processActivityJobMaker != nil {
		value, err := s.makers.processActivityJobMaker(ctx, &cfg.Streams.ProcessActivityJob, env)
		if err != nil {
			return err
		}
		s.functions.processActivityJob = value
	}
	if s.makers.processFanoutActivityAMaker != nil {
		value, err := s.makers.processFanoutActivityAMaker(ctx, &cfg.Streams.ProcessFanOutActivityA, env)
		if err != nil {
			return err
		}
		s.functions.processFanoutActivityA = value
	}
	if s.makers.processFanoutActivityBMaker != nil {
		value, err := s.makers.processFanoutActivityBMaker(ctx, &cfg.Streams.ProcessFanOutActivityB, env)
		if err != nil {
			return err
		}
		s.functions.processFanoutActivityB = value
	}
	if s.makers.processFanoutActivityCMaker != nil {
		value, err := s.makers.processFanoutActivityCMaker(ctx, &cfg.Streams.ProcessFanOutActivityC, env)
		if err != nil {
			return err
		}
		s.functions.processFanoutActivityC = value
	}
	if s.makers.observeFanoutActivityBMaker != nil {
		value, err := s.makers.observeFanoutActivityBMaker(ctx, &cfg.Streams.ObserveFanOutActivityB, env)
		if err != nil {
			return err
		}
		s.functions.observeFanoutActivityB = value
	}
	if s.makers.observeFanoutActivityCMaker != nil {
		value, err := s.makers.observeFanoutActivityCMaker(ctx, &cfg.Streams.ObserveFanOutActivityC, env)
		if err != nil {
			return err
		}
		s.functions.observeFanoutActivityC = value
	}
	if s.makers.processSequentialActivityAMaker != nil {
		value, err := s.makers.processSequentialActivityAMaker(ctx, &cfg.Streams.ProcessSequentialActivityA, env)
		if err != nil {
			return err
		}
		s.functions.processSequentialActivityA = value
	}
	if s.makers.processSequentialActivityBMaker != nil {
		value, err := s.makers.processSequentialActivityBMaker(ctx, &cfg.Streams.ProcessSequentialActivityB, env)
		if err != nil {
			return err
		}
		s.functions.processSequentialActivityB = value
	}
	if s.makers.workflowPauseMaker != nil {
		value, err := s.makers.workflowPauseMaker(ctx, &cfg.Streams.WorkflowPause, env)
		if err != nil {
			return err
		}
		s.functions.workflowPause = value
	}
	if s.makers.processWorkflowJobMaker != nil {
		value, err := s.makers.processWorkflowJobMaker(ctx, &cfg.Streams.ProcessWorkflowJob, env)
		if err != nil {
			return err
		}
		s.functions.processWorkflowJob = value
	}
	if s.makers.observeActivityResultMaker != nil {
		value, err := s.makers.observeActivityResultMaker(ctx, &cfg.Streams.ObserveActivityResult, env)
		if err != nil {
			return err
		}
		s.functions.observeActivityResult = value
	}
	if s.makers.observeWorkflowResultMaker != nil {
		value, err := s.makers.observeWorkflowResultMaker(ctx, &cfg.Streams.ObserveWorkflowResult, env)
		if err != nil {
			return err
		}
		s.functions.observeWorkflowResult = value
	}
	if s.makers.scheduledActivityPauseMaker != nil {
		value, err := s.makers.scheduledActivityPauseMaker(ctx, &cfg.Streams.ScheduledActivityPause, env)
		if err != nil {
			return err
		}
		s.functions.scheduledActivityPause = value
	}
	if s.makers.processScheduledActivityMaker != nil {
		value, err := s.makers.processScheduledActivityMaker(ctx, &cfg.Streams.ProcessScheduledActivity, env)
		if err != nil {
			return err
		}
		s.functions.processScheduledActivity = value
	}
	if s.makers.scheduledWorkflowPauseMaker != nil {
		value, err := s.makers.scheduledWorkflowPauseMaker(ctx, &cfg.Streams.ScheduledWorkflowPause, env)
		if err != nil {
			return err
		}
		s.functions.scheduledWorkflowPause = value
	}
	if s.makers.processScheduledWorkflowMaker != nil {
		value, err := s.makers.processScheduledWorkflowMaker(ctx, &cfg.Streams.ProcessScheduledWorkflow, env)
		if err != nil {
			return err
		}
		s.functions.processScheduledWorkflow = value
	}
	if s.makers.localScheduleMaker != nil {
		value, err := s.makers.localScheduleMaker(ctx, &cfg.Endpoints.LocalSchedule, env)
		if err != nil {
			return err
		}
		s.functions.localSchedule = value
	}
	if s.makers.temporalActivityScheduleMaker != nil {
		value, err := s.makers.temporalActivityScheduleMaker(ctx, &cfg.Endpoints.TemporalActivitySchedule, env)
		if err != nil {
			return err
		}
		s.functions.temporalActivitySchedule = value
	}
	if s.makers.temporalWorkflowScheduleMaker != nil {
		value, err := s.makers.temporalWorkflowScheduleMaker(ctx, &cfg.Endpoints.TemporalWorkflowSchedule, env)
		if err != nil {
			return err
		}
		s.functions.temporalWorkflowSchedule = value
	}
	return nil
}

func (s *Service) ServiceInit() error {
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()
	wg := sync.WaitGroup{}
	done := make(chan struct{})
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.ServiceApp.Stop(timeoutCtx)
	}()

	var httpStopDone chan struct{}
	if s.httpServer != nil {
		httpStopDone = make(chan struct{})
		wg.Add(1)
		go func() {
			defer wg.Done()
			defer close(httpStopDone)
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.stop(timeoutCtx)
	}()
	go func() {
		wg.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-timeoutCtx.Done():
		if httpStopDone != nil {
			select {
			case <-httpStopDone:
			default:
				s.Log().Warn(timeoutCtx, "HTTP server stop timed out", log.Err(timeoutCtx.Err()))
			}
		}
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Automation Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
