// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use std::time::Duration;

use serde::{Deserialize, Serialize};
use super::custom::CustomConfig;
use servicelib::api::{DataType, Environment, GrpcMethodType, HTTPMethodType, JoinStorageType, JoinType, KafkaSaslMechanism, KafkaSecurityProtocol, LogLevel, ProcessPattern, ScheduleMissedRunPolicy, ScheduleOverlapPolicy, TypeDefinitionFormat};
use servicelib::runtime::config::{
    CallSemantics, Config as ServiceConfigContract, CycleLinkStreamConfig,
    DelayStreamConfig, FilterStreamConfig, FlatMapIterableStreamConfig,
    FlatMapStreamConfig, InputStreamConfig, JoinStreamConfig, KeyByStreamConfig,
    LinkConfig, MapStreamConfig, MergeStreamConfig, MultiJoinStreamConfig,
    ModuleConfig, PoolConfig, ProcessStreamConfig, RuntimeDataConnectorConfig,
    RuntimeEndpointConfig, RuntimeStreamConfig, ServiceConfig, SinkStreamConfig,
    SplitStreamConfig, StreamConfig, WhenStreamConfig, CaseStreamConfig,
    TypeConfig, HttpDataConnectorConfig, GrpcDataConnectorConfig, KafkaDataConnectorConfig,
    CronDataConnectorConfig,
    CustomDataConnectorConfig, HttpEndpointConfig, GrpcEndpointConfig, KafkaEndpointConfig,
    CustomEndpointConfig, CronEndpointConfig,
};

pub const ANALYTICS_SERVICE_ID: i32 = 1;
pub const ANALYTICS_SCHEDULE_STREAM_ID: i32 = 1;
pub const CONSUME_ORDER_PROCESSED_STREAM_ID: i32 = 2;
pub const COUNT_ORDER_PROCESSED_STREAM_ID: i32 = 3;

pub const LOCAL_CRON_CONNECTOR_ID: i32 = 2;
pub const ORDER_EVENTS_CONNECTOR_ID: i32 = 3;

pub const ANALYTICS_SCHEDULE_ENDPOINT_ID: i32 = 2;
pub const ORDER_PROCESSED_ENDPOINT_ID: i32 = 4;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Streams {
    pub analytics_schedule: InputStreamConfig,
    pub consume_order_processed: InputStreamConfig,
    pub count_order_processed: ProcessStreamConfig,
}

impl Default for Streams {
    fn default() -> Self {
        Self {
            analytics_schedule: InputStreamConfig { stream: StreamConfig::new(ANALYTICS_SCHEDULE_STREAM_ID, "Analytics Schedule").with_graph(
    ANALYTICS_SERVICE_ID, 0, [],
    Some("AutomationJob"),
    None::<String>,
    -1600_f64, -205_f64,
).with_pipeline("analytics"), endpoint_id: ANALYTICS_SCHEDULE_ENDPOINT_ID },
            consume_order_processed: InputStreamConfig { stream: StreamConfig::new(CONSUME_ORDER_PROCESSED_STREAM_ID, "Consume Order Processed").with_graph(
    ANALYTICS_SERVICE_ID, COUNT_ORDER_PROCESSED_STREAM_ID, [],
    Some("OrderProcessed"),
    None::<String>,
    -1190_f64, -205_f64,
).with_pipeline("analytics"), endpoint_id: ORDER_PROCESSED_ENDPOINT_ID },
            count_order_processed: ProcessStreamConfig { stream: StreamConfig::new(COUNT_ORDER_PROCESSED_STREAM_ID, "Count Order Processed").with_graph(
    ANALYTICS_SERVICE_ID, CONSUME_ORDER_PROCESSED_STREAM_ID, [],
    Some("OrderProcessed"),
    None::<String>,
    -1390_f64, -19_f64,
).with_pipeline("analytics"), pattern: ProcessPattern::Undefined },
        }
    }
}

impl Streams {
    fn runtime_configs(&self) -> Vec<RuntimeStreamConfig> {
        vec![
            self.analytics_schedule.clone().into(),
            self.consume_order_processed.clone().into(),
            self.count_order_processed.clone().into(),
        ]
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Endpoints {
    pub analytics_schedule: CronEndpointConfig,
    pub order_processed: KafkaEndpointConfig,
}

impl Default for Endpoints {
    fn default() -> Self {
        Self {
            analytics_schedule: CronEndpointConfig {
                id: ANALYTICS_SCHEDULE_ENDPOINT_ID, name: "Analytics Schedule".to_owned(), id_data_connector: LOCAL_CRON_CONNECTOR_ID,
                tracing_enabled: false,
                enabled: true, schedule: "*/5 * * * *".to_owned(),
                timezone: "UTC".to_owned(),
                overlap_policy: ScheduleOverlapPolicy::Skip,
                missed_run_policy: ScheduleMissedRunPolicy::FireOnce,
            },
            order_processed: KafkaEndpointConfig {
                id: ORDER_PROCESSED_ENDPOINT_ID, name: "Order Processed".to_owned(), id_data_connector: ORDER_EVENTS_CONNECTOR_ID,
                tracing_enabled: false,
                enabled: true, create_topic: true, topic: "order-processed".to_owned(),
                partitions: 1, consumer_group: "analytics-service".to_owned(),
                replication_factor: 1,
            },
        }
    }
}

impl Endpoints {
    fn runtime_configs(&self) -> Vec<RuntimeEndpointConfig> {
        vec![
            self.analytics_schedule.clone().into(),
            self.order_processed.clone().into(),
        ]
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Config {
    pub analytics_schedule_enabled: bool,
    pub analytics_schedule_tracing_enabled: bool,
    pub request_timeout_ms: u64,
    pub environment: String,
    pub grpc_host: String,
    pub grpc_port: u16,
    pub http_host: String,
    pub http_port: u16,
    pub order_events_brokers: String,
    pub order_events_password: String,
    pub order_events_sasl_mechanism: String,
    pub order_events_security_protocol: String,
    pub order_events_username: String,
    pub order_processed_enabled: bool,
    pub streams: Streams,
    pub endpoints: Endpoints,
    #[serde(flatten)]
    pub custom: CustomConfig,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            analytics_schedule_enabled: true,
            analytics_schedule_tracing_enabled: false,
            request_timeout_ms: 0,
            environment: "".to_owned(),
            grpc_host: "0.0.0.0".to_owned(),
            grpc_port: 9203,
            http_host: "0.0.0.0".to_owned(),
            http_port: 9093,
            order_events_brokers: "redpanda:9092".to_owned(),
            order_events_password: "".to_owned(),
            order_events_sasl_mechanism: "SCRAM-SHA-512".to_owned(),
            order_events_security_protocol: "PLAINTEXT".to_owned(),
            order_events_username: "".to_owned(),
            order_processed_enabled: true,
            streams: Streams::default(),
            endpoints: Endpoints::default(),
            custom: CustomConfig::default(),
        }
    }
}

impl Config {
    pub fn service(&self) -> ServiceConfig {
        ServiceConfig {
            id: ANALYTICS_SERVICE_ID,
            name: "Analytics Service".to_owned(),
            http_host: self.http_host.clone(),
            http_port: self.http_port,
            grpc_host: self.grpc_host.clone(),
            grpc_port: self.grpc_port,
            color: "#05ABF7".to_owned(),
            programming_language: servicelib::api::ProgrammingLanguage::Rust,
            module_path: "github.com/gorundebug/rustexample-analyticsservice".to_owned(),
            default_call_semantics: CallSemantics::FunctionCall,
            metrics_handler: "metrics".to_owned(),
            status_handler: "status".to_owned(),
            startup_handler: "health/startup".to_owned(),
            readiness_handler: "health/ready".to_owned(),
            liveness_handler: "health/live".to_owned(),
            kubernetes_workload_type: servicelib::api::KubernetesWorkloadType::Deployment,
            default_grpc_timeout: 0,
            log_level: LogLevel::Undefined,
            environment: self.environment.clone(),
            shutdown_timeout: 30000,
            ..ServiceConfig::default()
        }
    }
}

impl ServiceConfigContract for Config {
    fn apply_environment(&mut self) -> Result<(), String> {
        apply_bool("ANALYTICS_SCHEDULE_ENABLED", &mut self.analytics_schedule_enabled)?;
        self.endpoints.analytics_schedule.enabled = self.analytics_schedule_enabled;
        apply_bool("ANALYTICS_SCHEDULE_TRACING_ENABLED", &mut self.analytics_schedule_tracing_enabled)?;
        self.endpoints.analytics_schedule.tracing_enabled = self.analytics_schedule_tracing_enabled;
        apply_u64("ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT", &mut self.request_timeout_ms)?;
        apply_string("ANALYTICS_SERVICE_ENVIRONMENT", &mut self.environment);
        apply_string("ANALYTICS_SERVICE_GRPC_HOST", &mut self.grpc_host);
        apply_port("ANALYTICS_SERVICE_GRPC_PORT", &mut self.grpc_port)?;
        apply_string("ANALYTICS_SERVICE_HTTP_HOST", &mut self.http_host);
        apply_port("ANALYTICS_SERVICE_HTTP_PORT", &mut self.http_port)?;
        apply_string("ORDER_EVENTS_BROKERS", &mut self.order_events_brokers);
        apply_string("ORDER_EVENTS_PASSWORD", &mut self.order_events_password);
        apply_string("ORDER_EVENTS_SASL_MECHANISM", &mut self.order_events_sasl_mechanism);
        apply_string("ORDER_EVENTS_SECURITY_PROTOCOL", &mut self.order_events_security_protocol);
        apply_string("ORDER_EVENTS_USERNAME", &mut self.order_events_username);
        apply_bool("ORDER_PROCESSED_ENABLED", &mut self.order_processed_enabled)?;
        self.endpoints.order_processed.enabled = self.order_processed_enabled;
        self.custom.apply_environment()
    }
    fn validate(&self) -> Result<(), String> {
        if self.http_port == 0 || self.grpc_port == 0 {
            return Err("httpPort and grpcPort must be positive".to_owned());
        }
        parse_environment(&self.environment)?;
        parse_kafka_security_protocol(&self.order_events_security_protocol)?;
        parse_kafka_sasl_mechanism(&self.order_events_sasl_mechanism)?;
        self.custom.validate()
    }
    fn services(&self) -> Vec<ServiceConfig> {
        vec![self.service()]
    }
    fn streams(&self) -> Vec<RuntimeStreamConfig> { self.streams.runtime_configs() }
    fn data_connectors(&self) -> Vec<RuntimeDataConnectorConfig> {
        vec![
            CronDataConnectorConfig {
                id: LOCAL_CRON_CONNECTOR_ID, name: "Local Cron".to_owned(),
            }.into(),
            KafkaDataConnectorConfig {
                id: ORDER_EVENTS_CONNECTOR_ID, name: "Order Events".to_owned(),
                brokers: self.order_events_brokers.clone(), version: "2.8.0".to_owned(),
                dial_timeout: 5000.0, use_partitioner: false, r#async: false,
                security_protocol: parse_kafka_security_protocol(&self.order_events_security_protocol).expect("Kafka security protocol was validated"),
                sasl_mechanism: parse_kafka_sasl_mechanism(&self.order_events_sasl_mechanism).expect("Kafka SASL mechanism was validated"),
                username: self.order_events_username.clone(),
                password: self.order_events_password.clone(),
            }.into(),
        ]
    }
    fn endpoints(&self) -> Vec<RuntimeEndpointConfig> {
        self.endpoints.runtime_configs()
    }
    fn pools(&self) -> Vec<PoolConfig> {
        vec![
        ]
    }
    fn links(&self) -> Vec<LinkConfig> {
        vec![
        ]
    }
    fn modules(&self) -> Vec<ModuleConfig> {
        vec![
            ModuleConfig { name: "inventory_service_api".to_owned(), path: "github.com/gorundebug/rustexample-inventory-service-api".to_owned(), properties: Default::default() },
            ModuleConfig { name: "model".to_owned(), path: "github.com/gorundebug/rustexample-model".to_owned(), properties: Default::default() },
            ModuleConfig { name: "order_service_api".to_owned(), path: "github.com/gorundebug/rustexample-order-service-api".to_owned(), properties: Default::default() },
        ]
    }
    fn types(&self) -> Vec<TypeConfig> {
        vec![
            TypeConfig {
                name: "AutomationJob".to_owned(), data_type: DataType::String,
                type_definition: "String".to_owned(), type_import: "example_model::types::automation_job".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "model".to_owned(),
                definition_format: TypeDefinitionFormat::Undefined, public_type: true,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
            TypeConfig {
                name: "OrderProcessed".to_owned(), data_type: DataType::Struct,
                type_definition: "OrderProcessed".to_owned(), type_import: "example_model::types::order_processed".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "model".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
        ]
    }
}

fn apply_string(name: &str, target: &mut String) {
    if let Ok(value) = std::env::var(name) {
        *target = value;
    }
}

fn parse_schedule_overlap_policy(value: &str) -> Result<ScheduleOverlapPolicy, String> {
    match value {
        "Allow" => Ok(ScheduleOverlapPolicy::Allow),
        "Skip" => Ok(ScheduleOverlapPolicy::Skip),
        _ => Err(format!("invalid schedule overlap policy: {value}")),
    }
}

fn parse_schedule_missed_run_policy(value: &str) -> Result<ScheduleMissedRunPolicy, String> {
    match value {
        "Skip" => Ok(ScheduleMissedRunPolicy::Skip),
        "FireOnce" => Ok(ScheduleMissedRunPolicy::FireOnce),
        _ => Err(format!("invalid schedule missed-run policy: {value}")),
    }
}

fn apply_port(name: &str, target: &mut u16) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_u64(name: &str, target: &mut u64) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_usize(name: &str, target: &mut usize) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_i32(name: &str, target: &mut i32) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_f64(name: &str, target: &mut f64) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_bool(name: &str, target: &mut bool) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn parse_environment(value: &str) -> Result<Environment, String> {
    match value {
        "" => Ok(Environment::Undefined),
        "local" => Ok(Environment::Local),
        "debug" => Ok(Environment::Debug),
        "staging" => Ok(Environment::Staging),
        "production" => Ok(Environment::Production),
        _ => Err(format!("invalid environment: {value}")),
    }
}

fn parse_kafka_security_protocol(value: &str) -> Result<KafkaSecurityProtocol, String> {
    match value {
        "PLAINTEXT" => Ok(KafkaSecurityProtocol::PLAINTEXT),
        "SASL_PLAINTEXT" => Ok(KafkaSecurityProtocol::SASLPLAINTEXT),
        "SASL_SSL" => Ok(KafkaSecurityProtocol::SASLSSL),
        _ => Err(format!("unknown Kafka security protocol {value:?}")),
    }
}

fn parse_kafka_sasl_mechanism(value: &str) -> Result<KafkaSaslMechanism, String> {
    match value {
        "PLAIN" => Ok(KafkaSaslMechanism::PLAIN),
        "SCRAM-SHA-256" => Ok(KafkaSaslMechanism::SCRAMSHA256),
        "SCRAM-SHA-512" => Ok(KafkaSaslMechanism::SCRAMSHA512),
        _ => Err(format!("unknown Kafka SASL mechanism {value:?}")),
    }
}