[package]
name = "order-service-api"
version = "0.2.61"
edition = "2024"
rust-version = "1.85"

[lib]
name = "order_service_api"

[features]
default = ["server"]
server = []
conversion = []


[dependencies]
serde = { version = "1", features = ["derive"] }
ammonia = "4"
async-trait = "0.1"
axum = { version = "0.8", features = ["multipart"] }
axum-extra = { version = "0.12", features = ["cookie", "query", "typed-header"] }
base64 = "0.22"
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
headers = "0.4"
http = "1"
lazy_static = "1"
regex = "1"
serde_html_form = "0.2"
serde_json = { version = "1", features = ["raw_value"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
uuid = { version = "1", features = ["serde"] }
validator = { version = "0.20", features = ["derive"] }