# Code generated by servicegen. DO NOT EDIT.
# Make prerequisites need backslash escaping; shell arguments need quotes instead.
make_empty :=
make_space := $(make_empty) $(make_empty)
make_escape_path = $(subst $(make_space),\$(make_space),$(1))
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(abspath ../tools)
BUF := $(TOOLS_DIR)/buf
PROTOC ?= $(or $(shell command -v protoc 2>/dev/null),$(TOOLS_DIR)/protoc)
DEPENDENCY_DOCKER_TARGETS :=
include dependency-proxy.generated.mk

.PHONY: all build test gen-proto fmt-proto

all: gen-proto

build: all ## [host] Compile every package in this module
	@go test -run '^$$' ./...

test: all ## [host] Run this module's tests
	@go test ./...

gen-proto:
	@set -e; find . -type f -name 'go.generated.proto.mk' | while IFS= read -r mkfile; do \
		dir=$$(dirname "$$mkfile"); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C "$$dir" -f "$$(basename "$$mkfile")" gen MODULE_DIR="$(MODULE_DIR)" PROTOC="$(PROTOC)"; \
	done

fmt-proto:
	@set -e; find . -type f -name '*.proto' | while IFS= read -r protofile; do \
		"$(BUF)" format -w "$$protofile"; \
	done