// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::makers_generated::ServiceMakers;

pub struct ServiceDataConnectors {
    pub order_service_api_data_source: Arc<AxumDataSource>,
    pub order_events_data_sink: Arc<RdkafkaKafkaDataSink>,
    pub inventory_data_sink: Arc<TonicDataSink>,
}

pub struct ServiceInfrastructure {
    pub order_service_api_data_source: Arc<AxumDataSource>,
    pub order_events_data_sink: Arc<RdkafkaKafkaDataSink>,
    pub inventory_data_sink: Arc<TonicDataSink>,
}

fn connector_config(
    environment: &RuntimeEnvironment,
    connector_id: i32,
) -> RuntimeResult<Arc<RuntimeDataConnectorConfig>> {
    environment.runtime_config().data_connector_by_id(connector_id).ok_or_else(||
        RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not configured"
        ))
    )
}
pub(super) fn http_connector_config(environment: &RuntimeEnvironment, connector_id: i32) -> RuntimeResult<HttpDataConnectorConfig> {
    match connector_config(environment, connector_id)?.as_ref() {
        RuntimeDataConnectorConfig::Http(config) => Ok(config.clone()),
        _ => Err(RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not HTTP"
        ))),
    }
}
fn grpc_connector_config(environment: &RuntimeEnvironment, connector_id: i32) -> RuntimeResult<GrpcDataConnectorConfig> {
    match connector_config(environment, connector_id)?.as_ref() {
        RuntimeDataConnectorConfig::Grpc(config) => Ok(config.clone()),
        _ => Err(RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not gRPC"
        ))),
    }
}
fn kafka_connector_config(environment: &RuntimeEnvironment, connector_id: i32) -> RuntimeResult<KafkaDataConnectorConfig> {
    match connector_config(environment, connector_id)?.as_ref() {
        RuntimeDataConnectorConfig::Kafka(config) => Ok(config.clone()),
        _ => Err(RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not Kafka"
        ))),
    }
}
macro_rules! infrastructure_maker_future {
    ($maker:expr, $context:expr, $environment:expr, $config:expr, $group:expr, $errors:expr) => ({
        let maker = $maker.clone();
        let context = $context.clone();
        let environment = $environment.clone();
        let config = $config;
        let group = $group.clone();
        let errors = $errors.clone();
        async move {
            match (maker)(context, environment, &config).await {
                Ok(value) => Some(value),
                Err(error) => {
                    group.cancel();
                    errors.send(error).expect("infrastructure maker error receiver was dropped");
                    None
                }
            }
        }
    });
}

impl ServiceInfrastructure {
pub async fn init_infrastructure(
    context: MessageContext,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
) -> RuntimeResult<ServiceInfrastructure> {
    let maker_group_context = context.child();
    let (maker_error_sender, maker_error_receiver) = mpsc::channel::<RuntimeError>();
    let order_service_api_data_source_future = infrastructure_maker_future!(
        makers.order_service_api_data_source, maker_group_context, environment,
        http_connector_config(&environment, crate::internal::config::ORDER_SERVICE_API_CONNECTOR_ID)?, maker_group_context, maker_error_sender
    );
    let order_events_data_sink_future = infrastructure_maker_future!(
        makers.order_events_data_sink, maker_group_context, environment,
        kafka_connector_config(&environment, crate::internal::config::ORDER_EVENTS_CONNECTOR_ID)?, maker_group_context, maker_error_sender
    );
    let inventory_data_sink_future = infrastructure_maker_future!(
        makers.inventory_data_sink, maker_group_context, environment,
        grpc_connector_config(&environment, crate::internal::config::INVENTORY_SERVICE_API_CONNECTOR_ID)?, maker_group_context, maker_error_sender
    );
    let mut order_service_api_data_source = None;
    let mut order_events_data_sink = None;
    let mut inventory_data_sink = None;
    let maker_futures: Vec<Pin<Box<dyn Future<Output = ()> + Send + '_>>> = vec![
        Box::pin(async { order_service_api_data_source = order_service_api_data_source_future.await; }),
        Box::pin(async { order_events_data_sink = order_events_data_sink_future.await; }),
        Box::pin(async { inventory_data_sink = inventory_data_sink_future.await; }),
    ];
    futures_util::future::join_all(maker_futures).await;
    maker_group_context.cancel();
    drop(maker_error_sender);
    if let Ok(error) = maker_error_receiver.try_recv() {
        return Err(error);
    }
    Ok(ServiceInfrastructure {
        order_service_api_data_source: order_service_api_data_source.ok_or_else(|| RuntimeError::InvalidConfiguration("infrastructure maker order_service_api_data_source failed without an error".to_owned()))?,
        order_events_data_sink: order_events_data_sink.ok_or_else(|| RuntimeError::InvalidConfiguration("infrastructure maker order_events_data_sink failed without an error".to_owned()))?,
        inventory_data_sink: inventory_data_sink.ok_or_else(|| RuntimeError::InvalidConfiguration("infrastructure maker inventory_data_sink failed without an error".to_owned()))?,
    })
}


}

impl ServiceDataConnectors {
    pub fn register(&self, app: &mut ServiceApp) -> RuntimeResult<()> {
        let _ = &app;
        app.add_http_router(self.order_service_api_data_source.router())?;
        app.register_data_source(Arc::clone(&self.order_service_api_data_source))?;
        app.register_data_sink(Arc::clone(&self.order_events_data_sink))?;
        app.register_data_sink(Arc::clone(&self.inventory_data_sink))?;
        Ok(())
    }

    pub fn reload(&self, config: &Config) -> Result<(), String> {
        let _ = config;
        self.inventory_data_sink.reload_address(config.inventory_address.clone())
            .map_err(|error| error.to_string())?;
        Ok(())
    }
}