// Code generated by servicegen. DO NOT EDIT.

use super::*;

#[derive(Clone)]
pub struct OrderPipelineMakers {
    pub map_order_item_result_to_order_state: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<MapOrderItemResultToOrderState>> + Send + 'a>> + Send + Sync>,
    pub map_to_order_processed: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<MapToOrderProcessed>> + Send + 'a>> + Send + Sync>,
    pub map_to_order_state: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<MapToOrderState>> + Send + 'a>> + Send + Sync>,
    pub order_processed_endpoint_sink: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a KafkaEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<OrderProcessedEndpointSink>> + Send + 'a>> + Send + Sync>,
    pub process_order_item_sink: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a GrpcEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ProcessOrderItemSink>> + Send + 'a>> + Send + Sync>,
    pub process_order_items: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a FlatMapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ProcessOrderItems>> + Send + 'a>> + Send + Sync>,
    pub process_order_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a HttpEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ProcessOrderSource>> + Send + 'a>> + Send + Sync>,
    pub soft_deadline: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a DelayStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<SoftDeadline>> + Send + 'a>> + Send + Sync>,
}

macro_rules! init_order_pipeline_streams {
    ($config:ident, $environment:ident, $functions:ident) => {{
        init_order_process_order_stream!($config, $environment, $functions, process_order);
        init_order_split_pipeline_stream!($config, $environment, $functions, split_pipeline, process_order.stream(), [process_order_items_branch, soft_deadline_branch]);
        init_order_process_order_items_stream!($config, $environment, $functions, process_order_items, process_order_items_branch);
        init_order_process_order_item_stream!($config, $environment, $functions, process_order_item, process_order_items, process_order_item_error);
        init_order_map_order_item_result_to_order_state_stream!($config, $environment, $functions, map_order_item_result_to_order_state, process_order_item.stream().clone());
        init_order_soft_deadline_stream!($config, $environment, $functions, soft_deadline, soft_deadline_branch);
        init_order_map_to_order_state_stream!($config, $environment, $functions, map_to_order_state, soft_deadline);
        init_order_merge_results_stream!($config, $environment, $functions, merge_results, [map_to_order_state, map_order_item_result_to_order_state, process_order_item_error]);
        init_order_split_order_result_stream!($config, $environment, $functions, split_order_result, merge_results, [map_to_order_processed_branch, process_order_branch]);
        init_order_map_to_order_processed_stream!($config, $environment, $functions, map_to_order_processed, map_to_order_processed_branch);
        init_order_publish_order_processed_stream!($config, $environment, $functions, publish_order_processed, map_to_order_processed);
        process_order.set_source(&process_order_branch)?;
        Ok::<OrderPipelineStreams, RuntimeError>(OrderPipelineStreams {
            process_order: process_order,
            split_pipeline,
            process_order_items,
            process_order_item,
            process_order_item_error,
            map_order_item_result_to_order_state,
            soft_deadline,
            map_to_order_state,
            merge_results,
            split_order_result,
            map_to_order_processed,
            publish_order_processed,
        })
    }};
}

impl Default for OrderPipelineMakers {
    fn default() -> Self {
        Self {
            map_order_item_result_to_order_state: Arc::new(|context, environment, config| {
                Box::pin(async move { make_map_order_item_result_to_order_state(context, environment, config).await })
            }),
            map_to_order_processed: Arc::new(|context, environment, config| {
                Box::pin(async move { make_map_to_order_processed(context, environment, config).await })
            }),
            map_to_order_state: Arc::new(|context, environment, config| {
                Box::pin(async move { make_map_to_order_state(context, environment, config).await })
            }),
            order_processed_endpoint_sink: Arc::new(|context, environment, config| {
                Box::pin(async move { make_order_processed_endpoint_sink(context, environment, config).await })
            }),
            process_order_item_sink: Arc::new(|context, environment, config| {
                Box::pin(async move { make_process_order_item_sink(context, environment, config).await })
            }),
            process_order_items: Arc::new(|context, environment, config| {
                Box::pin(async move { make_process_order_items(context, environment, config).await })
            }),
            process_order_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_process_order_source(context, environment, config).await })
            }),
            soft_deadline: Arc::new(|context, environment, config| {
                Box::pin(async move { make_soft_deadline(context, environment, config).await })
            }),
        }
    }
}

pub struct OrderPipelineFunctions {
    pub map_order_item_result_to_order_state: MapOrderItemResultToOrderState,
    pub map_to_order_processed: MapToOrderProcessed,
    pub map_to_order_state: MapToOrderState,
    pub order_processed_endpoint_sink: OrderProcessedEndpointSink,
    pub process_order_item_sink: ProcessOrderItemSink,
    pub process_order_items: ProcessOrderItems,
    pub process_order_source: ProcessOrderSource,
    pub soft_deadline: SoftDeadline,
}

pub struct OrderPipelineStreams {
    pub process_order: Arc<InputStream<Order, OrderState, String>>,
    pub split_pipeline: [Stream<Order>; 2],
    pub process_order_items: Stream<OrderItem>,
    pub process_order_item: Arc<SinkStreamWithResult<OrderItem, OrderItemResult, OrderState>>,
    pub process_order_item_error: Stream<OrderState>,
    pub map_order_item_result_to_order_state: Stream<OrderState>,
    pub soft_deadline: Stream<Order>,
    pub map_to_order_state: Stream<OrderState>,
    pub merge_results: Stream<OrderState>,
    pub split_order_result: [Stream<OrderState>; 2],
    pub map_to_order_processed: Stream<OrderProcessed>,
    pub publish_order_processed: Arc<SinkStreamWithResult<OrderProcessed, String, String>>,
}
macro_rules! init_order_process_order_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<Order, OrderState, String>::new(&$config.streams.process_order, $environment.clone()));
    };
}
macro_rules! init_order_split_pipeline_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr, [$($branch:ident),*]) => {
        let $variable = $source.split(&$config.streams.split_pipeline)?;
        let [$($branch),*] = $variable.clone();
        $(let _ = &$branch;)*
    };
}
macro_rules! init_order_process_order_items_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.flat_map(&$config.streams.process_order_items, $functions.order.process_order_items)?;
    };
}
macro_rules! init_order_process_order_item_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr, $error:ident) => {
        let $variable = $source.sink_with_result::<OrderItemResult, OrderState>(&$config.streams.process_order_item)?;
        let $error = $variable.error_stream().clone();
    };
}
macro_rules! init_order_map_order_item_result_to_order_state_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.map_order_item_result_to_order_state, $functions.order.map_order_item_result_to_order_state)?;
    };
}
macro_rules! init_order_soft_deadline_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.delay(&$config.streams.soft_deadline, $functions.order.soft_deadline)?;
    };
}
macro_rules! init_order_map_to_order_state_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.map_to_order_state, $functions.order.map_to_order_state)?;
    };
}
macro_rules! init_order_merge_results_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, [$first:expr $(, $source:expr)*]) => {
        let $variable = $first.merge(&$config.streams.merge_results, &[$($source.clone()),*])?;
    };
}
macro_rules! init_order_split_order_result_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr, [$($branch:ident),*]) => {
        let $variable = $source.split(&$config.streams.split_order_result)?;
        let [$($branch),*] = $variable.clone();
        $(let _ = &$branch;)*
    };
}
macro_rules! init_order_map_to_order_processed_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.map_to_order_processed, $functions.order.map_to_order_processed)?;
    };
}
macro_rules! init_order_publish_order_processed_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.sink_with_result::<String, String>(&$config.streams.publish_order_processed)?;
    };
}