// Code generated by servicegen. DO NOT EDIT.
#![allow(unused_imports, unused_variables)]

use std::{any::TypeId, sync::Arc};
use servicelib::runtime::{
    environment::{RuntimeEnvironment, RuntimeResult},
    serde::{ArraySerde, MapSerde, Serializer},
};
use super::imports::*;

pub fn get_serde(value_type: TypeId, environment: &RuntimeEnvironment) -> RuntimeResult<Option<Serializer>> {
    if let Some(serde) = super::custom_serde::get_custom_serde(value_type, environment)? {
        return Ok(Some(serde));
    }
    if let Some(serde) = get_serde_part_0(value_type, environment)? {
        return Ok(Some(serde));
    }
    Ok(None)
}


#[inline(never)]
fn get_serde_part_0(value_type: TypeId, environment: &RuntimeEnvironment) -> RuntimeResult<Option<Serializer>> {
    if value_type == TypeId::of::<Order>() {
        let serde = crate::internal::serdes::OrderSerde::new();
        return Ok(Some(Serializer::new::<Order>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<OrderItem>() {
        let serde = example_model::serdes::OrderItemSerde::new();
        return Ok(Some(Serializer::new::<OrderItem>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<OrderItemResult>() {
        let serde = example_model::serdes::OrderItemResultSerde::new();
        return Ok(Some(Serializer::new::<OrderItemResult>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<OrderProcessed>() {
        let serde = example_model::serdes::OrderProcessedSerde::new();
        return Ok(Some(Serializer::new::<OrderProcessed>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<OrderState>() {
        let serde = crate::internal::serdes::OrderStateSerde::new();
        return Ok(Some(Serializer::new::<OrderState>(Arc::new(serde))));
    }
    Ok(None)
}