// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use std::sync::{Arc, OnceLock, Weak};

use servicelib::{
    MessageContext, Stream,
    operators::{InputStream, SinkStream, SinkStreamWithResult},
    runtime::{
        config::{ConfigLoader, DelayStreamConfig, FlatMapStreamConfig, GrpcEndpointConfig, HttpEndpointConfig, KafkaEndpointConfig, MapStreamConfig,  },
        environment::{RuntimeEnvironment, RuntimeResult},
        serviceapp::ServiceApp,
    },
};
use example_model::types::*;

use servicelib::datasink::grpc::{NoStreamingClientFunction, TonicDataSink, make_grpc_no_streaming_endpoint_consumer};
use inventory_service_api::{
    inventoryserviceapi::inventory_service_api_client::InventoryServiceApiClient,
    processorderitem::{ ProcessOrderItemRequest, ProcessOrderItemResponse },
};

use servicelib::{
    datasink::kafka::{RdkafkaKafkaDataSink, make_rdkafka_kafka_endpoint_consumer},
};



use servicelib::{
    datasource::http::{AxumDataSource, EndpointHandler as _},
    runtime::config::HttpDataConnectorConfig,
};


use crate::internal::{config::Config, functions::*, types::*};

pub struct ServiceStreams {
    pub process_order: Arc<InputStream<Order, OrderState, String>>,
    pub split_pipeline: [Stream<Order>; 2],
    pub process_order_items: Stream<OrderItem>,
    pub process_order_item: Arc<SinkStreamWithResult<OrderItem, OrderItemResult, OrderState>>,
    pub process_order_item_error: Stream<OrderState>,
    pub map_order_item_result_to_order_state: Stream<OrderState>,
    pub soft_deadline: Stream<Order>,
    pub map_to_order_state: Stream<OrderState>,
    pub merge_results: Stream<OrderState>,
    pub split_order_result: [Stream<OrderState>; 2],
    pub map_to_order_processed: Stream<OrderProcessed>,
    pub publish_order_processed: Arc<SinkStreamWithResult<OrderProcessed, String, String>>,
}

pub struct ServiceHandlers {
    pub process_order_source: ProcessOrderSource,
}

pub struct ServiceDataConnectors {
    pub order_events_data_sink: Arc<RdkafkaKafkaDataSink>,
    pub inventory_data_sink: Arc<TonicDataSink>,
}

pub struct ServiceRuntime {
    pub streams: ServiceStreams,
    pub handlers: ServiceHandlers,
    pub data_connectors: ServiceDataConnectors,
}

struct GeneratedServiceInner {
    runtime: ServiceRuntime,
    app: OnceLock<Arc<ServiceApp>>,
}

#[derive(Clone)]
pub struct GeneratedService {
    inner: Arc<GeneratedServiceInner>,
}

#[derive(Clone)]
pub struct ServiceMakers {
    pub map_order_item_result_to_order_state: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &MapStreamConfig,
    ) -> RuntimeResult<MapOrderItemResultToOrderState> + Send + Sync>,
    pub map_to_order_processed: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &MapStreamConfig,
    ) -> RuntimeResult<MapToOrderProcessed> + Send + Sync>,
    pub map_to_order_state: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &MapStreamConfig,
    ) -> RuntimeResult<MapToOrderState> + Send + Sync>,
    pub order_processed_endpoint_sink: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &KafkaEndpointConfig,
    ) -> RuntimeResult<OrderProcessedEndpointSink> + Send + Sync>,
    pub process_order_item_sink: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &GrpcEndpointConfig,
    ) -> RuntimeResult<ProcessOrderItemSink> + Send + Sync>,
    pub process_order_items: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &FlatMapStreamConfig,
    ) -> RuntimeResult<ProcessOrderItems> + Send + Sync>,
    pub process_order_source: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &HttpEndpointConfig,
    ) -> RuntimeResult<ProcessOrderSource> + Send + Sync>,
    pub soft_deadline: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &DelayStreamConfig,
    ) -> RuntimeResult<SoftDeadline> + Send + Sync>,
}

impl Default for ServiceMakers {
    fn default() -> Self {
        Self {
            map_order_item_result_to_order_state: Arc::new(make_map_order_item_result_to_order_state),
            map_to_order_processed: Arc::new(make_map_to_order_processed),
            map_to_order_state: Arc::new(make_map_to_order_state),
            order_processed_endpoint_sink: Arc::new(make_order_processed_endpoint_sink),
            process_order_item_sink: Arc::new(make_process_order_item_sink),
            process_order_items: Arc::new(make_process_order_items),
            process_order_source: Arc::new(make_process_order_source),
            soft_deadline: Arc::new(make_soft_deadline),
        }
    }
}

pub struct ServiceFunctions {
    pub map_order_item_result_to_order_state: MapOrderItemResultToOrderState,
    pub map_to_order_processed: MapToOrderProcessed,
    pub map_to_order_state: MapToOrderState,
    pub order_processed_endpoint_sink: OrderProcessedEndpointSink,
    pub process_order_item_sink: ProcessOrderItemSink,
    pub process_order_items: ProcessOrderItems,
    pub process_order_source: ProcessOrderSource,
    pub soft_deadline: SoftDeadline,
}

pub fn init_functions(
    context: MessageContext,
    config: &Config,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
) -> RuntimeResult<ServiceFunctions> {
    Ok(ServiceFunctions {
        map_order_item_result_to_order_state: (makers.map_order_item_result_to_order_state)(context.clone(), environment.clone(), &config.streams.map_order_item_result_to_order_state)?,
        map_to_order_processed: (makers.map_to_order_processed)(context.clone(), environment.clone(), &config.streams.map_to_order_processed)?,
        map_to_order_state: (makers.map_to_order_state)(context.clone(), environment.clone(), &config.streams.map_to_order_state)?,
        order_processed_endpoint_sink: (makers.order_processed_endpoint_sink)(context.clone(), environment.clone(), &config.endpoints.order_processed)?,
        process_order_item_sink: (makers.process_order_item_sink)(context.clone(), environment.clone(), &config.endpoints.process_order_item)?,
        process_order_items: (makers.process_order_items)(context.clone(), environment.clone(), &config.streams.process_order_items)?,
        process_order_source: (makers.process_order_source)(context.clone(), environment.clone(), &config.endpoints.process_order)?,
        soft_deadline: (makers.soft_deadline)(context.clone(), environment.clone(), &config.streams.soft_deadline)?,
    })
}

pub async fn init_runtime(
    config: &Config,
    environment: RuntimeEnvironment,
    functions: ServiceFunctions,
) -> Result<ServiceRuntime, Box<dyn std::error::Error>> {
    let process_order = Arc::new(InputStream::<Order, OrderState, String>::new(&config.streams.process_order, environment.clone()));
    let split_pipeline = process_order.stream().split(&config.streams.split_pipeline)?;
    let [process_order_items_branch, soft_deadline_branch] = split_pipeline.clone();
    let process_order_items = process_order_items_branch.flat_map(&config.streams.process_order_items, functions.process_order_items)?;
    let process_order_item = process_order_items.sink_with_result::<OrderItemResult, OrderState>(&config.streams.process_order_item)?;
    let process_order_item_error = process_order_item.error_stream().clone();
    let map_order_item_result_to_order_state = process_order_item.stream().clone().map(&config.streams.map_order_item_result_to_order_state, functions.map_order_item_result_to_order_state)?;
    let soft_deadline = soft_deadline_branch.delay(&config.streams.soft_deadline, functions.soft_deadline)?;
    let map_to_order_state = soft_deadline.map(&config.streams.map_to_order_state, functions.map_to_order_state)?;
    let merge_results = map_to_order_state.merge(&config.streams.merge_results, &[map_order_item_result_to_order_state.clone(), process_order_item_error.clone()])?;
    let split_order_result = merge_results.split(&config.streams.split_order_result)?;
    let [map_to_order_processed_branch, process_order_branch] = split_order_result.clone();
    let map_to_order_processed = map_to_order_processed_branch.map(&config.streams.map_to_order_processed, functions.map_to_order_processed)?;
    let publish_order_processed = map_to_order_processed.sink_with_result::<String, String>(&config.streams.publish_order_processed)?;
    process_order.set_source(&process_order_branch)?;
    let order_events_data_sink = RdkafkaKafkaDataSink::from_stream(&publish_order_processed)?;
    let inventory_data_sink = TonicDataSink::from_stream(&process_order_item)?;
    let client_sink = Arc::clone(&inventory_data_sink);
    let client: NoStreamingClientFunction<ProcessOrderItemRequest, ProcessOrderItemResponse> = Arc::new(move |context, request| {
        let client_sink = Arc::clone(&client_sink);
        Box::pin(async move {
            let channel = client_sink.channel().await?;
            let mut request = tonic::Request::new(request);
            context.apply_to_tonic_request(&mut request);
            Ok(InventoryServiceApiClient::new(channel).process_order_item(request).await?.into_inner())
        })
    });
    make_grpc_no_streaming_endpoint_consumer(
        &process_order_item,
        functions.process_order_item_sink,
        client,
    )?;
    make_rdkafka_kafka_endpoint_consumer(
        &publish_order_processed, Arc::clone(&order_events_data_sink), None,
        functions.order_processed_endpoint_sink,
    )?;
    Ok(ServiceRuntime {
      streams: ServiceStreams {
        process_order: process_order.clone(),
        split_pipeline,
        process_order_items,
        process_order_item,
        process_order_item_error,
        map_order_item_result_to_order_state,
        soft_deadline,
        map_to_order_state,
        merge_results,
        split_order_result,
        map_to_order_processed,
        publish_order_processed,
      },
      handlers: ServiceHandlers {
        process_order_source: functions.process_order_source,
      },
      data_connectors: ServiceDataConnectors {
        order_events_data_sink: order_events_data_sink,
        inventory_data_sink: inventory_data_sink,
      },
    })
}

impl GeneratedService {
    pub async fn new(
        config: &Config,
        environment: RuntimeEnvironment,
        config_loader: ConfigLoader<Config>,
        custom_makers_init: fn(MessageContext, &mut ServiceMakers) -> RuntimeResult<()>,
        custom_functions_init: fn(MessageContext, &mut ServiceFunctions) -> RuntimeResult<()>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let mut app = ServiceApp::new(environment, config.service())?;
        let context = MessageContext::new();
        let mut makers = ServiceMakers::default();
        custom_makers_init(context.clone(), &mut makers)?;
        let mut functions = init_functions(
            context.clone(), config, app.environment().clone(), &makers,
        )?;
        custom_functions_init(context, &mut functions)?;
        let runtime = init_runtime(
            config, app.environment().clone(), functions,
        ).await?;
        let order_service_api_data_source = AxumDataSource::new(
            app.environment().clone(),
            &HttpDataConnectorConfig {
                id: config.endpoints.process_order.id_data_connector,
                name: "Order Service API".to_owned(),
                host: config.http_host.clone(),
                port: config.http_port,
                address: String::new(),
                use_dedicated_listener: false,
            },
        );
        runtime.handlers.process_order_source.reload(
            &config.endpoints.process_order, config.request_timeout_ms,
        );
        order_service_api_data_source.add_endpoint(
            runtime.streams.process_order.as_ref().clone(),
            config.endpoints.process_order.clone(),
            runtime.handlers.process_order_source.clone(),
        )?;
        app.add_http_router(order_service_api_data_source.router())?;
        app.register_data_source(order_service_api_data_source)?;
        app.register_data_sink(Arc::clone(&runtime.data_connectors.order_events_data_sink))?;
        app.register_data_sink(Arc::clone(&runtime.data_connectors.inventory_data_sink))?;

        let service = Self {
            inner: Arc::new(GeneratedServiceInner {
                runtime,
                app: OnceLock::new(),
            }),
        };

        let weak: Weak<GeneratedServiceInner> = Arc::downgrade(&service.inner);
        config_loader.set_reload_handler(move |config, runtime_config| {
            let Some(inner) = weak.upgrade() else {
                return Ok(());
            };
            let app = inner.app.get().ok_or_else(||
                "service application is not initialized".to_owned()
            )?;
            app.validate_reload(&config.service())
                .map_err(|error| error.to_string())?;
            inner.runtime.data_connectors.inventory_data_sink
                .reload_address(config.inventory_address.clone())
                .map_err(|error| error.to_string())?;
            inner.runtime.handlers.process_order_source.reload(
                &config.endpoints.process_order, config.request_timeout_ms,
            );
            app.environment().publish_runtime_config(runtime_config);
            Ok(())
        });
        app.add_component(Arc::new(config_loader))?;
        let app = Arc::new(app);
        service.inner.app.set(app).map_err(|_| {
            "service application initialized twice".to_owned()
        })?;
        Ok(service)
    }

    pub async fn run(self) -> Result<(), Box<dyn std::error::Error>> {
        let app = self.inner.app.get().ok_or_else(||
            "service application is not initialized".to_owned()
        )?;
        app.start(MessageContext::new()).await?;
        tokio::signal::ctrl_c().await?;
        app.stop(MessageContext::new()).await?;
        Ok(())
    }
}