// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::service_generated::GeneratedService;


use futures_util::{Stream as FuturesStream, StreamExt};

fn grpc_request_stream<T>(receiver: tokio::sync::mpsc::Receiver<T>)
    -> impl FuturesStream<Item = T> + Send
where T: Send + 'static {
    futures_util::stream::unfold(receiver, |mut receiver| async move {
        receiver.recv().await.map(|value| (value, receiver))
    })
}



pub struct ServiceServers;

impl ServiceServers {
    pub fn register(app: &mut ServiceApp, service: GeneratedService) -> RuntimeResult<()> {
        let _ = (&app, &service);
        Ok(())
    }
}