// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::connectors_generated::ServiceInfrastructure;





pub struct ServiceClients {
}

impl ServiceClients {
    pub fn init_clients(infrastructure: &ServiceInfrastructure) -> Self {
        let _ = infrastructure;

        Self {
        }
    }
}