// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::makers_generated::ServiceMakers;

pub struct ServiceFunctions {
    pub advance_cycle_analytics: Arc<AdvanceCycleAnalytics>,
    pub analytics_orders_source: AnalyticsOrdersSource,
    pub analytics_payments_source: AnalyticsPaymentsSource,
    pub analytics_schedule_source: AnalyticsScheduleSource,
    pub analytics_shipments_source: AnalyticsShipmentsSource,
    pub build_substream_analytics_result: Arc<BuildSubstreamAnalyticsResult>,
    pub complete_cycle_analytics: Arc<CompleteCycleAnalytics>,
    pub continue_cycle_analytics: Arc<ContinueCycleAnalytics>,
    pub count_order_processed: Arc<CountOrderProcessed>,
    pub cycle_analytics_input_source: CycleAnalyticsInputSource,
    pub cycle_analytics_result_sink: CycleAnalyticsResultSink,
    pub high_value_analytics_sink: HighValueAnalyticsSink,
    pub invoke_analytics_substream: Arc<InvokeAnalyticsSubstream>,
    pub join_order_payment_analytics: Arc<JoinOrderPaymentAnalytics>,
    pub joined_analytics_sink: JoinedAnalyticsSink,
    pub key_orders_for_join: Arc<KeyOrdersForJoin>,
    pub key_orders_for_multi_join: Arc<KeyOrdersForMultiJoin>,
    pub key_payments_for_join: Arc<KeyPaymentsForJoin>,
    pub key_payments_for_multi_join: Arc<KeyPaymentsForMultiJoin>,
    pub key_shipments_for_multi_join: Arc<KeyShipmentsForMultiJoin>,
    pub multi_join_analytics_events: Arc<MultiJoinAnalyticsEvents>,
    pub order_processed_endpoint_source: OrderProcessedEndpointSource,
    pub route_analytics_result: Arc<RouteAnalyticsResult>,
    pub standard_analytics_sink: StandardAnalyticsSink,
    pub substream_analytics_input_source: SubstreamAnalyticsInputSource,
    pub substream_analytics_result_sink: SubstreamAnalyticsResultSink,
}

// Keep fallible field extraction out of the async initialization state machine.
struct ServiceFunctionsBuilder {
    advance_cycle_analytics: Option<Arc<AdvanceCycleAnalytics>>,
    analytics_orders_source: Option<AnalyticsOrdersSource>,
    analytics_payments_source: Option<AnalyticsPaymentsSource>,
    analytics_schedule_source: Option<AnalyticsScheduleSource>,
    analytics_shipments_source: Option<AnalyticsShipmentsSource>,
    build_substream_analytics_result: Option<Arc<BuildSubstreamAnalyticsResult>>,
    complete_cycle_analytics: Option<Arc<CompleteCycleAnalytics>>,
    continue_cycle_analytics: Option<Arc<ContinueCycleAnalytics>>,
    count_order_processed: Option<Arc<CountOrderProcessed>>,
    cycle_analytics_input_source: Option<CycleAnalyticsInputSource>,
    cycle_analytics_result_sink: Option<CycleAnalyticsResultSink>,
    high_value_analytics_sink: Option<HighValueAnalyticsSink>,
    invoke_analytics_substream: Option<Arc<InvokeAnalyticsSubstream>>,
    join_order_payment_analytics: Option<Arc<JoinOrderPaymentAnalytics>>,
    joined_analytics_sink: Option<JoinedAnalyticsSink>,
    key_orders_for_join: Option<Arc<KeyOrdersForJoin>>,
    key_orders_for_multi_join: Option<Arc<KeyOrdersForMultiJoin>>,
    key_payments_for_join: Option<Arc<KeyPaymentsForJoin>>,
    key_payments_for_multi_join: Option<Arc<KeyPaymentsForMultiJoin>>,
    key_shipments_for_multi_join: Option<Arc<KeyShipmentsForMultiJoin>>,
    multi_join_analytics_events: Option<Arc<MultiJoinAnalyticsEvents>>,
    order_processed_endpoint_source: Option<OrderProcessedEndpointSource>,
    route_analytics_result: Option<Arc<RouteAnalyticsResult>>,
    standard_analytics_sink: Option<StandardAnalyticsSink>,
    substream_analytics_input_source: Option<SubstreamAnalyticsInputSource>,
    substream_analytics_result_sink: Option<SubstreamAnalyticsResultSink>,
}
struct FunctionCompletionPart0 {
    advance_cycle_analytics: Arc<AdvanceCycleAnalytics>,
    analytics_orders_source: AnalyticsOrdersSource,
    analytics_payments_source: AnalyticsPaymentsSource,
    analytics_schedule_source: AnalyticsScheduleSource,
    analytics_shipments_source: AnalyticsShipmentsSource,
    build_substream_analytics_result: Arc<BuildSubstreamAnalyticsResult>,
    complete_cycle_analytics: Arc<CompleteCycleAnalytics>,
    continue_cycle_analytics: Arc<ContinueCycleAnalytics>,
    count_order_processed: Arc<CountOrderProcessed>,
    cycle_analytics_input_source: CycleAnalyticsInputSource,
    cycle_analytics_result_sink: CycleAnalyticsResultSink,
    high_value_analytics_sink: HighValueAnalyticsSink,
    invoke_analytics_substream: Arc<InvokeAnalyticsSubstream>,
    join_order_payment_analytics: Arc<JoinOrderPaymentAnalytics>,
    joined_analytics_sink: JoinedAnalyticsSink,
    key_orders_for_join: Arc<KeyOrdersForJoin>,
    key_orders_for_multi_join: Arc<KeyOrdersForMultiJoin>,
    key_payments_for_join: Arc<KeyPaymentsForJoin>,
    key_payments_for_multi_join: Arc<KeyPaymentsForMultiJoin>,
    key_shipments_for_multi_join: Arc<KeyShipmentsForMultiJoin>,
    multi_join_analytics_events: Arc<MultiJoinAnalyticsEvents>,
    order_processed_endpoint_source: OrderProcessedEndpointSource,
    route_analytics_result: Arc<RouteAnalyticsResult>,
    standard_analytics_sink: StandardAnalyticsSink,
    substream_analytics_input_source: SubstreamAnalyticsInputSource,
    substream_analytics_result_sink: SubstreamAnalyticsResultSink,
}

impl ServiceFunctionsBuilder {
    #[inline(never)]
    fn new() -> Box<Self> {
        Box::new(Self {
            advance_cycle_analytics: None,
            analytics_orders_source: None,
            analytics_payments_source: None,
            analytics_schedule_source: None,
            analytics_shipments_source: None,
            build_substream_analytics_result: None,
            complete_cycle_analytics: None,
            continue_cycle_analytics: None,
            count_order_processed: None,
            cycle_analytics_input_source: None,
            cycle_analytics_result_sink: None,
            high_value_analytics_sink: None,
            invoke_analytics_substream: None,
            join_order_payment_analytics: None,
            joined_analytics_sink: None,
            key_orders_for_join: None,
            key_orders_for_multi_join: None,
            key_payments_for_join: None,
            key_payments_for_multi_join: None,
            key_shipments_for_multi_join: None,
            multi_join_analytics_events: None,
            order_processed_endpoint_source: None,
            route_analytics_result: None,
            standard_analytics_sink: None,
            substream_analytics_input_source: None,
            substream_analytics_result_sink: None,
        })
    }
    #[inline(never)]
    fn store_default_group(&mut self, mut results: Box<DefaultFunctionGroupResults>) {
        self.store_default_group_part_0(&mut results);
    }
    #[inline(never)]
    fn store_default_group_part_0(&mut self, results: &mut DefaultFunctionGroupResults) {
        self.advance_cycle_analytics = results.advance_cycle_analytics.take();
        self.analytics_orders_source = results.analytics_orders_source.take();
        self.analytics_payments_source = results.analytics_payments_source.take();
        self.analytics_schedule_source = results.analytics_schedule_source.take();
        self.analytics_shipments_source = results.analytics_shipments_source.take();
        self.build_substream_analytics_result = results.build_substream_analytics_result.take();
        self.complete_cycle_analytics = results.complete_cycle_analytics.take();
        self.continue_cycle_analytics = results.continue_cycle_analytics.take();
        self.count_order_processed = results.count_order_processed.take();
        self.cycle_analytics_input_source = results.cycle_analytics_input_source.take();
        self.cycle_analytics_result_sink = results.cycle_analytics_result_sink.take();
        self.high_value_analytics_sink = results.high_value_analytics_sink.take();
        self.invoke_analytics_substream = results.invoke_analytics_substream.take();
        self.join_order_payment_analytics = results.join_order_payment_analytics.take();
        self.joined_analytics_sink = results.joined_analytics_sink.take();
        self.key_orders_for_join = results.key_orders_for_join.take();
        self.key_orders_for_multi_join = results.key_orders_for_multi_join.take();
        self.key_payments_for_join = results.key_payments_for_join.take();
        self.key_payments_for_multi_join = results.key_payments_for_multi_join.take();
        self.key_shipments_for_multi_join = results.key_shipments_for_multi_join.take();
        self.multi_join_analytics_events = results.multi_join_analytics_events.take();
        self.order_processed_endpoint_source = results.order_processed_endpoint_source.take();
        self.route_analytics_result = results.route_analytics_result.take();
        self.standard_analytics_sink = results.standard_analytics_sink.take();
        self.substream_analytics_input_source = results.substream_analytics_input_source.take();
        self.substream_analytics_result_sink = results.substream_analytics_result_sink.take();
    }
    #[inline(never)]
    fn complete_part_0(&mut self) -> RuntimeResult<FunctionCompletionPart0> {
        Ok(FunctionCompletionPart0 {
            advance_cycle_analytics: self.advance_cycle_analytics.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker advance_cycle_analytics failed without an error".to_owned(),
            ))?,
            analytics_orders_source: self.analytics_orders_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker analytics_orders_source failed without an error".to_owned(),
            ))?,
            analytics_payments_source: self.analytics_payments_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker analytics_payments_source failed without an error".to_owned(),
            ))?,
            analytics_schedule_source: self.analytics_schedule_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker analytics_schedule_source failed without an error".to_owned(),
            ))?,
            analytics_shipments_source: self.analytics_shipments_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker analytics_shipments_source failed without an error".to_owned(),
            ))?,
            build_substream_analytics_result: self.build_substream_analytics_result.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker build_substream_analytics_result failed without an error".to_owned(),
            ))?,
            complete_cycle_analytics: self.complete_cycle_analytics.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker complete_cycle_analytics failed without an error".to_owned(),
            ))?,
            continue_cycle_analytics: self.continue_cycle_analytics.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker continue_cycle_analytics failed without an error".to_owned(),
            ))?,
            count_order_processed: self.count_order_processed.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker count_order_processed failed without an error".to_owned(),
            ))?,
            cycle_analytics_input_source: self.cycle_analytics_input_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker cycle_analytics_input_source failed without an error".to_owned(),
            ))?,
            cycle_analytics_result_sink: self.cycle_analytics_result_sink.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker cycle_analytics_result_sink failed without an error".to_owned(),
            ))?,
            high_value_analytics_sink: self.high_value_analytics_sink.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker high_value_analytics_sink failed without an error".to_owned(),
            ))?,
            invoke_analytics_substream: self.invoke_analytics_substream.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker invoke_analytics_substream failed without an error".to_owned(),
            ))?,
            join_order_payment_analytics: self.join_order_payment_analytics.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker join_order_payment_analytics failed without an error".to_owned(),
            ))?,
            joined_analytics_sink: self.joined_analytics_sink.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker joined_analytics_sink failed without an error".to_owned(),
            ))?,
            key_orders_for_join: self.key_orders_for_join.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker key_orders_for_join failed without an error".to_owned(),
            ))?,
            key_orders_for_multi_join: self.key_orders_for_multi_join.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker key_orders_for_multi_join failed without an error".to_owned(),
            ))?,
            key_payments_for_join: self.key_payments_for_join.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker key_payments_for_join failed without an error".to_owned(),
            ))?,
            key_payments_for_multi_join: self.key_payments_for_multi_join.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker key_payments_for_multi_join failed without an error".to_owned(),
            ))?,
            key_shipments_for_multi_join: self.key_shipments_for_multi_join.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker key_shipments_for_multi_join failed without an error".to_owned(),
            ))?,
            multi_join_analytics_events: self.multi_join_analytics_events.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker multi_join_analytics_events failed without an error".to_owned(),
            ))?,
            order_processed_endpoint_source: self.order_processed_endpoint_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker order_processed_endpoint_source failed without an error".to_owned(),
            ))?,
            route_analytics_result: self.route_analytics_result.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker route_analytics_result failed without an error".to_owned(),
            ))?,
            standard_analytics_sink: self.standard_analytics_sink.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker standard_analytics_sink failed without an error".to_owned(),
            ))?,
            substream_analytics_input_source: self.substream_analytics_input_source.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker substream_analytics_input_source failed without an error".to_owned(),
            ))?,
            substream_analytics_result_sink: self.substream_analytics_result_sink.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
                "function maker substream_analytics_result_sink failed without an error".to_owned(),
            ))?,
        })
    }

    #[inline(never)]
    fn finish(mut self: Box<Self>) -> RuntimeResult<ServiceFunctions> {
        let part_0 = self.complete_part_0()?;
        Ok(ServiceFunctions {
            advance_cycle_analytics: part_0.advance_cycle_analytics,
            analytics_orders_source: part_0.analytics_orders_source,
            analytics_payments_source: part_0.analytics_payments_source,
            analytics_schedule_source: part_0.analytics_schedule_source,
            analytics_shipments_source: part_0.analytics_shipments_source,
            build_substream_analytics_result: part_0.build_substream_analytics_result,
            complete_cycle_analytics: part_0.complete_cycle_analytics,
            continue_cycle_analytics: part_0.continue_cycle_analytics,
            count_order_processed: part_0.count_order_processed,
            cycle_analytics_input_source: part_0.cycle_analytics_input_source,
            cycle_analytics_result_sink: part_0.cycle_analytics_result_sink,
            high_value_analytics_sink: part_0.high_value_analytics_sink,
            invoke_analytics_substream: part_0.invoke_analytics_substream,
            join_order_payment_analytics: part_0.join_order_payment_analytics,
            joined_analytics_sink: part_0.joined_analytics_sink,
            key_orders_for_join: part_0.key_orders_for_join,
            key_orders_for_multi_join: part_0.key_orders_for_multi_join,
            key_payments_for_join: part_0.key_payments_for_join,
            key_payments_for_multi_join: part_0.key_payments_for_multi_join,
            key_shipments_for_multi_join: part_0.key_shipments_for_multi_join,
            multi_join_analytics_events: part_0.multi_join_analytics_events,
            order_processed_endpoint_source: part_0.order_processed_endpoint_source,
            route_analytics_result: part_0.route_analytics_result,
            standard_analytics_sink: part_0.standard_analytics_sink,
            substream_analytics_input_source: part_0.substream_analytics_input_source,
            substream_analytics_result_sink: part_0.substream_analytics_result_sink,
        })
    }
}
struct DefaultFunctionGroupResults {
    advance_cycle_analytics: Option<Arc<AdvanceCycleAnalytics>>,
    analytics_orders_source: Option<AnalyticsOrdersSource>,
    analytics_payments_source: Option<AnalyticsPaymentsSource>,
    analytics_schedule_source: Option<AnalyticsScheduleSource>,
    analytics_shipments_source: Option<AnalyticsShipmentsSource>,
    build_substream_analytics_result: Option<Arc<BuildSubstreamAnalyticsResult>>,
    complete_cycle_analytics: Option<Arc<CompleteCycleAnalytics>>,
    continue_cycle_analytics: Option<Arc<ContinueCycleAnalytics>>,
    count_order_processed: Option<Arc<CountOrderProcessed>>,
    cycle_analytics_input_source: Option<CycleAnalyticsInputSource>,
    cycle_analytics_result_sink: Option<CycleAnalyticsResultSink>,
    high_value_analytics_sink: Option<HighValueAnalyticsSink>,
    invoke_analytics_substream: Option<Arc<InvokeAnalyticsSubstream>>,
    join_order_payment_analytics: Option<Arc<JoinOrderPaymentAnalytics>>,
    joined_analytics_sink: Option<JoinedAnalyticsSink>,
    key_orders_for_join: Option<Arc<KeyOrdersForJoin>>,
    key_orders_for_multi_join: Option<Arc<KeyOrdersForMultiJoin>>,
    key_payments_for_join: Option<Arc<KeyPaymentsForJoin>>,
    key_payments_for_multi_join: Option<Arc<KeyPaymentsForMultiJoin>>,
    key_shipments_for_multi_join: Option<Arc<KeyShipmentsForMultiJoin>>,
    multi_join_analytics_events: Option<Arc<MultiJoinAnalyticsEvents>>,
    order_processed_endpoint_source: Option<OrderProcessedEndpointSource>,
    route_analytics_result: Option<Arc<RouteAnalyticsResult>>,
    standard_analytics_sink: Option<StandardAnalyticsSink>,
    substream_analytics_input_source: Option<SubstreamAnalyticsInputSource>,
    substream_analytics_result_sink: Option<SubstreamAnalyticsResultSink>,
}

#[inline(never)]
fn init_default_group(
    maker_group_context: MessageContext,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
    maker_error_sender: mpsc::Sender<RuntimeError>,
) -> Pin<Box<dyn Future<Output = Box<DefaultFunctionGroupResults>> + Send>> {
    let advance_cycle_analytics_maker = makers.advance_cycle_analytics.clone();
    let analytics_orders_source_maker = makers.analytics_orders_source.clone();
    let analytics_payments_source_maker = makers.analytics_payments_source.clone();
    let analytics_schedule_source_maker = makers.analytics_schedule_source.clone();
    let analytics_shipments_source_maker = makers.analytics_shipments_source.clone();
    let build_substream_analytics_result_maker = makers.build_substream_analytics_result.clone();
    let complete_cycle_analytics_maker = makers.complete_cycle_analytics.clone();
    let continue_cycle_analytics_maker = makers.continue_cycle_analytics.clone();
    let count_order_processed_maker = makers.count_order_processed.clone();
    let cycle_analytics_input_source_maker = makers.cycle_analytics_input_source.clone();
    let cycle_analytics_result_sink_maker = makers.cycle_analytics_result_sink.clone();
    let high_value_analytics_sink_maker = makers.high_value_analytics_sink.clone();
    let invoke_analytics_substream_maker = makers.invoke_analytics_substream.clone();
    let join_order_payment_analytics_maker = makers.join_order_payment_analytics.clone();
    let joined_analytics_sink_maker = makers.joined_analytics_sink.clone();
    let key_orders_for_join_maker = makers.key_orders_for_join.clone();
    let key_orders_for_multi_join_maker = makers.key_orders_for_multi_join.clone();
    let key_payments_for_join_maker = makers.key_payments_for_join.clone();
    let key_payments_for_multi_join_maker = makers.key_payments_for_multi_join.clone();
    let key_shipments_for_multi_join_maker = makers.key_shipments_for_multi_join.clone();
    let multi_join_analytics_events_maker = makers.multi_join_analytics_events.clone();
    let order_processed_endpoint_source_maker = makers.order_processed_endpoint_source.clone();
    let route_analytics_result_maker = makers.route_analytics_result.clone();
    let standard_analytics_sink_maker = makers.standard_analytics_sink.clone();
    let substream_analytics_input_source_maker = makers.substream_analytics_input_source.clone();
    let substream_analytics_result_sink_maker = makers.substream_analytics_result_sink.clone();
    Box::pin(async move {
        let advance_cycle_analytics_context = maker_group_context.clone();
        let advance_cycle_analytics_group_context = maker_group_context.clone();
        let advance_cycle_analytics_environment = environment.clone();
        let advance_cycle_analytics_error_sender = maker_error_sender.clone();
        let advance_cycle_analytics_future = async move {
            let result = (advance_cycle_analytics_maker)(
                advance_cycle_analytics_context,
                advance_cycle_analytics_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    advance_cycle_analytics_group_context.cancel();
                    advance_cycle_analytics_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut advance_cycle_analytics = None;
        let analytics_orders_source_context = maker_group_context.clone();
        let analytics_orders_source_group_context = maker_group_context.clone();
        let analytics_orders_source_environment = environment.clone();
        let analytics_orders_source_error_sender = maker_error_sender.clone();
        let analytics_orders_source_future = async move {
            let result = (analytics_orders_source_maker)(
                analytics_orders_source_context,
                analytics_orders_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    analytics_orders_source_group_context.cancel();
                    analytics_orders_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut analytics_orders_source = None;
        let analytics_payments_source_context = maker_group_context.clone();
        let analytics_payments_source_group_context = maker_group_context.clone();
        let analytics_payments_source_environment = environment.clone();
        let analytics_payments_source_error_sender = maker_error_sender.clone();
        let analytics_payments_source_future = async move {
            let result = (analytics_payments_source_maker)(
                analytics_payments_source_context,
                analytics_payments_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    analytics_payments_source_group_context.cancel();
                    analytics_payments_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut analytics_payments_source = None;
        let analytics_schedule_source_context = maker_group_context.clone();
        let analytics_schedule_source_group_context = maker_group_context.clone();
        let analytics_schedule_source_environment = environment.clone();
        let analytics_schedule_source_error_sender = maker_error_sender.clone();
        let analytics_schedule_source_future = async move {
            let result = (analytics_schedule_source_maker)(
                analytics_schedule_source_context,
                analytics_schedule_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    analytics_schedule_source_group_context.cancel();
                    analytics_schedule_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut analytics_schedule_source = None;
        let analytics_shipments_source_context = maker_group_context.clone();
        let analytics_shipments_source_group_context = maker_group_context.clone();
        let analytics_shipments_source_environment = environment.clone();
        let analytics_shipments_source_error_sender = maker_error_sender.clone();
        let analytics_shipments_source_future = async move {
            let result = (analytics_shipments_source_maker)(
                analytics_shipments_source_context,
                analytics_shipments_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    analytics_shipments_source_group_context.cancel();
                    analytics_shipments_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut analytics_shipments_source = None;
        let build_substream_analytics_result_context = maker_group_context.clone();
        let build_substream_analytics_result_group_context = maker_group_context.clone();
        let build_substream_analytics_result_environment = environment.clone();
        let build_substream_analytics_result_error_sender = maker_error_sender.clone();
        let build_substream_analytics_result_future = async move {
            let result = (build_substream_analytics_result_maker)(
                build_substream_analytics_result_context,
                build_substream_analytics_result_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    build_substream_analytics_result_group_context.cancel();
                    build_substream_analytics_result_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut build_substream_analytics_result = None;
        let complete_cycle_analytics_context = maker_group_context.clone();
        let complete_cycle_analytics_group_context = maker_group_context.clone();
        let complete_cycle_analytics_environment = environment.clone();
        let complete_cycle_analytics_error_sender = maker_error_sender.clone();
        let complete_cycle_analytics_future = async move {
            let result = (complete_cycle_analytics_maker)(
                complete_cycle_analytics_context,
                complete_cycle_analytics_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    complete_cycle_analytics_group_context.cancel();
                    complete_cycle_analytics_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut complete_cycle_analytics = None;
        let continue_cycle_analytics_context = maker_group_context.clone();
        let continue_cycle_analytics_group_context = maker_group_context.clone();
        let continue_cycle_analytics_environment = environment.clone();
        let continue_cycle_analytics_error_sender = maker_error_sender.clone();
        let continue_cycle_analytics_future = async move {
            let result = (continue_cycle_analytics_maker)(
                continue_cycle_analytics_context,
                continue_cycle_analytics_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    continue_cycle_analytics_group_context.cancel();
                    continue_cycle_analytics_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut continue_cycle_analytics = None;
        let count_order_processed_context = maker_group_context.clone();
        let count_order_processed_group_context = maker_group_context.clone();
        let count_order_processed_environment = environment.clone();
        let count_order_processed_error_sender = maker_error_sender.clone();
        let count_order_processed_future = async move {
            let result = (count_order_processed_maker)(
                count_order_processed_context,
                count_order_processed_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    count_order_processed_group_context.cancel();
                    count_order_processed_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut count_order_processed = None;
        let cycle_analytics_input_source_context = maker_group_context.clone();
        let cycle_analytics_input_source_group_context = maker_group_context.clone();
        let cycle_analytics_input_source_environment = environment.clone();
        let cycle_analytics_input_source_error_sender = maker_error_sender.clone();
        let cycle_analytics_input_source_future = async move {
            let result = (cycle_analytics_input_source_maker)(
                cycle_analytics_input_source_context,
                cycle_analytics_input_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    cycle_analytics_input_source_group_context.cancel();
                    cycle_analytics_input_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut cycle_analytics_input_source = None;
        let cycle_analytics_result_sink_context = maker_group_context.clone();
        let cycle_analytics_result_sink_group_context = maker_group_context.clone();
        let cycle_analytics_result_sink_environment = environment.clone();
        let cycle_analytics_result_sink_error_sender = maker_error_sender.clone();
        let cycle_analytics_result_sink_future = async move {
            let result = (cycle_analytics_result_sink_maker)(
                cycle_analytics_result_sink_context,
                cycle_analytics_result_sink_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    cycle_analytics_result_sink_group_context.cancel();
                    cycle_analytics_result_sink_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut cycle_analytics_result_sink = None;
        let high_value_analytics_sink_context = maker_group_context.clone();
        let high_value_analytics_sink_group_context = maker_group_context.clone();
        let high_value_analytics_sink_environment = environment.clone();
        let high_value_analytics_sink_error_sender = maker_error_sender.clone();
        let high_value_analytics_sink_future = async move {
            let result = (high_value_analytics_sink_maker)(
                high_value_analytics_sink_context,
                high_value_analytics_sink_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    high_value_analytics_sink_group_context.cancel();
                    high_value_analytics_sink_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut high_value_analytics_sink = None;
        let invoke_analytics_substream_context = maker_group_context.clone();
        let invoke_analytics_substream_group_context = maker_group_context.clone();
        let invoke_analytics_substream_environment = environment.clone();
        let invoke_analytics_substream_error_sender = maker_error_sender.clone();
        let invoke_analytics_substream_future = async move {
            let result = (invoke_analytics_substream_maker)(
                invoke_analytics_substream_context,
                invoke_analytics_substream_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    invoke_analytics_substream_group_context.cancel();
                    invoke_analytics_substream_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut invoke_analytics_substream = None;
        let join_order_payment_analytics_context = maker_group_context.clone();
        let join_order_payment_analytics_group_context = maker_group_context.clone();
        let join_order_payment_analytics_environment = environment.clone();
        let join_order_payment_analytics_error_sender = maker_error_sender.clone();
        let join_order_payment_analytics_future = async move {
            let result = (join_order_payment_analytics_maker)(
                join_order_payment_analytics_context,
                join_order_payment_analytics_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    join_order_payment_analytics_group_context.cancel();
                    join_order_payment_analytics_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut join_order_payment_analytics = None;
        let joined_analytics_sink_context = maker_group_context.clone();
        let joined_analytics_sink_group_context = maker_group_context.clone();
        let joined_analytics_sink_environment = environment.clone();
        let joined_analytics_sink_error_sender = maker_error_sender.clone();
        let joined_analytics_sink_future = async move {
            let result = (joined_analytics_sink_maker)(
                joined_analytics_sink_context,
                joined_analytics_sink_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    joined_analytics_sink_group_context.cancel();
                    joined_analytics_sink_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut joined_analytics_sink = None;
        let key_orders_for_join_context = maker_group_context.clone();
        let key_orders_for_join_group_context = maker_group_context.clone();
        let key_orders_for_join_environment = environment.clone();
        let key_orders_for_join_error_sender = maker_error_sender.clone();
        let key_orders_for_join_future = async move {
            let result = (key_orders_for_join_maker)(
                key_orders_for_join_context,
                key_orders_for_join_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    key_orders_for_join_group_context.cancel();
                    key_orders_for_join_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut key_orders_for_join = None;
        let key_orders_for_multi_join_context = maker_group_context.clone();
        let key_orders_for_multi_join_group_context = maker_group_context.clone();
        let key_orders_for_multi_join_environment = environment.clone();
        let key_orders_for_multi_join_error_sender = maker_error_sender.clone();
        let key_orders_for_multi_join_future = async move {
            let result = (key_orders_for_multi_join_maker)(
                key_orders_for_multi_join_context,
                key_orders_for_multi_join_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    key_orders_for_multi_join_group_context.cancel();
                    key_orders_for_multi_join_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut key_orders_for_multi_join = None;
        let key_payments_for_join_context = maker_group_context.clone();
        let key_payments_for_join_group_context = maker_group_context.clone();
        let key_payments_for_join_environment = environment.clone();
        let key_payments_for_join_error_sender = maker_error_sender.clone();
        let key_payments_for_join_future = async move {
            let result = (key_payments_for_join_maker)(
                key_payments_for_join_context,
                key_payments_for_join_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    key_payments_for_join_group_context.cancel();
                    key_payments_for_join_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut key_payments_for_join = None;
        let key_payments_for_multi_join_context = maker_group_context.clone();
        let key_payments_for_multi_join_group_context = maker_group_context.clone();
        let key_payments_for_multi_join_environment = environment.clone();
        let key_payments_for_multi_join_error_sender = maker_error_sender.clone();
        let key_payments_for_multi_join_future = async move {
            let result = (key_payments_for_multi_join_maker)(
                key_payments_for_multi_join_context,
                key_payments_for_multi_join_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    key_payments_for_multi_join_group_context.cancel();
                    key_payments_for_multi_join_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut key_payments_for_multi_join = None;
        let key_shipments_for_multi_join_context = maker_group_context.clone();
        let key_shipments_for_multi_join_group_context = maker_group_context.clone();
        let key_shipments_for_multi_join_environment = environment.clone();
        let key_shipments_for_multi_join_error_sender = maker_error_sender.clone();
        let key_shipments_for_multi_join_future = async move {
            let result = (key_shipments_for_multi_join_maker)(
                key_shipments_for_multi_join_context,
                key_shipments_for_multi_join_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    key_shipments_for_multi_join_group_context.cancel();
                    key_shipments_for_multi_join_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut key_shipments_for_multi_join = None;
        let multi_join_analytics_events_context = maker_group_context.clone();
        let multi_join_analytics_events_group_context = maker_group_context.clone();
        let multi_join_analytics_events_environment = environment.clone();
        let multi_join_analytics_events_error_sender = maker_error_sender.clone();
        let multi_join_analytics_events_future = async move {
            let result = (multi_join_analytics_events_maker)(
                multi_join_analytics_events_context,
                multi_join_analytics_events_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    multi_join_analytics_events_group_context.cancel();
                    multi_join_analytics_events_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut multi_join_analytics_events = None;
        let order_processed_endpoint_source_context = maker_group_context.clone();
        let order_processed_endpoint_source_group_context = maker_group_context.clone();
        let order_processed_endpoint_source_environment = environment.clone();
        let order_processed_endpoint_source_error_sender = maker_error_sender.clone();
        let order_processed_endpoint_source_future = async move {
            let result = (order_processed_endpoint_source_maker)(
                order_processed_endpoint_source_context,
                order_processed_endpoint_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    order_processed_endpoint_source_group_context.cancel();
                    order_processed_endpoint_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut order_processed_endpoint_source = None;
        let route_analytics_result_context = maker_group_context.clone();
        let route_analytics_result_group_context = maker_group_context.clone();
        let route_analytics_result_environment = environment.clone();
        let route_analytics_result_error_sender = maker_error_sender.clone();
        let route_analytics_result_future = async move {
            let result = (route_analytics_result_maker)(
                route_analytics_result_context,
                route_analytics_result_environment,
            ).await;
            match result {
                Ok(value) => Some(Arc::new(value)),
                Err(error) => {
                    route_analytics_result_group_context.cancel();
                    route_analytics_result_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut route_analytics_result = None;
        let standard_analytics_sink_context = maker_group_context.clone();
        let standard_analytics_sink_group_context = maker_group_context.clone();
        let standard_analytics_sink_environment = environment.clone();
        let standard_analytics_sink_error_sender = maker_error_sender.clone();
        let standard_analytics_sink_future = async move {
            let result = (standard_analytics_sink_maker)(
                standard_analytics_sink_context,
                standard_analytics_sink_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    standard_analytics_sink_group_context.cancel();
                    standard_analytics_sink_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut standard_analytics_sink = None;
        let substream_analytics_input_source_context = maker_group_context.clone();
        let substream_analytics_input_source_group_context = maker_group_context.clone();
        let substream_analytics_input_source_environment = environment.clone();
        let substream_analytics_input_source_error_sender = maker_error_sender.clone();
        let substream_analytics_input_source_future = async move {
            let result = (substream_analytics_input_source_maker)(
                substream_analytics_input_source_context,
                substream_analytics_input_source_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    substream_analytics_input_source_group_context.cancel();
                    substream_analytics_input_source_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut substream_analytics_input_source = None;
        let substream_analytics_result_sink_context = maker_group_context.clone();
        let substream_analytics_result_sink_group_context = maker_group_context.clone();
        let substream_analytics_result_sink_environment = environment.clone();
        let substream_analytics_result_sink_error_sender = maker_error_sender.clone();
        let substream_analytics_result_sink_future = async move {
            let result = (substream_analytics_result_sink_maker)(
                substream_analytics_result_sink_context,
                substream_analytics_result_sink_environment,
            ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    substream_analytics_result_sink_group_context.cancel();
                    substream_analytics_result_sink_error_sender.send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let mut substream_analytics_result_sink = None;
        let maker_futures: Vec<Pin<Box<dyn Future<Output = ()> + Send + '_>>> = vec![
            Box::pin(async { advance_cycle_analytics = advance_cycle_analytics_future.await; }),
            Box::pin(async { analytics_orders_source = analytics_orders_source_future.await; }),
            Box::pin(async { analytics_payments_source = analytics_payments_source_future.await; }),
            Box::pin(async { analytics_schedule_source = analytics_schedule_source_future.await; }),
            Box::pin(async { analytics_shipments_source = analytics_shipments_source_future.await; }),
            Box::pin(async { build_substream_analytics_result = build_substream_analytics_result_future.await; }),
            Box::pin(async { complete_cycle_analytics = complete_cycle_analytics_future.await; }),
            Box::pin(async { continue_cycle_analytics = continue_cycle_analytics_future.await; }),
            Box::pin(async { count_order_processed = count_order_processed_future.await; }),
            Box::pin(async { cycle_analytics_input_source = cycle_analytics_input_source_future.await; }),
            Box::pin(async { cycle_analytics_result_sink = cycle_analytics_result_sink_future.await; }),
            Box::pin(async { high_value_analytics_sink = high_value_analytics_sink_future.await; }),
            Box::pin(async { invoke_analytics_substream = invoke_analytics_substream_future.await; }),
            Box::pin(async { join_order_payment_analytics = join_order_payment_analytics_future.await; }),
            Box::pin(async { joined_analytics_sink = joined_analytics_sink_future.await; }),
            Box::pin(async { key_orders_for_join = key_orders_for_join_future.await; }),
            Box::pin(async { key_orders_for_multi_join = key_orders_for_multi_join_future.await; }),
            Box::pin(async { key_payments_for_join = key_payments_for_join_future.await; }),
            Box::pin(async { key_payments_for_multi_join = key_payments_for_multi_join_future.await; }),
            Box::pin(async { key_shipments_for_multi_join = key_shipments_for_multi_join_future.await; }),
            Box::pin(async { multi_join_analytics_events = multi_join_analytics_events_future.await; }),
            Box::pin(async { order_processed_endpoint_source = order_processed_endpoint_source_future.await; }),
            Box::pin(async { route_analytics_result = route_analytics_result_future.await; }),
            Box::pin(async { standard_analytics_sink = standard_analytics_sink_future.await; }),
            Box::pin(async { substream_analytics_input_source = substream_analytics_input_source_future.await; }),
            Box::pin(async { substream_analytics_result_sink = substream_analytics_result_sink_future.await; }),
        ];
        futures_util::future::join_all(maker_futures).await;
        Box::new(DefaultFunctionGroupResults {
            advance_cycle_analytics,
            analytics_orders_source,
            analytics_payments_source,
            analytics_schedule_source,
            analytics_shipments_source,
            build_substream_analytics_result,
            complete_cycle_analytics,
            continue_cycle_analytics,
            count_order_processed,
            cycle_analytics_input_source,
            cycle_analytics_result_sink,
            high_value_analytics_sink,
            invoke_analytics_substream,
            join_order_payment_analytics,
            joined_analytics_sink,
            key_orders_for_join,
            key_orders_for_multi_join,
            key_payments_for_join,
            key_payments_for_multi_join,
            key_shipments_for_multi_join,
            multi_join_analytics_events,
            order_processed_endpoint_source,
            route_analytics_result,
            standard_analytics_sink,
            substream_analytics_input_source,
            substream_analytics_result_sink,
        })
    })
}

impl ServiceFunctions {
    pub async fn init_functions(
        context: MessageContext,
        environment: RuntimeEnvironment,
        makers: &ServiceMakers,
    ) -> RuntimeResult<Self> {
        let _ = (&context, &environment, makers);
        let mut builder = ServiceFunctionsBuilder::new();
        let maker_group_context = context.child();
        let (maker_error_sender, maker_error_receiver) = mpsc::channel::<RuntimeError>();
        let default_group = init_default_group(
            maker_group_context.clone(), environment.clone(), makers, maker_error_sender.clone(),
        ).await;
        maker_group_context.cancel();
        drop(maker_error_sender);
        if let Ok(error) = maker_error_receiver.try_recv() {
            return Err(error);
        }
        builder.store_default_group(default_group);
        builder.finish()
    }
}

pub struct ServiceHandlers {
}