// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::substreams_generated::ServiceSubStreams;

#[derive(Clone)]
pub struct ServiceMakers {
    pub substreams: ServiceSubStreams,
    pub advance_cycle_analytics: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AdvanceCycleAnalytics>> + Send>> + Send + Sync>,
    pub analytics_orders_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsOrdersSource>> + Send>> + Send + Sync>,
    pub analytics_payments_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsPaymentsSource>> + Send>> + Send + Sync>,
    pub analytics_schedule_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsScheduleSource>> + Send>> + Send + Sync>,
    pub analytics_shipments_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsShipmentsSource>> + Send>> + Send + Sync>,
    pub build_substream_analytics_result: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<BuildSubstreamAnalyticsResult>> + Send>> + Send + Sync>,
    pub complete_cycle_analytics: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<CompleteCycleAnalytics>> + Send>> + Send + Sync>,
    pub continue_cycle_analytics: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ContinueCycleAnalytics>> + Send>> + Send + Sync>,
    pub count_order_processed: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<CountOrderProcessed>> + Send>> + Send + Sync>,
    pub cycle_analytics_input_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<CycleAnalyticsInputSource>> + Send>> + Send + Sync>,
    pub cycle_analytics_result_sink: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<CycleAnalyticsResultSink>> + Send>> + Send + Sync>,
    pub high_value_analytics_sink: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<HighValueAnalyticsSink>> + Send>> + Send + Sync>,
    pub invoke_analytics_substream: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<InvokeAnalyticsSubstream>> + Send>> + Send + Sync>,
    pub join_order_payment_analytics: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<JoinOrderPaymentAnalytics>> + Send>> + Send + Sync>,
    pub joined_analytics_sink: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<JoinedAnalyticsSink>> + Send>> + Send + Sync>,
    pub key_orders_for_join: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<KeyOrdersForJoin>> + Send>> + Send + Sync>,
    pub key_orders_for_multi_join: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<KeyOrdersForMultiJoin>> + Send>> + Send + Sync>,
    pub key_payments_for_join: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<KeyPaymentsForJoin>> + Send>> + Send + Sync>,
    pub key_payments_for_multi_join: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<KeyPaymentsForMultiJoin>> + Send>> + Send + Sync>,
    pub key_shipments_for_multi_join: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<KeyShipmentsForMultiJoin>> + Send>> + Send + Sync>,
    pub multi_join_analytics_events: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<MultiJoinAnalyticsEvents>> + Send>> + Send + Sync>,
    pub order_processed_endpoint_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<OrderProcessedEndpointSource>> + Send>> + Send + Sync>,
    pub route_analytics_result: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<RouteAnalyticsResult>> + Send>> + Send + Sync>,
    pub standard_analytics_sink: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<StandardAnalyticsSink>> + Send>> + Send + Sync>,
    pub substream_analytics_input_source: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<SubstreamAnalyticsInputSource>> + Send>> + Send + Sync>,
    pub substream_analytics_result_sink: Arc<dyn Fn(
        MessageContext, RuntimeEnvironment,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<SubstreamAnalyticsResultSink>> + Send>> + Send + Sync>,
    pub order_events_data_source: ServiceInfrastructureMaker<KafkaDataConnectorConfig, Arc<RdkafkaKafkaDataSource>>,
    pub local_cron_data_source: ServiceInfrastructureMaker<CronDataConnectorConfig, Arc<CronDataSource>>,
}

pub type ServiceInfrastructureMaker<C, T> = Arc<dyn for<'a> Fn(
    MessageContext,
    RuntimeEnvironment,
    &'a C,
) -> Pin<Box<dyn Future<Output = RuntimeResult<T>> + Send + 'a>> + Send + Sync>;

impl Default for ServiceMakers {
    fn default() -> Self {
        Self {
            substreams: ServiceSubStreams::default(),
            advance_cycle_analytics: Arc::new(|context, environment| {
                Box::pin(async move { make_advance_cycle_analytics(context, environment).await })
            }),
            analytics_orders_source: Arc::new(|context, environment| {
                Box::pin(async move { make_analytics_orders_source(context, environment).await })
            }),
            analytics_payments_source: Arc::new(|context, environment| {
                Box::pin(async move { make_analytics_payments_source(context, environment).await })
            }),
            analytics_schedule_source: Arc::new(|context, environment| {
                Box::pin(async move { make_analytics_schedule_source(context, environment).await })
            }),
            analytics_shipments_source: Arc::new(|context, environment| {
                Box::pin(async move { make_analytics_shipments_source(context, environment).await })
            }),
            build_substream_analytics_result: Arc::new(|context, environment| {
                Box::pin(async move { make_build_substream_analytics_result(context, environment).await })
            }),
            complete_cycle_analytics: Arc::new(|context, environment| {
                Box::pin(async move { make_complete_cycle_analytics(context, environment).await })
            }),
            continue_cycle_analytics: Arc::new(|context, environment| {
                Box::pin(async move { make_continue_cycle_analytics(context, environment).await })
            }),
            count_order_processed: Arc::new(|context, environment| {
                Box::pin(async move { make_count_order_processed(context, environment).await })
            }),
            cycle_analytics_input_source: Arc::new(|context, environment| {
                Box::pin(async move { make_cycle_analytics_input_source(context, environment).await })
            }),
            cycle_analytics_result_sink: Arc::new(|context, environment| {
                Box::pin(async move { make_cycle_analytics_result_sink(context, environment).await })
            }),
            high_value_analytics_sink: Arc::new(|context, environment| {
                Box::pin(async move { make_high_value_analytics_sink(context, environment).await })
            }),
            invoke_analytics_substream: Arc::new(|context, environment| {
                Box::pin(async move { make_invoke_analytics_substream(context, environment).await })
            }),
            join_order_payment_analytics: Arc::new(|context, environment| {
                Box::pin(async move { make_join_order_payment_analytics(context, environment).await })
            }),
            joined_analytics_sink: Arc::new(|context, environment| {
                Box::pin(async move { make_joined_analytics_sink(context, environment).await })
            }),
            key_orders_for_join: Arc::new(|context, environment| {
                Box::pin(async move { make_key_orders_for_join(context, environment).await })
            }),
            key_orders_for_multi_join: Arc::new(|context, environment| {
                Box::pin(async move { make_key_orders_for_multi_join(context, environment).await })
            }),
            key_payments_for_join: Arc::new(|context, environment| {
                Box::pin(async move { make_key_payments_for_join(context, environment).await })
            }),
            key_payments_for_multi_join: Arc::new(|context, environment| {
                Box::pin(async move { make_key_payments_for_multi_join(context, environment).await })
            }),
            key_shipments_for_multi_join: Arc::new(|context, environment| {
                Box::pin(async move { make_key_shipments_for_multi_join(context, environment).await })
            }),
            multi_join_analytics_events: Arc::new(|context, environment| {
                Box::pin(async move { make_multi_join_analytics_events(context, environment).await })
            }),
            order_processed_endpoint_source: Arc::new(|context, environment| {
                Box::pin(async move { make_order_processed_endpoint_source(context, environment).await })
            }),
            route_analytics_result: Arc::new(|context, environment| {
                Box::pin(async move { make_route_analytics_result(context, environment).await })
            }),
            standard_analytics_sink: Arc::new(|context, environment| {
                Box::pin(async move { make_standard_analytics_sink(context, environment).await })
            }),
            substream_analytics_input_source: Arc::new(|context, environment| {
                Box::pin(async move { make_substream_analytics_input_source(context, environment).await })
            }),
            substream_analytics_result_sink: Arc::new(|context, environment| {
                Box::pin(async move { make_substream_analytics_result_sink(context, environment).await })
            }),
            order_events_data_source: Arc::new(|_context, environment, config| {
                Box::pin(async move { RdkafkaKafkaDataSource::from_config(environment, config) })
            }),
            local_cron_data_source: Arc::new(|_context, environment, config| {
                Box::pin(async move { CronDataSource::from_config(config, environment) })
            }),
        }
    }
}


impl ServiceMakers {
    pub fn init_makers() -> Self { Self::default() }
}