// Code generated by servicegen. DO NOT EDIT.

use super::*;

#[derive(Clone)]
pub struct AnalyticsSourcesPipelineMakers {
    pub analytics_orders_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a CustomEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsOrdersSource>> + Send + 'a>> + Send + Sync>,
    pub analytics_payments_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a CustomEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsPaymentsSource>> + Send + 'a>> + Send + Sync>,
    pub analytics_shipments_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a CustomEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<AnalyticsShipmentsSource>> + Send + 'a>> + Send + Sync>,
}

macro_rules! init_analytics_sources_pipeline_streams {
    ($config:ident, $environment:ident, $functions:ident) => {{
        init_analytics_sources_analytics_orders_stream!($config, $environment, $functions, analytics_orders);
        init_analytics_sources_analytics_payments_stream!($config, $environment, $functions, analytics_payments);
        init_analytics_sources_analytics_shipments_stream!($config, $environment, $functions, analytics_shipments);
        init_analytics_sources_split_analytics_orders_stream!($config, $environment, $functions, split_analytics_orders, analytics_orders.stream(), [key_orders_for_join_branch, key_orders_for_multi_join_branch]);
        init_analytics_sources_split_analytics_payments_stream!($config, $environment, $functions, split_analytics_payments, analytics_payments.stream(), [key_payments_for_join_branch, key_payments_for_multi_join_branch]);
        Ok::<AnalyticsSourcesPipelineStreams, RuntimeError>(AnalyticsSourcesPipelineStreams {
            analytics_orders: analytics_orders,
            analytics_payments: analytics_payments,
            analytics_shipments: analytics_shipments,
            split_analytics_orders,
            split_analytics_payments,
        })
    }};
}

impl Default for AnalyticsSourcesPipelineMakers {
    fn default() -> Self {
        Self {
            analytics_orders_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_analytics_orders_source(context, environment, config).await })
            }),
            analytics_payments_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_analytics_payments_source(context, environment, config).await })
            }),
            analytics_shipments_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_analytics_shipments_source(context, environment, config).await })
            }),
        }
    }
}

pub struct AnalyticsSourcesPipelineFunctions {
    pub analytics_orders_source: AnalyticsOrdersSource,
    pub analytics_payments_source: AnalyticsPaymentsSource,
    pub analytics_shipments_source: AnalyticsShipmentsSource,
}

pub struct AnalyticsSourcesPipelineStreams {
    pub analytics_orders: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_payments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_shipments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub split_analytics_orders: [Stream<AnalyticsEvent>; 2],
    pub split_analytics_payments: [Stream<AnalyticsEvent>; 2],
}
macro_rules! init_analytics_sources_analytics_orders_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&$config.streams.analytics_orders, $environment.clone()));
    };
}
macro_rules! init_analytics_sources_analytics_payments_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&$config.streams.analytics_payments, $environment.clone()));
    };
}
macro_rules! init_analytics_sources_analytics_shipments_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&$config.streams.analytics_shipments, $environment.clone()));
    };
}
macro_rules! init_analytics_sources_split_analytics_orders_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr, [$($branch:ident),*]) => {
        let $variable = $source.split(&$config.streams.split_analytics_orders)?;
        let [$($branch),*] = $variable.clone();
        $(let _ = &$branch;)*
    };
}
macro_rules! init_analytics_sources_split_analytics_payments_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr, [$($branch:ident),*]) => {
        let $variable = $source.split(&$config.streams.split_analytics_payments)?;
        let [$($branch),*] = $variable.clone();
        $(let _ = &$branch;)*
    };
}