// Code generated by servicegen. DO NOT EDIT.

use super::*;

#[derive(Clone)]
pub struct SubstreamAnalyticsPipelineMakers {
    pub build_substream_analytics_result: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<BuildSubstreamAnalyticsResult>> + Send + 'a>> + Send + Sync>,
    pub invoke_analytics_substream: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<InvokeAnalyticsSubstream>> + Send + 'a>> + Send + Sync>,
    pub substream_analytics_input_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a CustomEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<SubstreamAnalyticsInputSource>> + Send + 'a>> + Send + Sync>,
    pub substream_analytics_result_sink: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a CustomEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<SubstreamAnalyticsResultSink>> + Send + 'a>> + Send + Sync>,
}

macro_rules! init_substream_analytics_pipeline_streams {
    ($config:ident, $environment:ident, $functions:ident) => {{
        init_substream_analytics_analyze_analytics_substream_stream!($config, $environment, $functions, analyze_analytics_substream);
        init_substream_analytics_build_substream_analytics_result_stream!($config, $environment, $functions, build_substream_analytics_result, analyze_analytics_substream.stream());
        init_substream_analytics_substream_analytics_input_stream!($config, $environment, $functions, substream_analytics_input);
        init_substream_analytics_invoke_analytics_substream_stream!($config, $environment, $functions, invoke_analytics_substream, substream_analytics_input.stream());
        init_substream_analytics_write_substream_analytics_stream!($config, $environment, $functions, write_substream_analytics, invoke_analytics_substream);
        analyze_analytics_substream.set_source(&build_substream_analytics_result)?;
        Ok::<SubstreamAnalyticsPipelineStreams, RuntimeError>(SubstreamAnalyticsPipelineStreams {
            substream_analytics_input: substream_analytics_input,
            analyze_analytics_substream,
            build_substream_analytics_result,
            invoke_analytics_substream,
            write_substream_analytics,
        })
    }};
}

impl Default for SubstreamAnalyticsPipelineMakers {
    fn default() -> Self {
        Self {
            build_substream_analytics_result: Arc::new(|context, environment, config| {
                Box::pin(async move { make_build_substream_analytics_result(context, environment, config).await })
            }),
            invoke_analytics_substream: Arc::new(|context, environment, config| {
                Box::pin(async move { make_invoke_analytics_substream(context, environment, config).await })
            }),
            substream_analytics_input_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_substream_analytics_input_source(context, environment, config).await })
            }),
            substream_analytics_result_sink: Arc::new(|context, environment, config| {
                Box::pin(async move { make_substream_analytics_result_sink(context, environment, config).await })
            }),
        }
    }
}

pub struct SubstreamAnalyticsPipelineFunctions {
    pub build_substream_analytics_result: BuildSubstreamAnalyticsResult,
    pub invoke_analytics_substream: InvokeAnalyticsSubstream,
    pub substream_analytics_input_source: SubstreamAnalyticsInputSource,
    pub substream_analytics_result_sink: SubstreamAnalyticsResultSink,
}

pub struct SubstreamAnalyticsPipelineStreams {
    pub substream_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analyze_analytics_substream: Arc<SubStream<AnalyticsEvent, AnalyticsResult>>,
    pub build_substream_analytics_result: Stream<AnalyticsResult>,
    pub invoke_analytics_substream: Stream<AnalyticsResult>,
    pub write_substream_analytics: Arc<SinkStream<AnalyticsResult, String>>,
}
macro_rules! init_substream_analytics_analyze_analytics_substream_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(SubStream::<AnalyticsEvent, AnalyticsResult>::new(&$config.streams.analyze_analytics_substream, $environment.clone()));
    };
}
macro_rules! init_substream_analytics_build_substream_analytics_result_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.build_substream_analytics_result, $functions.substream_analytics.build_substream_analytics_result)?;
    };
}
macro_rules! init_substream_analytics_substream_analytics_input_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&$config.streams.substream_analytics_input, $environment.clone()));
    };
}
macro_rules! init_substream_analytics_invoke_analytics_substream_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.invoke_analytics_substream, $functions.substream_analytics.invoke_analytics_substream)?;
    };
}
macro_rules! init_substream_analytics_write_substream_analytics_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.sink::<String>(&$config.streams.write_substream_analytics)?;
    };
}