// Code generated by servicegen. DO NOT EDIT.
#![allow(unused_imports, unused_variables)]

use std::{any::TypeId, sync::Arc};
use servicelib::runtime::{
    environment::{RuntimeEnvironment, RuntimeResult},
    serde::{ArraySerde, MapSerde, Serializer},
};
use super::imports::*;

pub fn get_serde(value_type: TypeId, environment: &RuntimeEnvironment) -> RuntimeResult<Option<Serializer>> {
    if let Some(serde) = super::custom_serde::get_custom_serde(value_type, environment)? {
        return Ok(Some(serde));
    }
    if let Some(serde) = get_serde_part_0(value_type, environment)? {
        return Ok(Some(serde));
    }
    Ok(None)
}


#[inline(never)]
fn get_serde_part_0(value_type: TypeId, environment: &RuntimeEnvironment) -> RuntimeResult<Option<Serializer>> {
    if value_type == TypeId::of::<AnalyticsEvent>() {
        let serde = crate::internal::serdes::AnalyticsEventSerde::new();
        return Ok(Some(Serializer::new::<AnalyticsEvent>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<AnalyticsResult>() {
        let serde = crate::internal::serdes::AnalyticsResultSerde::new();
        return Ok(Some(Serializer::new::<AnalyticsResult>(Arc::new(serde))));
    }
    if value_type == TypeId::of::<OrderProcessed>() {
        let serde = example_model::serdes::OrderProcessedSerde::new();
        return Ok(Some(Serializer::new::<OrderProcessed>(Arc::new(serde))));
    }
    Ok(None)
}