// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::service_generated::GeneratedService;




pub struct ServiceServers;

impl ServiceServers {
    pub fn register(app: &mut ServiceApp, service: GeneratedService) -> RuntimeResult<()> {
        let _ = (&app, &service);
        Ok(())
    }
}