// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::functions_generated::ServiceFunctions;
use servicelib::operators::{case, delay, error, filter, flatmap, flatmapiterable, input, join, keyby, link, map, merge, multijoin, process, sink, split, substream};

pub struct GeneratedSharedCaseFunction<F>(pub Arc<F>);

impl<T, F> servicelib::operators::case::BuildSwitchFunction<T> for GeneratedSharedCaseFunction<F>
where
    F: servicelib::operators::case::BuildSwitchFunction<T>,
{
    fn select(&self, value: &T) -> usize {
        servicelib::operators::case::BuildSwitchFunction::select(self.0.as_ref(), value)
    }
}

pub struct ServiceStreams {
    pub analytics_schedule: Arc<InputStream<String, (), String>>,
    pub consume_order_processed: Arc<InputStream<OrderProcessed, OrderProcessed, String>>,
    pub analytics_orders: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_payments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_shipments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub cycle_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub substream_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub cycle_analytics_link: Arc<LinkStream<AnalyticsEvent>>,
    pub count_order_processed: Stream<OrderProcessed>,
    pub split_analytics_orders: [Stream<AnalyticsEvent>; 2],
    pub split_analytics_payments: [Stream<AnalyticsEvent>; 2],
    pub merge_cycle_analytics: Stream<AnalyticsEvent>,
    pub advance_cycle_analytics: Stream<AnalyticsEvent>,
    pub split_cycle_analytics: [Stream<AnalyticsEvent>; 2],
    pub complete_cycle_analytics: Stream<AnalyticsEvent>,
    pub continue_cycle_analytics: Stream<AnalyticsEvent>,
    pub write_cycle_analytics: Arc<SinkStream<AnalyticsEvent, String>>,
    pub key_orders_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_payments_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub join_order_payment_analytics: Stream<AnalyticsResult>,
    pub write_joined_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub key_orders_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_payments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_shipments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub multi_join_analytics_events: Arc<MultiJoinStream<String, AnalyticsResult, Arc<MultiJoinAnalyticsEvents>>>,
    pub route_analytics_result: TypedCaseStream<AnalyticsResult, GeneratedSharedCaseFunction<RouteAnalyticsResult>>,
    pub high_value_analytics: Stream<AnalyticsResult>,
    pub standard_analytics: Stream<AnalyticsResult>,
    pub write_high_value_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub write_standard_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub analyze_analytics_substream: Arc<SubStream<AnalyticsEvent, AnalyticsResult>>,
    pub build_substream_analytics_result: Stream<AnalyticsResult>,
    pub invoke_analytics_substream: Stream<AnalyticsResult>,
    pub write_substream_analytics: Arc<SinkStream<AnalyticsResult, String>>,
}

// Partial state exists only while the graph is being constructed.
#[derive(Default)]
struct ServiceStreamsBuilder {
    analytics_schedule: Option<Arc<InputStream<String, (), String>>>,
    consume_order_processed: Option<Arc<InputStream<OrderProcessed, OrderProcessed, String>>>,
    analytics_orders: Option<Arc<InputStream<AnalyticsEvent, (), String>>>,
    analytics_payments: Option<Arc<InputStream<AnalyticsEvent, (), String>>>,
    analytics_shipments: Option<Arc<InputStream<AnalyticsEvent, (), String>>>,
    cycle_analytics_input: Option<Arc<InputStream<AnalyticsEvent, (), String>>>,
    substream_analytics_input: Option<Arc<InputStream<AnalyticsEvent, (), String>>>,
    cycle_analytics_link: Option<Arc<LinkStream<AnalyticsEvent>>>,
    count_order_processed: Option<Stream<OrderProcessed>>,
    split_analytics_orders: Option<[Stream<AnalyticsEvent>; 2]>,
    split_analytics_payments: Option<[Stream<AnalyticsEvent>; 2]>,
    merge_cycle_analytics: Option<Stream<AnalyticsEvent>>,
    advance_cycle_analytics: Option<Stream<AnalyticsEvent>>,
    split_cycle_analytics: Option<[Stream<AnalyticsEvent>; 2]>,
    complete_cycle_analytics: Option<Stream<AnalyticsEvent>>,
    continue_cycle_analytics: Option<Stream<AnalyticsEvent>>,
    write_cycle_analytics: Option<Arc<SinkStream<AnalyticsEvent, String>>>,
    key_orders_for_join: Option<Stream<KeyValue<String, AnalyticsEvent>>>,
    key_payments_for_join: Option<Stream<KeyValue<String, AnalyticsEvent>>>,
    join_order_payment_analytics: Option<Stream<AnalyticsResult>>,
    write_joined_analytics: Option<Arc<SinkStream<AnalyticsResult, String>>>,
    key_orders_for_multi_join: Option<Stream<KeyValue<String, AnalyticsEvent>>>,
    key_payments_for_multi_join: Option<Stream<KeyValue<String, AnalyticsEvent>>>,
    key_shipments_for_multi_join: Option<Stream<KeyValue<String, AnalyticsEvent>>>,
    multi_join_analytics_events: Option<Arc<MultiJoinStream<String, AnalyticsResult, Arc<MultiJoinAnalyticsEvents>>>>,
    route_analytics_result: Option<TypedCaseStream<AnalyticsResult, GeneratedSharedCaseFunction<RouteAnalyticsResult>>>,
    high_value_analytics: Option<Stream<AnalyticsResult>>,
    standard_analytics: Option<Stream<AnalyticsResult>>,
    write_high_value_analytics: Option<Arc<SinkStream<AnalyticsResult, String>>>,
    write_standard_analytics: Option<Arc<SinkStream<AnalyticsResult, String>>>,
    analyze_analytics_substream: Option<Arc<SubStream<AnalyticsEvent, AnalyticsResult>>>,
    build_substream_analytics_result: Option<Stream<AnalyticsResult>>,
    invoke_analytics_substream: Option<Stream<AnalyticsResult>>,
    write_substream_analytics: Option<Arc<SinkStream<AnalyticsResult, String>>>,
}

#[inline(never)]
fn stream_builder_ref<'a, T>(value: &'a Option<T>, name: &str) -> RuntimeResult<&'a T> {
    value.as_ref().ok_or_else(|| RuntimeError::InvalidConfiguration(
        format!("stream {name} is required before it has been initialized"),
    ))
}

#[inline(never)]
fn stream_builder_take<T>(value: &mut Option<T>, name: &str) -> RuntimeResult<T> {
    value.take().ok_or_else(|| RuntimeError::InvalidConfiguration(
        format!("stream {name} was not initialized"),
    ))
}


struct StreamCompletionPart0 {
    analytics_schedule: Arc<InputStream<String, (), String>>,
    consume_order_processed: Arc<InputStream<OrderProcessed, OrderProcessed, String>>,
    analytics_orders: Arc<InputStream<AnalyticsEvent, (), String>>,
    analytics_payments: Arc<InputStream<AnalyticsEvent, (), String>>,
    analytics_shipments: Arc<InputStream<AnalyticsEvent, (), String>>,
    cycle_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    substream_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    cycle_analytics_link: Arc<LinkStream<AnalyticsEvent>>,
    count_order_processed: Stream<OrderProcessed>,
    split_analytics_orders: [Stream<AnalyticsEvent>; 2],
    split_analytics_payments: [Stream<AnalyticsEvent>; 2],
    merge_cycle_analytics: Stream<AnalyticsEvent>,
    advance_cycle_analytics: Stream<AnalyticsEvent>,
    split_cycle_analytics: [Stream<AnalyticsEvent>; 2],
    complete_cycle_analytics: Stream<AnalyticsEvent>,
    continue_cycle_analytics: Stream<AnalyticsEvent>,
    write_cycle_analytics: Arc<SinkStream<AnalyticsEvent, String>>,
    key_orders_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    key_payments_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    join_order_payment_analytics: Stream<AnalyticsResult>,
    write_joined_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    key_orders_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    key_payments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    key_shipments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    multi_join_analytics_events: Arc<MultiJoinStream<String, AnalyticsResult, Arc<MultiJoinAnalyticsEvents>>>,
    route_analytics_result: TypedCaseStream<AnalyticsResult, GeneratedSharedCaseFunction<RouteAnalyticsResult>>,
    high_value_analytics: Stream<AnalyticsResult>,
    standard_analytics: Stream<AnalyticsResult>,
    write_high_value_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    write_standard_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    analyze_analytics_substream: Arc<SubStream<AnalyticsEvent, AnalyticsResult>>,
    build_substream_analytics_result: Stream<AnalyticsResult>,
}

struct StreamCompletionPart1 {
    invoke_analytics_substream: Stream<AnalyticsResult>,
    write_substream_analytics: Arc<SinkStream<AnalyticsResult, String>>,
}


impl ServiceStreams {
    #[inline(never)]
    pub fn init_streams(
        config: &Config,
        environment: &RuntimeEnvironment,
        functions: &ServiceFunctions,
    ) -> RuntimeResult<Self> {
        let _ = (config, environment, functions);
        let mut builder = ServiceStreamsBuilder::default();
        builder.init_part_0(config, environment, functions)?;
        builder.init_part_1(config, environment, functions)?;
        builder.connect_part_0(config, functions)?;
        builder.connect_part_1(config, functions)?;
        let streams = builder.finish()?;
        streams.build()?;
        Ok(streams)
    }

    pub fn build(&self) -> RuntimeResult<()> {
        Ok(())
    }

}

impl ServiceStreamsBuilder {

    #[inline(never)]
    fn init_part_0(
        &mut self,
        config: &Config,
        environment: &RuntimeEnvironment,
        functions: &ServiceFunctions,
    ) -> RuntimeResult<()> {
        let _ = (config, environment, functions);
        self.cycle_analytics_link = Some(
            link::create(&config.streams.cycle_analytics_link, environment.clone())
        );
        self.analytics_schedule = Some(
            input::create(&config.streams.analytics_schedule, environment.clone())
        );
        self.consume_order_processed = Some(
            input::create(&config.streams.consume_order_processed, environment.clone())
        );
        self.count_order_processed = Some(
            process::create(&config.streams.count_order_processed, environment.clone())
        );
        self.analytics_orders = Some(
            input::create(&config.streams.analytics_orders, environment.clone())
        );
        self.analytics_payments = Some(
            input::create(&config.streams.analytics_payments, environment.clone())
        );
        self.analytics_shipments = Some(
            input::create(&config.streams.analytics_shipments, environment.clone())
        );
        self.split_analytics_orders = Some(
            split::create(&config.streams.split_analytics_orders, &(*stream_builder_ref(&self.analytics_orders, "analytics_orders")?).stream())
        );
        self.split_analytics_payments = Some(
            split::create(&config.streams.split_analytics_payments, &(*stream_builder_ref(&self.analytics_payments, "analytics_payments")?).stream())
        );
        self.cycle_analytics_input = Some(
            input::create(&config.streams.cycle_analytics_input, environment.clone())
        );
        self.merge_cycle_analytics = Some(
            merge::create(&config.streams.merge_cycle_analytics, &(*stream_builder_ref(&self.cycle_analytics_input, "cycle_analytics_input")?).stream())
        );
        self.advance_cycle_analytics = Some(
            map::create(&config.streams.advance_cycle_analytics, environment.clone())
        );
        self.split_cycle_analytics = Some(
            split::create(&config.streams.split_cycle_analytics, &(*stream_builder_ref(&self.advance_cycle_analytics, "advance_cycle_analytics")?))
        );
        self.complete_cycle_analytics = Some(
            filter::create(&config.streams.complete_cycle_analytics, &(*stream_builder_ref(&self.split_cycle_analytics, "split_cycle_analytics")?)[0])
        );
        self.continue_cycle_analytics = Some(
            filter::create(&config.streams.continue_cycle_analytics, &(*stream_builder_ref(&self.split_cycle_analytics, "split_cycle_analytics")?)[1])
        );
        self.write_cycle_analytics = Some(
            sink::create(&config.streams.write_cycle_analytics, environment.clone())?
        );
        self.key_orders_for_join = Some(
            keyby::create(&config.streams.key_orders_for_join, environment.clone())
        );
        self.key_payments_for_join = Some(
            keyby::create(&config.streams.key_payments_for_join, environment.clone())
        );
        self.join_order_payment_analytics = Some(
            join::create(&config.streams.join_order_payment_analytics, environment.clone())
        );
        self.write_joined_analytics = Some(
            sink::create(&config.streams.write_joined_analytics, environment.clone())?
        );
        self.key_orders_for_multi_join = Some(
            keyby::create(&config.streams.key_orders_for_multi_join, environment.clone())
        );
        self.key_payments_for_multi_join = Some(
            keyby::create(&config.streams.key_payments_for_multi_join, environment.clone())
        );
        self.key_shipments_for_multi_join = Some(
            keyby::create(&config.streams.key_shipments_for_multi_join, environment.clone())
        );
        self.multi_join_analytics_events = Some(
            multijoin::create(&config.streams.multi_join_analytics_events, environment.clone(), functions.multi_join_analytics_events.clone())?
        );
        self.route_analytics_result = Some(
            case::create(&config.streams.route_analytics_result, &(*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?).stream().clone(), GeneratedSharedCaseFunction(
                functions.route_analytics_result.clone(),
            ))
        );
        self.high_value_analytics = Some(
            case::when(&config.streams.high_value_analytics, &(*stream_builder_ref(&self.route_analytics_result, "route_analytics_result")?))
        );
        self.standard_analytics = Some(
            case::when(&config.streams.standard_analytics, &(*stream_builder_ref(&self.route_analytics_result, "route_analytics_result")?))
        );
        self.write_high_value_analytics = Some(
            sink::create(&config.streams.write_high_value_analytics, environment.clone())?
        );
        self.write_standard_analytics = Some(
            sink::create(&config.streams.write_standard_analytics, environment.clone())?
        );
        self.analyze_analytics_substream = Some(
            substream::create(&config.streams.analyze_analytics_substream, environment.clone())
        );
        self.build_substream_analytics_result = Some(
            map::create(&config.streams.build_substream_analytics_result, environment.clone())
        );
        self.substream_analytics_input = Some(
            input::create(&config.streams.substream_analytics_input, environment.clone())
        );
        Ok(())
    }

    #[inline(never)]
    fn connect_part_0(&self, config: &Config, functions: &ServiceFunctions) -> RuntimeResult<()> {
        let _ = (config, functions);
        let _collector_bound_consume_order_processed = (*stream_builder_ref(&self.consume_order_processed, "consume_order_processed")?).set_source_typed(&(*stream_builder_ref(&self.count_order_processed, "count_order_processed")?))?;
        let _collector_bound_cycle_analytics_link = (*stream_builder_ref(&self.cycle_analytics_link, "cycle_analytics_link")?).set_source_typed(&(*stream_builder_ref(&self.continue_cycle_analytics, "continue_cycle_analytics")?))?;
        let _collector_bound_analyze_analytics_substream = (*stream_builder_ref(&self.analyze_analytics_substream, "analyze_analytics_substream")?).set_source_typed(&(*stream_builder_ref(&self.build_substream_analytics_result, "build_substream_analytics_result")?))?;
        let operator_build_substream_analytics_result = Arc::new(servicelib::operators::map::MapStream::from_collector(_collector_bound_analyze_analytics_substream.clone(), functions.build_substream_analytics_result.clone()));
        let _collector_build_substream_analytics_result = (*stream_builder_ref(&self.analyze_analytics_substream, "analyze_analytics_substream")?).stream().try_set_typed_consumer(Arc::clone(&operator_build_substream_analytics_result), config.streams.build_substream_analytics_result.stream.id)?;
        let operator_write_standard_analytics = Arc::clone(&(*stream_builder_ref(&self.write_standard_analytics, "write_standard_analytics")?));
        let _collector_write_standard_analytics = (*stream_builder_ref(&self.standard_analytics, "standard_analytics")?).try_set_typed_consumer(Arc::clone(&operator_write_standard_analytics), config.streams.write_standard_analytics.stream.id)?;
        let operator_write_high_value_analytics = Arc::clone(&(*stream_builder_ref(&self.write_high_value_analytics, "write_high_value_analytics")?));
        let _collector_write_high_value_analytics = (*stream_builder_ref(&self.high_value_analytics, "high_value_analytics")?).try_set_typed_consumer(Arc::clone(&operator_write_high_value_analytics), config.streams.write_high_value_analytics.stream.id)?;
        let operator_route_analytics_result = (*stream_builder_ref(&self.route_analytics_result, "route_analytics_result")?).from_branches((_collector_write_high_value_analytics.clone(), (_collector_write_standard_analytics.clone(), ())))?;
        let _collector_route_analytics_result = (*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?).stream().clone().try_set_typed_consumer(Arc::clone(&operator_route_analytics_result), config.streams.route_analytics_result.stream.id)?;
        let operator_multi_join_analytics_events = Arc::clone(&(*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?));
        let _collector_multi_join_analytics_events_0 = operator_multi_join_analytics_events.connect_left(&(*stream_builder_ref(&self.key_orders_for_multi_join, "key_orders_for_multi_join")?), (*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?).stream().collector())?;
        let _collector_multi_join_analytics_events_1 = operator_multi_join_analytics_events.add_with_collector(&(*stream_builder_ref(&self.key_payments_for_multi_join, "key_payments_for_multi_join")?), (*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?).stream().collector())?;
        let _collector_multi_join_analytics_events_2 = operator_multi_join_analytics_events.add_with_collector(&(*stream_builder_ref(&self.key_shipments_for_multi_join, "key_shipments_for_multi_join")?), (*stream_builder_ref(&self.multi_join_analytics_events, "multi_join_analytics_events")?).stream().collector())?;
        let operator_key_shipments_for_multi_join = Arc::new(servicelib::operators::keyby::KeyByStream::from_collector(_collector_multi_join_analytics_events_2.clone(), functions.key_shipments_for_multi_join.clone()));
        let _collector_key_shipments_for_multi_join = (*stream_builder_ref(&self.analytics_shipments, "analytics_shipments")?).stream().try_set_typed_consumer(Arc::clone(&operator_key_shipments_for_multi_join), config.streams.key_shipments_for_multi_join.stream.id)?;
        let operator_key_payments_for_multi_join = Arc::new(servicelib::operators::keyby::KeyByStream::from_collector(_collector_multi_join_analytics_events_1.clone(), functions.key_payments_for_multi_join.clone()));
        let _collector_key_payments_for_multi_join = (*stream_builder_ref(&self.split_analytics_payments, "split_analytics_payments")?)[1].try_set_typed_consumer(Arc::clone(&operator_key_payments_for_multi_join), config.streams.key_payments_for_multi_join.stream.id)?;
        let operator_key_orders_for_multi_join = Arc::new(servicelib::operators::keyby::KeyByStream::from_collector(_collector_multi_join_analytics_events_0.clone(), functions.key_orders_for_multi_join.clone()));
        let _collector_key_orders_for_multi_join = (*stream_builder_ref(&self.split_analytics_orders, "split_analytics_orders")?)[1].try_set_typed_consumer(Arc::clone(&operator_key_orders_for_multi_join), config.streams.key_orders_for_multi_join.stream.id)?;
        let operator_write_joined_analytics = Arc::clone(&(*stream_builder_ref(&self.write_joined_analytics, "write_joined_analytics")?));
        let _collector_write_joined_analytics = (*stream_builder_ref(&self.join_order_payment_analytics, "join_order_payment_analytics")?).try_set_typed_consumer(Arc::clone(&operator_write_joined_analytics), config.streams.write_joined_analytics.stream.id)?;
        let operator_join_order_payment_analytics = servicelib::operators::join::JoinStream::from_collector(&config.streams.join_order_payment_analytics, _collector_write_joined_analytics.clone(), functions.join_order_payment_analytics.clone())?;
        let _collector_join_order_payment_analytics_0 = (*stream_builder_ref(&self.key_orders_for_join, "key_orders_for_join")?).try_set_typed_consumer(Arc::clone(&operator_join_order_payment_analytics), config.streams.join_order_payment_analytics.stream.id)?;
        let _collector_join_order_payment_analytics_1 = (*stream_builder_ref(&self.key_payments_for_join, "key_payments_for_join")?).try_set_typed_consumer(Arc::new(operator_join_order_payment_analytics.right()), config.streams.join_order_payment_analytics.stream.id)?;
        let operator_key_payments_for_join = Arc::new(servicelib::operators::keyby::KeyByStream::from_collector(_collector_join_order_payment_analytics_1.clone(), functions.key_payments_for_join.clone()));
        let _collector_key_payments_for_join = (*stream_builder_ref(&self.split_analytics_payments, "split_analytics_payments")?)[0].try_set_typed_consumer(Arc::clone(&operator_key_payments_for_join), config.streams.key_payments_for_join.stream.id)?;
        let operator_key_orders_for_join = Arc::new(servicelib::operators::keyby::KeyByStream::from_collector(_collector_join_order_payment_analytics_0.clone(), functions.key_orders_for_join.clone()));
        let _collector_key_orders_for_join = (*stream_builder_ref(&self.split_analytics_orders, "split_analytics_orders")?)[0].try_set_typed_consumer(Arc::clone(&operator_key_orders_for_join), config.streams.key_orders_for_join.stream.id)?;
        let operator_write_cycle_analytics = Arc::clone(&(*stream_builder_ref(&self.write_cycle_analytics, "write_cycle_analytics")?));
        let _collector_write_cycle_analytics = (*stream_builder_ref(&self.complete_cycle_analytics, "complete_cycle_analytics")?).try_set_typed_consumer(Arc::clone(&operator_write_cycle_analytics), config.streams.write_cycle_analytics.stream.id)?;
        let operator_continue_cycle_analytics = Arc::new(servicelib::operators::filter::FilterStream::from_collector(_collector_bound_cycle_analytics_link.clone(), functions.continue_cycle_analytics.clone()));
        let _collector_continue_cycle_analytics = (*stream_builder_ref(&self.split_cycle_analytics, "split_cycle_analytics")?)[1].try_set_typed_consumer(Arc::clone(&operator_continue_cycle_analytics), config.streams.continue_cycle_analytics.stream.id)?;
        let operator_complete_cycle_analytics = Arc::new(servicelib::operators::filter::FilterStream::from_collector(_collector_write_cycle_analytics.clone(), functions.complete_cycle_analytics.clone()));
        let _collector_complete_cycle_analytics = (*stream_builder_ref(&self.split_cycle_analytics, "split_cycle_analytics")?)[0].try_set_typed_consumer(Arc::clone(&operator_complete_cycle_analytics), config.streams.complete_cycle_analytics.stream.id)?;
        let operator_split_cycle_analytics = servicelib::operators::split::SplitStream::<_, 2>::from_typed(&config.streams.split_cycle_analytics, &(*stream_builder_ref(&self.advance_cycle_analytics, "advance_cycle_analytics")?), (_collector_complete_cycle_analytics.clone(), (_collector_continue_cycle_analytics.clone(), ())))?;
        let _collector_split_cycle_analytics = (*stream_builder_ref(&self.advance_cycle_analytics, "advance_cycle_analytics")?).try_set_typed_consumer(Arc::clone(&operator_split_cycle_analytics), config.streams.split_cycle_analytics.stream.id)?;
        let operator_advance_cycle_analytics = Arc::new(servicelib::operators::map::MapStream::from_collector(_collector_split_cycle_analytics.clone(), functions.advance_cycle_analytics.clone()));
        let _collector_advance_cycle_analytics = (*stream_builder_ref(&self.merge_cycle_analytics, "merge_cycle_analytics")?).try_set_typed_consumer(Arc::clone(&operator_advance_cycle_analytics), config.streams.advance_cycle_analytics.stream.id)?;
        let operator_merge_cycle_analytics = Arc::new(servicelib::operators::merge::MergeStream::from_collector(_collector_advance_cycle_analytics.clone()));
        let _collector_merge_cycle_analytics_0 = (*stream_builder_ref(&self.cycle_analytics_input, "cycle_analytics_input")?).stream().try_set_typed_consumer(Arc::clone(&operator_merge_cycle_analytics), config.streams.merge_cycle_analytics.stream.id)?;
        let _collector_merge_cycle_analytics_1 = (*stream_builder_ref(&self.cycle_analytics_link, "cycle_analytics_link")?).stream().try_set_typed_consumer(Arc::clone(&operator_merge_cycle_analytics), config.streams.merge_cycle_analytics.stream.id)?;
        let operator_split_analytics_payments = servicelib::operators::split::SplitStream::<_, 2>::from_typed(&config.streams.split_analytics_payments, &(*stream_builder_ref(&self.analytics_payments, "analytics_payments")?).stream(), (_collector_key_payments_for_join.clone(), (_collector_key_payments_for_multi_join.clone(), ())))?;
        let _collector_split_analytics_payments = (*stream_builder_ref(&self.analytics_payments, "analytics_payments")?).stream().try_set_typed_consumer(Arc::clone(&operator_split_analytics_payments), config.streams.split_analytics_payments.stream.id)?;
        let operator_split_analytics_orders = servicelib::operators::split::SplitStream::<_, 2>::from_typed(&config.streams.split_analytics_orders, &(*stream_builder_ref(&self.analytics_orders, "analytics_orders")?).stream(), (_collector_key_orders_for_join.clone(), (_collector_key_orders_for_multi_join.clone(), ())))?;
        let _collector_split_analytics_orders = (*stream_builder_ref(&self.analytics_orders, "analytics_orders")?).stream().try_set_typed_consumer(Arc::clone(&operator_split_analytics_orders), config.streams.split_analytics_orders.stream.id)?;
        let operator_count_order_processed = Arc::new(servicelib::operators::process::ProcessStream::from_collectors(_collector_bound_consume_order_processed.clone(), servicelib::operators::error::ErrorStream::new(&config.streams.count_order_processed.stream, (*stream_builder_ref(&self.count_order_processed, "count_order_processed")?).environment().clone()).stream().collector(), functions.count_order_processed.clone()));
        let _collector_count_order_processed = (*stream_builder_ref(&self.consume_order_processed, "consume_order_processed")?).stream().try_set_typed_consumer(Arc::clone(&operator_count_order_processed), config.streams.count_order_processed.stream.id)?;
        Ok(())
    }

    #[inline(never)]
    fn init_part_1(
        &mut self,
        config: &Config,
        environment: &RuntimeEnvironment,
        functions: &ServiceFunctions,
    ) -> RuntimeResult<()> {
        let _ = (config, environment, functions);
        self.invoke_analytics_substream = Some(
            map::create(&config.streams.invoke_analytics_substream, environment.clone())
        );
        self.write_substream_analytics = Some(
            sink::create(&config.streams.write_substream_analytics, environment.clone())?
        );
        Ok(())
    }

    #[inline(never)]
    fn connect_part_1(&self, config: &Config, functions: &ServiceFunctions) -> RuntimeResult<()> {
        let _ = (config, functions);
        let operator_write_substream_analytics = Arc::clone(&(*stream_builder_ref(&self.write_substream_analytics, "write_substream_analytics")?));
        let _collector_write_substream_analytics = (*stream_builder_ref(&self.invoke_analytics_substream, "invoke_analytics_substream")?).try_set_typed_consumer(Arc::clone(&operator_write_substream_analytics), config.streams.write_substream_analytics.stream.id)?;
        let operator_invoke_analytics_substream = Arc::new(servicelib::operators::map::MapStream::from_collector(_collector_write_substream_analytics.clone(), functions.invoke_analytics_substream.clone()));
        let _collector_invoke_analytics_substream = (*stream_builder_ref(&self.substream_analytics_input, "substream_analytics_input")?).stream().try_set_typed_consumer(Arc::clone(&operator_invoke_analytics_substream), config.streams.invoke_analytics_substream.stream.id)?;
        Ok(())
    }


    #[inline(never)]
    fn complete_part_0(&mut self) -> RuntimeResult<StreamCompletionPart0> {
        Ok(StreamCompletionPart0 {
            analytics_schedule: stream_builder_take(&mut self.analytics_schedule, "analytics_schedule")?,
            consume_order_processed: stream_builder_take(&mut self.consume_order_processed, "consume_order_processed")?,
            analytics_orders: stream_builder_take(&mut self.analytics_orders, "analytics_orders")?,
            analytics_payments: stream_builder_take(&mut self.analytics_payments, "analytics_payments")?,
            analytics_shipments: stream_builder_take(&mut self.analytics_shipments, "analytics_shipments")?,
            cycle_analytics_input: stream_builder_take(&mut self.cycle_analytics_input, "cycle_analytics_input")?,
            substream_analytics_input: stream_builder_take(&mut self.substream_analytics_input, "substream_analytics_input")?,
            cycle_analytics_link: stream_builder_take(&mut self.cycle_analytics_link, "cycle_analytics_link")?,
            count_order_processed: stream_builder_take(&mut self.count_order_processed, "count_order_processed")?,
            split_analytics_orders: stream_builder_take(&mut self.split_analytics_orders, "split_analytics_orders")?,
            split_analytics_payments: stream_builder_take(&mut self.split_analytics_payments, "split_analytics_payments")?,
            merge_cycle_analytics: stream_builder_take(&mut self.merge_cycle_analytics, "merge_cycle_analytics")?,
            advance_cycle_analytics: stream_builder_take(&mut self.advance_cycle_analytics, "advance_cycle_analytics")?,
            split_cycle_analytics: stream_builder_take(&mut self.split_cycle_analytics, "split_cycle_analytics")?,
            complete_cycle_analytics: stream_builder_take(&mut self.complete_cycle_analytics, "complete_cycle_analytics")?,
            continue_cycle_analytics: stream_builder_take(&mut self.continue_cycle_analytics, "continue_cycle_analytics")?,
            write_cycle_analytics: stream_builder_take(&mut self.write_cycle_analytics, "write_cycle_analytics")?,
            key_orders_for_join: stream_builder_take(&mut self.key_orders_for_join, "key_orders_for_join")?,
            key_payments_for_join: stream_builder_take(&mut self.key_payments_for_join, "key_payments_for_join")?,
            join_order_payment_analytics: stream_builder_take(&mut self.join_order_payment_analytics, "join_order_payment_analytics")?,
            write_joined_analytics: stream_builder_take(&mut self.write_joined_analytics, "write_joined_analytics")?,
            key_orders_for_multi_join: stream_builder_take(&mut self.key_orders_for_multi_join, "key_orders_for_multi_join")?,
            key_payments_for_multi_join: stream_builder_take(&mut self.key_payments_for_multi_join, "key_payments_for_multi_join")?,
            key_shipments_for_multi_join: stream_builder_take(&mut self.key_shipments_for_multi_join, "key_shipments_for_multi_join")?,
            multi_join_analytics_events: stream_builder_take(&mut self.multi_join_analytics_events, "multi_join_analytics_events")?,
            route_analytics_result: stream_builder_take(&mut self.route_analytics_result, "route_analytics_result")?,
            high_value_analytics: stream_builder_take(&mut self.high_value_analytics, "high_value_analytics")?,
            standard_analytics: stream_builder_take(&mut self.standard_analytics, "standard_analytics")?,
            write_high_value_analytics: stream_builder_take(&mut self.write_high_value_analytics, "write_high_value_analytics")?,
            write_standard_analytics: stream_builder_take(&mut self.write_standard_analytics, "write_standard_analytics")?,
            analyze_analytics_substream: stream_builder_take(&mut self.analyze_analytics_substream, "analyze_analytics_substream")?,
            build_substream_analytics_result: stream_builder_take(&mut self.build_substream_analytics_result, "build_substream_analytics_result")?,
        })
    }

    #[inline(never)]
    fn complete_part_1(&mut self) -> RuntimeResult<StreamCompletionPart1> {
        Ok(StreamCompletionPart1 {
            invoke_analytics_substream: stream_builder_take(&mut self.invoke_analytics_substream, "invoke_analytics_substream")?,
            write_substream_analytics: stream_builder_take(&mut self.write_substream_analytics, "write_substream_analytics")?,
        })
    }

    #[inline(never)]
    fn finish(mut self) -> RuntimeResult<ServiceStreams> {
        let part_0 = self.complete_part_0()?;
        let part_1 = self.complete_part_1()?;
        Ok(ServiceStreams {
            analytics_schedule: part_0.analytics_schedule,
            consume_order_processed: part_0.consume_order_processed,
            analytics_orders: part_0.analytics_orders,
            analytics_payments: part_0.analytics_payments,
            analytics_shipments: part_0.analytics_shipments,
            cycle_analytics_input: part_0.cycle_analytics_input,
            substream_analytics_input: part_0.substream_analytics_input,
            cycle_analytics_link: part_0.cycle_analytics_link,
            count_order_processed: part_0.count_order_processed,
            split_analytics_orders: part_0.split_analytics_orders,
            split_analytics_payments: part_0.split_analytics_payments,
            merge_cycle_analytics: part_0.merge_cycle_analytics,
            advance_cycle_analytics: part_0.advance_cycle_analytics,
            split_cycle_analytics: part_0.split_cycle_analytics,
            complete_cycle_analytics: part_0.complete_cycle_analytics,
            continue_cycle_analytics: part_0.continue_cycle_analytics,
            write_cycle_analytics: part_0.write_cycle_analytics,
            key_orders_for_join: part_0.key_orders_for_join,
            key_payments_for_join: part_0.key_payments_for_join,
            join_order_payment_analytics: part_0.join_order_payment_analytics,
            write_joined_analytics: part_0.write_joined_analytics,
            key_orders_for_multi_join: part_0.key_orders_for_multi_join,
            key_payments_for_multi_join: part_0.key_payments_for_multi_join,
            key_shipments_for_multi_join: part_0.key_shipments_for_multi_join,
            multi_join_analytics_events: part_0.multi_join_analytics_events,
            route_analytics_result: part_0.route_analytics_result,
            high_value_analytics: part_0.high_value_analytics,
            standard_analytics: part_0.standard_analytics,
            write_high_value_analytics: part_0.write_high_value_analytics,
            write_standard_analytics: part_0.write_standard_analytics,
            analyze_analytics_substream: part_0.analyze_analytics_substream,
            build_substream_analytics_result: part_0.build_substream_analytics_result,
            invoke_analytics_substream: part_1.invoke_analytics_substream,
            write_substream_analytics: part_1.write_substream_analytics,
        })
    }
}