// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::functions_generated::ServiceFunctions;

pub struct GeneratedSharedCaseFunction<F>(pub Arc<F>);

impl<T, F> servicelib::operators::case::BuildSwitchFunction<T> for GeneratedSharedCaseFunction<F>
where
    F: servicelib::operators::case::BuildSwitchFunction<T>,
{
    fn select(&self, value: &T) -> usize {
        servicelib::operators::case::BuildSwitchFunction::select(self.0.as_ref(), value)
    }
}


pub struct ServiceStreams {
    pub analytics_schedule: Arc<InputStream<String, (), String>>,
    pub consume_order_processed: Arc<InputStream<OrderProcessed, OrderProcessed, String>>,
    pub analytics_orders: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_payments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub analytics_shipments: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub cycle_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub substream_analytics_input: Arc<InputStream<AnalyticsEvent, (), String>>,
    pub cycle_analytics_link: Arc<LinkStream<AnalyticsEvent>>,
    pub count_order_processed: Stream<OrderProcessed>,
    pub split_analytics_orders: [Stream<AnalyticsEvent>; 2],
    pub split_analytics_payments: [Stream<AnalyticsEvent>; 2],
    pub merge_cycle_analytics: Stream<AnalyticsEvent>,
    pub advance_cycle_analytics: Stream<AnalyticsEvent>,
    pub split_cycle_analytics: [Stream<AnalyticsEvent>; 2],
    pub complete_cycle_analytics: Stream<AnalyticsEvent>,
    pub continue_cycle_analytics: Stream<AnalyticsEvent>,
    pub write_cycle_analytics: Arc<SinkStream<AnalyticsEvent, String>>,
    pub key_orders_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_payments_for_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub join_order_payment_analytics: Stream<AnalyticsResult>,
    pub write_joined_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub key_orders_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_payments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub key_shipments_for_multi_join: Stream<KeyValue<String, AnalyticsEvent>>,
    pub multi_join_analytics_events: Arc<MultiJoinStream<String, AnalyticsResult, Arc<MultiJoinAnalyticsEvents>>>,
    pub route_analytics_result: TypedCaseStream<AnalyticsResult, GeneratedSharedCaseFunction<RouteAnalyticsResult>>,
    pub high_value_analytics: Stream<AnalyticsResult>,
    pub standard_analytics: Stream<AnalyticsResult>,
    pub write_high_value_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub write_standard_analytics: Arc<SinkStream<AnalyticsResult, String>>,
    pub analyze_analytics_substream: Arc<SubStream<AnalyticsEvent, AnalyticsResult>>,
    pub build_substream_analytics_result: Stream<AnalyticsResult>,
    pub invoke_analytics_substream: Stream<AnalyticsResult>,
    pub write_substream_analytics: Arc<SinkStream<AnalyticsResult, String>>,
}

impl ServiceStreams {
    #[inline(never)]
    pub fn init_streams(
        config: &Config,
        environment: &RuntimeEnvironment,
        functions: &ServiceFunctions,
    ) -> RuntimeResult<Self> {
        let _ = (config, environment, functions);
    let cycle_analytics_link = LinkStream::<AnalyticsEvent>::make(&config.streams.cycle_analytics_link, environment.clone());
    let analytics_schedule = Arc::new(InputStream::<String, (), String>::new(&config.streams.analytics_schedule, environment.clone()));
    let consume_order_processed = Arc::new(InputStream::<OrderProcessed, OrderProcessed, String>::new(&config.streams.consume_order_processed, environment.clone()));
    let (count_order_processed, count_order_processed_error) = consume_order_processed.stream().process(&config.streams.count_order_processed, functions.count_order_processed.clone())?;
    let _ = &count_order_processed_error;
    let analytics_orders = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&config.streams.analytics_orders, environment.clone()));
    let analytics_payments = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&config.streams.analytics_payments, environment.clone()));
    let analytics_shipments = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&config.streams.analytics_shipments, environment.clone()));
    let split_analytics_orders = analytics_orders.stream().split(&config.streams.split_analytics_orders)?;
    let [key_orders_for_join_branch, key_orders_for_multi_join_branch] = split_analytics_orders.clone();
    let split_analytics_payments = analytics_payments.stream().split(&config.streams.split_analytics_payments)?;
    let [key_payments_for_join_branch, key_payments_for_multi_join_branch] = split_analytics_payments.clone();
    let cycle_analytics_input = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&config.streams.cycle_analytics_input, environment.clone()));
    let merge_cycle_analytics = cycle_analytics_input.stream().merge(&config.streams.merge_cycle_analytics, &[cycle_analytics_link.stream().clone()])?;
    let advance_cycle_analytics = merge_cycle_analytics.map(&config.streams.advance_cycle_analytics, functions.advance_cycle_analytics.clone())?;
    let split_cycle_analytics = advance_cycle_analytics.split(&config.streams.split_cycle_analytics)?;
    let [complete_cycle_analytics_branch, continue_cycle_analytics_branch] = split_cycle_analytics.clone();
    let complete_cycle_analytics = complete_cycle_analytics_branch.filter(&config.streams.complete_cycle_analytics, functions.complete_cycle_analytics.clone())?;
    let continue_cycle_analytics = continue_cycle_analytics_branch.filter(&config.streams.continue_cycle_analytics, functions.continue_cycle_analytics.clone())?;
    let write_cycle_analytics = complete_cycle_analytics.sink::<String>(&config.streams.write_cycle_analytics)?;
    let key_orders_for_join = key_orders_for_join_branch.key_by(&config.streams.key_orders_for_join, functions.key_orders_for_join.clone())?;
    let key_payments_for_join = key_payments_for_join_branch.key_by(&config.streams.key_payments_for_join, functions.key_payments_for_join.clone())?;
    let join_order_payment_analytics = key_orders_for_join.join(&config.streams.join_order_payment_analytics, &key_payments_for_join, functions.join_order_payment_analytics.clone())?;
    let write_joined_analytics = join_order_payment_analytics.sink::<String>(&config.streams.write_joined_analytics)?;
    let key_orders_for_multi_join = key_orders_for_multi_join_branch.key_by(&config.streams.key_orders_for_multi_join, functions.key_orders_for_multi_join.clone())?;
    let key_payments_for_multi_join = key_payments_for_multi_join_branch.key_by(&config.streams.key_payments_for_multi_join, functions.key_payments_for_multi_join.clone())?;
    let key_shipments_for_multi_join = analytics_shipments.stream().key_by(&config.streams.key_shipments_for_multi_join, functions.key_shipments_for_multi_join.clone())?;
    let multi_join_analytics_events = key_orders_for_multi_join.multi_join(&config.streams.multi_join_analytics_events, functions.multi_join_analytics_events.clone())?;
    multi_join_analytics_events.add(&key_payments_for_multi_join)?;
    multi_join_analytics_events.add(&key_shipments_for_multi_join)?;
    let route_analytics_result = multi_join_analytics_events.stream().clone().case(&config.streams.route_analytics_result, GeneratedSharedCaseFunction(
        functions.route_analytics_result.clone(),
    ))?;
    let high_value_analytics = route_analytics_result.when(&config.streams.high_value_analytics);
    let standard_analytics = route_analytics_result.when(&config.streams.standard_analytics);
    let write_high_value_analytics = high_value_analytics.sink::<String>(&config.streams.write_high_value_analytics)?;
    let write_standard_analytics = standard_analytics.sink::<String>(&config.streams.write_standard_analytics)?;
    let analyze_analytics_substream = Arc::new(SubStream::<AnalyticsEvent, AnalyticsResult>::new(&config.streams.analyze_analytics_substream, environment.clone()));
    let build_substream_analytics_result = analyze_analytics_substream.stream().map(&config.streams.build_substream_analytics_result, functions.build_substream_analytics_result.clone())?;
    let substream_analytics_input = Arc::new(InputStream::<AnalyticsEvent, (), String>::new(&config.streams.substream_analytics_input, environment.clone()));
    let invoke_analytics_substream = substream_analytics_input.stream().map(&config.streams.invoke_analytics_substream, functions.invoke_analytics_substream.clone())?;
    let write_substream_analytics = invoke_analytics_substream.sink::<String>(&config.streams.write_substream_analytics)?;

        let streams = Self {
            analytics_schedule: analytics_schedule,
            consume_order_processed: consume_order_processed,
            analytics_orders: analytics_orders,
            analytics_payments: analytics_payments,
            analytics_shipments: analytics_shipments,
            cycle_analytics_input: cycle_analytics_input,
            substream_analytics_input: substream_analytics_input,
            cycle_analytics_link,
            count_order_processed,
            split_analytics_orders,
            split_analytics_payments,
            merge_cycle_analytics,
            advance_cycle_analytics,
            split_cycle_analytics,
            complete_cycle_analytics,
            continue_cycle_analytics,
            write_cycle_analytics,
            key_orders_for_join,
            key_payments_for_join,
            join_order_payment_analytics,
            write_joined_analytics,
            key_orders_for_multi_join,
            key_payments_for_multi_join,
            key_shipments_for_multi_join,
            multi_join_analytics_events,
            route_analytics_result,
            high_value_analytics,
            standard_analytics,
            write_high_value_analytics,
            write_standard_analytics,
            analyze_analytics_substream,
            build_substream_analytics_result,
            invoke_analytics_substream,
            write_substream_analytics,
        };
        streams.build()?;
        Ok(streams)
    }

    pub fn build(&self) -> RuntimeResult<()> {
        self.consume_order_processed.set_source(&self.count_order_processed)?;
        self.cycle_analytics_link.set_source(&self.continue_cycle_analytics)?;
        self.analyze_analytics_substream.set_source(&self.build_substream_analytics_result)?;
        Ok(())
    }
}