// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use std::time::Duration;

use serde::{Deserialize, Serialize};
use super::custom::CustomConfig;
use servicelib::api::{DataType, Environment, GrpcMethodType, HTTPMethodType, JoinStorageType, JoinType, KafkaSaslMechanism, KafkaSecurityProtocol, LogLevel, ProcessPattern, ScheduleMissedRunPolicy, ScheduleOverlapPolicy, TypeDefinitionFormat};
use servicelib::runtime::config::{
    CallSemantics, Config as ServiceConfigContract, CycleLinkStreamConfig,
    DelayStreamConfig, FilterStreamConfig, FlatMapIterableStreamConfig,
    FlatMapStreamConfig, InputStreamConfig, JoinStreamConfig, KeyByStreamConfig,
    LinkConfig, MapStreamConfig, MergeStreamConfig, MultiJoinStreamConfig,
    ModuleConfig, PoolConfig, ProcessStreamConfig, RuntimeDataConnectorConfig,
    RuntimeEndpointConfig, RuntimeStreamConfig, ServiceConfig, SinkStreamConfig,
    SplitStreamConfig, StreamConfig, WhenStreamConfig, CaseStreamConfig,
    TypeConfig, HttpDataConnectorConfig, GrpcDataConnectorConfig, KafkaDataConnectorConfig,
    CronDataConnectorConfig,
    CustomDataConnectorConfig, HttpEndpointConfig, GrpcEndpointConfig, KafkaEndpointConfig,
    CustomEndpointConfig, CronEndpointConfig,
};

pub const ORDER_SERVICE_ID: i32 = 4;
pub const MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE_STREAM_ID: i32 = 46;
pub const MAP_TO_ORDER_PROCESSED_STREAM_ID: i32 = 47;
pub const MAP_TO_ORDER_STATE_STREAM_ID: i32 = 48;
pub const MERGE_RESULTS_STREAM_ID: i32 = 49;
pub const PROCESS_ORDER_STREAM_ID: i32 = 50;
pub const PROCESS_ORDER_ITEM_STREAM_ID: i32 = 51;
pub const PROCESS_ORDER_ITEMS_STREAM_ID: i32 = 52;
pub const PUBLISH_ORDER_PROCESSED_STREAM_ID: i32 = 53;
pub const SOFT_DEADLINE_STREAM_ID: i32 = 54;
pub const SPLIT_ORDER_RESULT_STREAM_ID: i32 = 55;
pub const SPLIT_PIPELINE_STREAM_ID: i32 = 56;

pub const INVENTORY_SERVICE_API_CONNECTOR_ID: i32 = 1;
pub const ORDER_EVENTS_CONNECTOR_ID: i32 = 3;
pub const ORDER_SERVICE_API_CONNECTOR_ID: i32 = 4;

pub const PROCESS_ORDER_ITEM_ENDPOINT_ID: i32 = 1;
pub const ORDER_PROCESSED_ENDPOINT_ID: i32 = 3;
pub const PROCESS_ORDER_ENDPOINT_ID: i32 = 4;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Streams {
    pub map_order_item_result_to_order_state: MapStreamConfig,
    pub map_to_order_processed: MapStreamConfig,
    pub map_to_order_state: MapStreamConfig,
    pub merge_results: MergeStreamConfig,
    pub process_order: InputStreamConfig,
    pub process_order_item: SinkStreamConfig,
    pub process_order_items: FlatMapStreamConfig,
    pub publish_order_processed: SinkStreamConfig,
    pub soft_deadline: DelayStreamConfig,
    pub split_order_result: SplitStreamConfig,
    pub split_pipeline: SplitStreamConfig,
}

impl Default for Streams {
    fn default() -> Self {
        Self {
            map_order_item_result_to_order_state: MapStreamConfig::from(StreamConfig::new(MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE_STREAM_ID, "Map Order Item Result To Order State").with_graph(
    ORDER_SERVICE_ID, PROCESS_ORDER_ITEM_STREAM_ID, [],
    Some("OrderState"),
    None::<String>,
    103_f64, -52_f64,
).with_pipeline("order")),
            map_to_order_processed: MapStreamConfig::from(StreamConfig::new(MAP_TO_ORDER_PROCESSED_STREAM_ID, "MapToOrderProcessed").with_graph(
    ORDER_SERVICE_ID, SPLIT_ORDER_RESULT_STREAM_ID, [],
    Some("OrderProcessed"),
    None::<String>,
    -821_f64, -26_f64,
).with_pipeline("order")),
            map_to_order_state: MapStreamConfig::from(StreamConfig::new(MAP_TO_ORDER_STATE_STREAM_ID, "Map to Order State").with_graph(
    ORDER_SERVICE_ID, SOFT_DEADLINE_STREAM_ID, [],
    Some("OrderState"),
    None::<String>,
    -368_f64, -227_f64,
).with_pipeline("order")),
            merge_results: MergeStreamConfig::from(StreamConfig::new(MERGE_RESULTS_STREAM_ID, "Merge Results").with_graph(
    ORDER_SERVICE_ID, 0, [MAP_TO_ORDER_STATE_STREAM_ID, MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE_STREAM_ID, -PROCESS_ORDER_ITEM_STREAM_ID],
    None::<String>,
    None::<String>,
    -228_f64, 130_f64,
).with_pipeline("order")),
            process_order: InputStreamConfig { stream: StreamConfig::new(PROCESS_ORDER_STREAM_ID, "Process Order").with_graph(
    ORDER_SERVICE_ID, SPLIT_ORDER_RESULT_STREAM_ID, [],
    Some("Order"),
    None::<String>,
    -760_f64, -367_f64,
).with_pipeline("order"), endpoint_id: PROCESS_ORDER_ENDPOINT_ID },
            process_order_item: SinkStreamConfig { stream: StreamConfig::new(PROCESS_ORDER_ITEM_STREAM_ID, "Process Order Item").with_graph(
    ORDER_SERVICE_ID, PROCESS_ORDER_ITEMS_STREAM_ID, [],
    Some("OrderItemResult"),
    None::<String>,
    -60_f64, -375_f64,
).with_pipeline("order"), endpoint_id: PROCESS_ORDER_ITEM_ENDPOINT_ID },
            process_order_items: FlatMapStreamConfig::from(StreamConfig::new(PROCESS_ORDER_ITEMS_STREAM_ID, "Process Order Items").with_graph(
    ORDER_SERVICE_ID, SPLIT_PIPELINE_STREAM_ID, [],
    Some("OrderItem"),
    None::<String>,
    -198_f64, -662_f64,
).with_pipeline("order")),
            publish_order_processed: SinkStreamConfig { stream: StreamConfig::new(PUBLISH_ORDER_PROCESSED_STREAM_ID, "Publish Order Processed").with_graph(
    ORDER_SERVICE_ID, MAP_TO_ORDER_PROCESSED_STREAM_ID, [],
    Some("OrderProcessed"),
    None::<String>,
    -944_f64, -255_f64,
).with_pipeline("order"), endpoint_id: ORDER_PROCESSED_ENDPOINT_ID },
            soft_deadline: DelayStreamConfig { stream: StreamConfig::new(SOFT_DEADLINE_STREAM_ID, "Soft Deadline").with_graph(
    ORDER_SERVICE_ID, SPLIT_PIPELINE_STREAM_ID, [],
    None::<String>,
    None::<String>,
    -477_f64, -444_f64,
).with_pipeline("order"), duration: Duration::from_millis(0) },
            split_order_result: SplitStreamConfig::from(StreamConfig::new(SPLIT_ORDER_RESULT_STREAM_ID, "Split Order Result").with_graph(
    ORDER_SERVICE_ID, MERGE_RESULTS_STREAM_ID, [],
    None::<String>,
    None::<String>,
    -671_f64, -129_f64,
).with_pipeline("order")),
            split_pipeline: SplitStreamConfig::from(StreamConfig::new(SPLIT_PIPELINE_STREAM_ID, "Split Pipeline").with_graph(
    ORDER_SERVICE_ID, PROCESS_ORDER_STREAM_ID, [],
    None::<String>,
    None::<String>,
    -640_f64, -597_f64,
).with_pipeline("order")),
        }
    }
}

impl Streams {
    fn runtime_configs(&self) -> Vec<RuntimeStreamConfig> {
        vec![
            self.map_order_item_result_to_order_state.clone().into(),
            self.map_to_order_processed.clone().into(),
            self.map_to_order_state.clone().into(),
            self.merge_results.clone().into(),
            self.process_order.clone().into(),
            self.process_order_item.clone().into(),
            self.process_order_items.clone().into(),
            self.publish_order_processed.clone().into(),
            self.soft_deadline.clone().into(),
            self.split_order_result.clone().into(),
            self.split_pipeline.clone().into(),
        ]
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Endpoints {
    pub process_order_item: GrpcEndpointConfig,
    pub order_processed: KafkaEndpointConfig,
    pub process_order: HttpEndpointConfig,
}

impl Default for Endpoints {
    fn default() -> Self {
        Self {
            process_order_item: GrpcEndpointConfig {
                id: PROCESS_ORDER_ITEM_ENDPOINT_ID, name: "Process Order Item".to_owned(), id_data_connector: INVENTORY_SERVICE_API_CONNECTOR_ID,
                tracing_enabled: false,
                grpc_method_type: GrpcMethodType::NoStreaming,
            },
            order_processed: KafkaEndpointConfig {
                id: ORDER_PROCESSED_ENDPOINT_ID, name: "Order Processed".to_owned(), id_data_connector: ORDER_EVENTS_CONNECTOR_ID,
                tracing_enabled: false,
                enabled: true, create_topic: true, topic: "order-processed".to_owned(),
                partitions: 1, consumer_group: "analytics-service".to_owned(),
                replication_factor: 1,
            },
            process_order: HttpEndpointConfig {
                id: PROCESS_ORDER_ENDPOINT_ID, name: "Process Order".to_owned(), id_data_connector: ORDER_SERVICE_API_CONNECTOR_ID,
                tracing_enabled: false,
                http_method_type: HTTPMethodType::POST, path: "/v1/processorder".to_owned(),
            },
        }
    }
}

impl Endpoints {
    fn runtime_configs(&self) -> Vec<RuntimeEndpointConfig> {
        vec![
            self.process_order_item.clone().into(),
            self.order_processed.clone().into(),
            self.process_order.clone().into(),
        ]
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct Config {
    pub default_pool_executors_count: usize,
    pub inventory_address: String,
    pub inventory_service_api_connections_count: usize,
    pub order_events_brokers: String,
    pub order_events_password: String,
    pub order_events_sasl_mechanism: String,
    pub order_events_security_protocol: String,
    pub order_events_username: String,
    pub order_processed_enabled: bool,
    pub request_timeout_ms: u64,
    pub environment: String,
    pub grpc_host: String,
    pub grpc_port: u16,
    pub http_host: String,
    pub http_port: u16,
    pub soft_deadline_margin_ms: u64,
    pub streams: Streams,
    pub endpoints: Endpoints,
    #[serde(flatten)]
    pub custom: CustomConfig,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            default_pool_executors_count: 2,
            inventory_address: "dns:///localhost:9202".to_owned(),
            inventory_service_api_connections_count: 1,
            order_events_brokers: "redpanda:9092".to_owned(),
            order_events_password: "".to_owned(),
            order_events_sasl_mechanism: "SCRAM-SHA-512".to_owned(),
            order_events_security_protocol: "PLAINTEXT".to_owned(),
            order_events_username: "".to_owned(),
            order_processed_enabled: true,
            request_timeout_ms: 0,
            environment: "".to_owned(),
            grpc_host: "0.0.0.0".to_owned(),
            grpc_port: 9201,
            http_host: "0.0.0.0".to_owned(),
            http_port: 9091,
            soft_deadline_margin_ms: 0,
            streams: Streams::default(),
            endpoints: Endpoints::default(),
            custom: CustomConfig::default(),
        }
    }
}

impl Config {
    pub fn service(&self) -> ServiceConfig {
        ServiceConfig {
            id: ORDER_SERVICE_ID,
            name: "Order Service".to_owned(),
            http_host: self.http_host.clone(),
            http_port: self.http_port,
            grpc_host: self.grpc_host.clone(),
            grpc_port: self.grpc_port,
            color: "#FF5C00".to_owned(),
            programming_language: servicelib::api::ProgrammingLanguage::Rust,
            module_path: "github.com/gorundebug/rustexample-orderservice".to_owned(),
            default_call_semantics: CallSemantics::FunctionCall,
            metrics_handler: "metrics".to_owned(),
            status_handler: "status".to_owned(),
            startup_handler: "health/startup".to_owned(),
            readiness_handler: "health/ready".to_owned(),
            liveness_handler: "health/live".to_owned(),
            kubernetes_workload_type: servicelib::api::KubernetesWorkloadType::Deployment,
            default_grpc_timeout: 0,
            log_level: LogLevel::Undefined,
            environment: self.environment.clone(),
            shutdown_timeout: 30000,
            ..ServiceConfig::default()
        }
    }
}

impl ServiceConfigContract for Config {
    fn apply_environment(&mut self) -> Result<(), String> {
        apply_usize("DEFAULT_POOL_EXECUTORS_COUNT", &mut self.default_pool_executors_count)?;
        apply_string("INVENTORY_SERVICE_API_ADDRESS", &mut self.inventory_address);
        apply_usize("INVENTORY_SERVICE_API_CONNECTIONS_COUNT", &mut self.inventory_service_api_connections_count)?;
        apply_string("ORDER_EVENTS_BROKERS", &mut self.order_events_brokers);
        apply_string("ORDER_EVENTS_PASSWORD", &mut self.order_events_password);
        apply_string("ORDER_EVENTS_SASL_MECHANISM", &mut self.order_events_sasl_mechanism);
        apply_string("ORDER_EVENTS_SECURITY_PROTOCOL", &mut self.order_events_security_protocol);
        apply_string("ORDER_EVENTS_USERNAME", &mut self.order_events_username);
        apply_bool("ORDER_PROCESSED_ENABLED", &mut self.order_processed_enabled)?;
        self.endpoints.order_processed.enabled = self.order_processed_enabled;
        apply_u64("ORDER_SERVICE_DEFAULT_GRPC_TIMEOUT", &mut self.request_timeout_ms)?;
        apply_string("ORDER_SERVICE_ENVIRONMENT", &mut self.environment);
        apply_string("ORDER_SERVICE_GRPC_HOST", &mut self.grpc_host);
        apply_port("ORDER_SERVICE_GRPC_PORT", &mut self.grpc_port)?;
        apply_string("ORDER_SERVICE_HTTP_HOST", &mut self.http_host);
        apply_port("ORDER_SERVICE_HTTP_PORT", &mut self.http_port)?;
        apply_u64("SOFT_DEADLINE_DURATION", &mut self.soft_deadline_margin_ms)?;
        self.streams.soft_deadline.duration = Duration::from_millis(self.soft_deadline_margin_ms);
        self.custom.apply_environment()
    }
    fn validate(&self) -> Result<(), String> {
        if self.http_port == 0 || self.grpc_port == 0 {
            return Err("httpPort and grpcPort must be positive".to_owned());
        }
        parse_environment(&self.environment)?;
        if self.inventory_address.is_empty() {
            return Err("inventory_address must not be empty".to_owned());
        }
        if self.inventory_service_api_connections_count == 0 {
            return Err("inventory_service_api_connections_count must be at least 1".to_owned());
        }
        parse_kafka_security_protocol(&self.order_events_security_protocol)?;
        parse_kafka_sasl_mechanism(&self.order_events_sasl_mechanism)?;
        self.custom.validate()
    }
    fn services(&self) -> Vec<ServiceConfig> {
        vec![self.service()]
    }
    fn streams(&self) -> Vec<RuntimeStreamConfig> { self.streams.runtime_configs() }
    fn data_connectors(&self) -> Vec<RuntimeDataConnectorConfig> {
        vec![
            GrpcDataConnectorConfig {
                id: INVENTORY_SERVICE_API_CONNECTOR_ID, name: "Inventory Service API".to_owned(),
                address: self.inventory_address.clone(),
                connections_count: self.inventory_service_api_connections_count,
            }.into(),
            KafkaDataConnectorConfig {
                id: ORDER_EVENTS_CONNECTOR_ID, name: "Order Events".to_owned(),
                brokers: self.order_events_brokers.clone(), version: "2.8.0".to_owned(),
                dial_timeout: 5000.0, use_partitioner: false, r#async: false,
                security_protocol: parse_kafka_security_protocol(&self.order_events_security_protocol).expect("Kafka security protocol was validated"),
                sasl_mechanism: parse_kafka_sasl_mechanism(&self.order_events_sasl_mechanism).expect("Kafka SASL mechanism was validated"),
                username: self.order_events_username.clone(),
                password: self.order_events_password.clone(),
            }.into(),
            HttpDataConnectorConfig {
                id: ORDER_SERVICE_API_CONNECTOR_ID, name: "Order Service API".to_owned(),
                host: self.http_host.clone(), port: self.http_port,
                address: "".to_owned(),
                use_dedicated_listener: false,
            }.into(),
        ]
    }
    fn endpoints(&self) -> Vec<RuntimeEndpointConfig> {
        self.endpoints.runtime_configs()
    }
    fn pools(&self) -> Vec<PoolConfig> {
        vec![
            PoolConfig { name: "Default Pool".to_owned(), executors_count: self.default_pool_executors_count, queue_capacity: 0 },
        ]
    }
    fn links(&self) -> Vec<LinkConfig> {
        vec![
            LinkConfig {
                from: MERGE_RESULTS_STREAM_ID, to: SPLIT_ORDER_RESULT_STREAM_ID,
                call_semantics: CallSemantics::FunctionCall,
                r#async: false,
            },
            LinkConfig {
                from: PROCESS_ORDER_STREAM_ID, to: SPLIT_PIPELINE_STREAM_ID,
                call_semantics: CallSemantics::PriorityTaskPool { pool_name: "Default Pool".to_owned(), priority: 1 },
                r#async: false,
            },
            LinkConfig {
                from: SPLIT_PIPELINE_STREAM_ID, to: PROCESS_ORDER_ITEMS_STREAM_ID,
                call_semantics: CallSemantics::ParallelCall,
                r#async: false,
            },
            LinkConfig {
                from: SPLIT_PIPELINE_STREAM_ID, to: SOFT_DEADLINE_STREAM_ID,
                call_semantics: CallSemantics::ParallelCall,
                r#async: false,
            },
        ]
    }
    fn modules(&self) -> Vec<ModuleConfig> {
        vec![
            ModuleConfig { name: "inventory_service_api".to_owned(), path: "github.com/gorundebug/rustexample-inventory-service-api".to_owned(), properties: Default::default() },
            ModuleConfig { name: "model".to_owned(), path: "github.com/gorundebug/rustexample-model".to_owned(), properties: Default::default() },
            ModuleConfig { name: "order_service_api".to_owned(), path: "github.com/gorundebug/rustexample-order-service-api".to_owned(), properties: Default::default() },
        ]
    }
    fn types(&self) -> Vec<TypeConfig> {
        vec![
            TypeConfig {
                name: "Order".to_owned(), data_type: DataType::Struct,
                type_definition: "Order".to_owned(), type_import: "crate::internal::types::order".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
            TypeConfig {
                name: "OrderItem".to_owned(), data_type: DataType::Struct,
                type_definition: "OrderItem".to_owned(), type_import: "example_model::types::order_item".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "model".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
            TypeConfig {
                name: "OrderItemResult".to_owned(), data_type: DataType::Struct,
                type_definition: "OrderItemResult".to_owned(), type_import: "example_model::types::order_item_result".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "model".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
            TypeConfig {
                name: "OrderProcessed".to_owned(), data_type: DataType::Struct,
                type_definition: "OrderProcessed".to_owned(), type_import: "example_model::types::order_processed".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "model".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
            TypeConfig {
                name: "OrderState".to_owned(), data_type: DataType::Struct,
                type_definition: "OrderState".to_owned(), type_import: "crate::internal::types::order_state".to_owned(),
                value_type: "".to_owned(), key_type: "".to_owned(),
                package: "".to_owned(), module: "".to_owned(),
                definition_format: TypeDefinitionFormat::Native, public_type: false,
                transfer_by_value: false, use_alias: false, properties: Default::default(),
            },
        ]
    }
}

fn apply_string(name: &str, target: &mut String) {
    if let Ok(value) = std::env::var(name) {
        *target = value;
    }
}

fn parse_schedule_overlap_policy(value: &str) -> Result<ScheduleOverlapPolicy, String> {
    match value {
        "Allow" => Ok(ScheduleOverlapPolicy::Allow),
        "Skip" => Ok(ScheduleOverlapPolicy::Skip),
        _ => Err(format!("invalid schedule overlap policy: {value}")),
    }
}

fn parse_schedule_missed_run_policy(value: &str) -> Result<ScheduleMissedRunPolicy, String> {
    match value {
        "Skip" => Ok(ScheduleMissedRunPolicy::Skip),
        "FireOnce" => Ok(ScheduleMissedRunPolicy::FireOnce),
        _ => Err(format!("invalid schedule missed-run policy: {value}")),
    }
}

fn apply_port(name: &str, target: &mut u16) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_u64(name: &str, target: &mut u64) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_usize(name: &str, target: &mut usize) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_i32(name: &str, target: &mut i32) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_f64(name: &str, target: &mut f64) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn apply_bool(name: &str, target: &mut bool) -> Result<(), String> {
    if let Ok(value) = std::env::var(name) {
        *target = value
            .parse()
            .map_err(|error| format!("invalid {name}: {error}"))?;
    }
    Ok(())
}

fn parse_environment(value: &str) -> Result<Environment, String> {
    match value {
        "" => Ok(Environment::Undefined),
        "local" => Ok(Environment::Local),
        "debug" => Ok(Environment::Debug),
        "staging" => Ok(Environment::Staging),
        "production" => Ok(Environment::Production),
        _ => Err(format!("invalid environment: {value}")),
    }
}

fn parse_kafka_security_protocol(value: &str) -> Result<KafkaSecurityProtocol, String> {
    match value {
        "PLAINTEXT" => Ok(KafkaSecurityProtocol::PLAINTEXT),
        "SASL_PLAINTEXT" => Ok(KafkaSecurityProtocol::SASLPLAINTEXT),
        "SASL_SSL" => Ok(KafkaSecurityProtocol::SASLSSL),
        _ => Err(format!("unknown Kafka security protocol {value:?}")),
    }
}

fn parse_kafka_sasl_mechanism(value: &str) -> Result<KafkaSaslMechanism, String> {
    match value {
        "PLAIN" => Ok(KafkaSaslMechanism::PLAIN),
        "SCRAM-SHA-256" => Ok(KafkaSaslMechanism::SCRAMSHA256),
        "SCRAM-SHA-512" => Ok(KafkaSaslMechanism::SCRAMSHA512),
        _ => Err(format!("unknown Kafka SASL mechanism {value:?}")),
    }
}