stages:
  - build
  - test
  - lint

.go-defaults:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go-cache/
  before_script:
    - export GOPATH="$CI_PROJECT_DIR/.go-cache"
    - export GOMODCACHE="$CI_PROJECT_DIR/.go-cache/pkg/mod"
    - export GOPRIVATE="github.com"
    - export GONOSUMDB="github.com"
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"

build:
  extends: .go-defaults
  image: golang:1.25-bookworm
  stage: build
  script:
    - go mod tidy
    - go build ./...

test:
  extends: .go-defaults
  image: golang:1.25-bookworm
  stage: test
  script:
    - go test ./...

lint:
  extends: .go-defaults
  image: golang:1.25-bookworm
  stage: lint
  script:
    - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
    - golangci-lint run