services:
  automationservice:
    image: automationservice:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        GOPROXY: ${GOPROXY:-direct}
        GOSUMDB: ${GOSUMDB:-sum.golang.org}
        RUNTIME_STRIP: ${RUNTIME_STRIP:-ON}
        DEPENDENCY_GITHUB_RAW_URL: ${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}
        DEPENDENCY_APT_DEBIAN_URL: ${DEPENDENCY_APT_DEBIAN_URL:-}
        DEPENDENCY_APT_DEBIAN_SECURITY_URL: ${DEPENDENCY_APT_DEBIAN_SECURITY_URL:-}
      additional_contexts:
        servicelib-source: "${GOSERVICELIB_SOURCE_CONTEXT:-https://github.com/gorundebug/servicelib.git#v0.2.25}"
    environment:
      - DEBUG=${DEBUG:-0}
    ports:
      - "9094:9094"
      - "9204:9204"
      - "2345:2345"