# Code generated by servicegen. DO NOT EDIT.
SERVICE_NAME=automationservice
SERVICE_NAME_UPPER=AUTOMATION_SERVICE
MODULE_DIR := $(abspath .)
PROJECT_DIR ?= $(MODULE_DIR)
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_VERSION := $(shell git describe --tags --always 2>/dev/null || echo "v0.0.0")
LDFLAGS := -X main.build_version=$(BUILD_VERSION) -X main.build_commit=$(GIT_COMMIT)
BIN_DIR := $(PROJECT_DIR)/bin
COMPOSE := docker compose -f $(if $(wildcard docker-compose.yml),docker-compose.yml,docker-compose.generated.yml)
COMPOSE_DEV := $(COMPOSE) -f docker-compose.dev.generated.yml
TOOLS_DIR ?= $(abspath ./tools)
BUF := $(TOOLS_DIR)/buf
PROTOC ?= $(TOOLS_DIR)/protoc
GOLANGCI_LINT ?= $(TOOLS_DIR)/golangci-lint
GOLANGCI_LINT_VERSION := v1.64.8
ACT_VERSION := v0.2.144
ACT := $(TOOLS_DIR)/act
OS := $(shell uname -s)
ARCH := $(shell uname -m)
GOSERVICELIB_SOURCE_CONTEXT ?= https://github.com/gorundebug/servicelib.git\#v0.2.25
RUNTIME_STRIP ?= ON
DEPENDENCY_DOWNLOAD_ENV := $(or $(wildcard $(abspath ./dependency-download-env.generated.sh)),$(wildcard $(abspath ../dependency-download-env.generated.sh)),/bin/sh)
SHELL := $(DEPENDENCY_DOWNLOAD_ENV)
.SHELLFLAGS := -c
export

DEPENDENCY_DOCKER_TARGETS := docker-build docker-up docker-build-dev docker-up-dev debug
include dependency-proxy.generated.mk

export GOWORK := off
ifeq ($(strip $(USE_LOCAL_MODULES)),1)
export GOWORK := $(abspath ../go.work)
endif

ifneq ($(strip $(DEPENDENCY_PROXY_DIR)),)
# Keep an explicit environment/command-line source context for local framework
# development. Only replace the generated release default with the proxy URL.
ifeq ($(origin GOSERVICELIB_SOURCE_CONTEXT),file)
GOSERVICELIB_SOURCE_CONTEXT := $(DEPENDENCY_PROXY_DOCKER_BASE)/github-raw/gorundebug/servicelib/archive/refs/tags/v0.2.25.tar.gz
endif
export GOSERVICELIB_SOURCE_CONTEXT
ifneq ($(strip $(USE_LOCAL_MODULES)),1)
endif
endif

.PHONY: all build clean run test lint lint-fix act gen-proto service_build service_build_linux fmt-proto \
	docker-build docker-build-dev docker-up docker-up-dev debug docker-down docker-down-dev hooks

all: build

build: gen-proto service_build

service_build:
	@echo "Building $(SERVICE_NAME)..."
	mkdir -p $(BIN_DIR)
	go build -ldflags="$(LDFLAGS)" -o "$(BIN_DIR)/$(SERVICE_NAME)" "./cmd/service/main.go"

service_build_linux:
	@echo "Building $(SERVICE_NAME) for linux/$(shell go env GOARCH)..."
	mkdir -p $(BIN_DIR)
	CGO_ENABLED=0 GOOS=linux go build -ldflags="$(LDFLAGS)" -o "$(BIN_DIR)/$(SERVICE_NAME)" "./cmd/service/main.go"

clean:
	@echo "Cleaning $(SERVICE_NAME)..."
	rm -rf "$(BIN_DIR)"

gen-proto:
	@if [ -d internal/proto ]; then \
		echo "Generate proto code..."; \
		find . -type f -name 'go.generated.proto.mk' | while read mkfile; do \
			dir=$$(dirname $$mkfile); \
			echo "Generating files in $$dir..."; \
			$(MAKE) -C $$dir -f $$(basename $$mkfile) gen MODULE_DIR="$(MODULE_DIR)" PROTOC="$(PROTOC)"; \
		done; \
	fi

fmt-proto:
	@find . -type f -name '*.proto' | while read protofile; do \
		$(BUF) format -w $$protofile; \
	done

docker-build:
	@$(COMPOSE) build $(SERVICE_NAME)

docker-build-dev:
	@$(COMPOSE_DEV) build $(SERVICE_NAME)

docker-up: docker-build
	@$(COMPOSE) up -d --no-build $(SERVICE_NAME)

docker-up-dev: docker-build-dev
	@DEBUG=0 $(COMPOSE_DEV) up -d --no-build --force-recreate $(SERVICE_NAME)

debug: docker-build-dev
	@DEBUG=1 $(COMPOSE_DEV) up -d --no-build --force-recreate $(SERVICE_NAME)

docker-down:
	@$(COMPOSE) down

docker-down-dev:
	@$(COMPOSE_DEV) down

test:
	go test ./...

lint: $(GOLANGCI_LINT)
	$(GOLANGCI_LINT) run ./...

lint-fix: $(GOLANGCI_LINT)
	$(GOLANGCI_LINT) run --fix ./...

$(GOLANGCI_LINT):
	@mkdir -p $(TOOLS_DIR)
	@echo "Installing golangci-lint $(GOLANGCI_LINT_VERSION)..."
	@GOBIN=$(TOOLS_DIR) go install github.com/golangci/golangci-lint/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)

$(ACT):
	@mkdir -p $(TOOLS_DIR)
	@echo "Downloading act $(ACT_VERSION)..."
	@curl -sSL "$(DEPENDENCY_GITHUB_RAW_URL)/nektos/act/releases/download/$(ACT_VERSION)/act_$(OS)_$(ARCH).tar.gz" | tar -xz -C $(TOOLS_DIR) act

act: $(ACT) ## Run GitHub Actions locally via act (requires Docker)
	$(ACT) push

run:
	go run "./cmd/service/main.go" -config "./config/config.yaml" -values "./config/overrides.yaml"

hooks: ## Install git hooks (pre-commit: lint, pre-push: test)
	@cp scripts/pre-commit.generated.sh .git/hooks/pre-commit
	@chmod +x .git/hooks/pre-commit
	@cp scripts/pre-push.generated.sh .git/hooks/pre-push
	@chmod +x .git/hooks/pre-push
	@echo "Git hooks installed."