// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::{
    clients_generated::ServiceClients,
    connectors_generated::{ServiceDataConnectors, ServiceInfrastructure},
    functions_generated::{ServiceFunctions, ServiceHandlers},
    streams_generated::ServiceStreams,
};

pub struct ServiceRuntime {
    pub streams: ServiceStreams,
    pub handlers: ServiceHandlers,
    pub data_connectors: ServiceDataConnectors,
    pub clients: ServiceClients,
}

pub struct ServiceBindings;

impl ServiceBindings {
    pub fn build(
        config: &Config,
        streams: ServiceStreams,
        functions: ServiceFunctions,
        infrastructure: ServiceInfrastructure,
    ) -> RuntimeResult<ServiceRuntime> {
        let _ = config;
        let clients = ServiceClients::init_clients(&infrastructure);
        let ServiceStreams {
            process_inventory_item,
            get_inventory_item_data,
            get_inventory_item_error,
            map_inventory_item_error,
            merge_inventory_result,
        } = streams;

        Ok(ServiceRuntime {
            clients,
            streams: ServiceStreams {
            process_inventory_item,
            get_inventory_item_data,
            get_inventory_item_error,
            map_inventory_item_error,
            merge_inventory_result,
            },
            handlers: ServiceHandlers {
                process_order_item_source: functions.process_order_item_source,
            },
      data_connectors: ServiceDataConnectors {
        inventory_service_api_data_source: infrastructure.inventory_service_api_data_source,
      },
    })
}

}