// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::bindings_generated::ServiceRuntime;

pub struct ServiceEndpoints {
    pub process_order_item_endpoint: Arc<NoStreamingEndpointConsumer<
        (), inventory_service_api::inventoryserviceapi::processorderitem::ProcessOrderItemRequest, inventory_service_api::inventoryserviceapi::processorderitem::ProcessOrderItemResponse,
        OrderItem, OrderItemResult, OrderItemResult, ProcessOrderItemSource
    >>,

}

impl ServiceEndpoints {
    pub fn init_endpoints(config: &Config, runtime: &ServiceRuntime) -> RuntimeResult<Self> {
        let _ = (config, runtime);
        let process_order_item_endpoint = make_grpc_source_endpoint_consumer(
            runtime.streams.process_inventory_item.as_ref().clone(),
            runtime.handlers.process_order_item_source.clone(),
        )?;


        Ok(Self {
            process_order_item_endpoint,
        })
    }
}