// Code generated by servicegen. DO NOT EDIT.

use super::*;

#[derive(Clone)]
pub struct InventoryItemPipelineMakers {
    pub get_inventory_item_data: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a ProcessStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<GetInventoryItemData>> + Send + 'a>> + Send + Sync>,
    pub get_inventory_item_error: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a MapStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<GetInventoryItemError>> + Send + 'a>> + Send + Sync>,
    pub process_order_item_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a GrpcEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ProcessOrderItemSource>> + Send + 'a>> + Send + Sync>,
}

macro_rules! init_inventory_item_pipeline_streams {
    ($config:ident, $environment:ident, $functions:ident) => {{
        init_inventory_item_process_inventory_item_stream!($config, $environment, $functions, process_inventory_item);
        init_inventory_item_get_inventory_item_data_stream!($config, $environment, $functions, get_inventory_item_data, get_inventory_item_error, process_inventory_item.stream());
        init_inventory_item_map_inventory_item_error_stream!($config, $environment, $functions, map_inventory_item_error, get_inventory_item_error);
        init_inventory_item_merge_inventory_result_stream!($config, $environment, $functions, merge_inventory_result, [get_inventory_item_data, map_inventory_item_error]);
        process_inventory_item.set_source(&merge_inventory_result)?;
        Ok::<InventoryItemPipelineStreams, RuntimeError>(InventoryItemPipelineStreams {
            process_order_item: process_inventory_item,
            get_inventory_item_data,
            get_inventory_item_error,
            map_inventory_item_error,
            merge_inventory_result,
        })
    }};
}

impl Default for InventoryItemPipelineMakers {
    fn default() -> Self {
        Self {
            get_inventory_item_data: Arc::new(|context, environment, config| {
                Box::pin(async move { make_get_inventory_item_data(context, environment, config).await })
            }),
            get_inventory_item_error: Arc::new(|context, environment, config| {
                Box::pin(async move { make_get_inventory_item_error(context, environment, config).await })
            }),
            process_order_item_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_process_order_item_source(context, environment, config).await })
            }),
        }
    }
}

pub struct InventoryItemPipelineFunctions {
    pub get_inventory_item_data: GetInventoryItemData,
    pub get_inventory_item_error: GetInventoryItemError,
    pub process_order_item_source: ProcessOrderItemSource,
}

pub struct InventoryItemPipelineStreams {
    pub process_order_item: Arc<InputStream<OrderItem, OrderItemResult, OrderItemResult>>,
    pub get_inventory_item_data: Stream<OrderItemResult>,
    pub get_inventory_item_error: Stream<String>,
    pub map_inventory_item_error: Stream<OrderItemResult>,
    pub merge_inventory_result: Stream<OrderItemResult>,
}
macro_rules! init_inventory_item_process_inventory_item_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident) => {
        let $variable = Arc::new(InputStream::<OrderItem, OrderItemResult, OrderItemResult>::new(&$config.streams.process_inventory_item, $environment.clone()));
    };
}
macro_rules! init_inventory_item_get_inventory_item_data_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $error:ident, $source:expr) => {
        let ($variable, $error) = $source.process(&$config.streams.get_inventory_item_data, $functions.inventory_item.get_inventory_item_data)?;
        let _ = &$error;
    };
}
macro_rules! init_inventory_item_map_inventory_item_error_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, $source:expr) => {
        let $variable = $source.map(&$config.streams.map_inventory_item_error, $functions.inventory_item.get_inventory_item_error)?;
    };
}
macro_rules! init_inventory_item_merge_inventory_result_stream {
    ($config:ident, $environment:ident, $functions:ident, $variable:ident, [$first:expr $(, $source:expr)*]) => {
        let $variable = $first.merge(&$config.streams.merge_inventory_result, &[$($source.clone()),*])?;
    };
}