// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use std::{future::Future, pin::Pin, sync::{Arc, OnceLock, Weak, mpsc}};

use servicelib::{
    MessageContext, Stream,
    operators::{InputStream, SinkStream, SinkStreamWithResult},
    runtime::{
        config::{
            ConfigLoader, RuntimeDataConnectorConfig,
            GrpcEndpointConfig,
            ProcessStreamConfig,
            GrpcDataConnectorConfig,
        },
        environment::{RuntimeEnvironment, RuntimeError, RuntimeResult},
        serviceapp::ServiceApp,
    },
};
use example_model::types::*;






use servicelib::datasource::grpc::{
    NoStreamingEndpointConsumer, TonicDataSource,
    make_grpc_no_streaming_endpoint_consumer as make_grpc_source_endpoint_consumer,
};
use tonic::{Request, Response, Status};
use inventory_service_api::inventoryserviceapi::inventory_service_api_server::{
    InventoryServiceApi, InventoryServiceApiServer,
};

use inventory_service_api::processorderitem::{
    ProcessOrderItemRequest, ProcessOrderItemResponse,
};

use crate::internal::{config::Config, functions::*};

pub struct ServiceStreams {
    pub process_order_item: Arc<InputStream<OrderItem, OrderItemResult, OrderItemResult>>,
    pub get_inventory_item_data: Stream<OrderItemResult>,
    pub get_inventory_item_error: Stream<OrderItemResult>,
    pub merge_inventory_result: Stream<OrderItemResult>,
}

pub struct ServiceHandlers {
    pub process_order_item_source: ProcessOrderItemSource,
}

pub struct ServiceDataConnectors {
    pub inventory_service_api_data_source: Arc<TonicDataSource>,
}

pub struct ServiceRuntime {
    pub streams: ServiceStreams,
    pub handlers: ServiceHandlers,
    pub data_connectors: ServiceDataConnectors,
}

pub struct ServiceInfrastructure {
    pub inventory_service_api_data_source: Arc<TonicDataSource>,
}

struct GeneratedServiceInner {
    runtime: ServiceRuntime,
    process_order_item_endpoint: Arc<NoStreamingEndpointConsumer<
        (), ProcessOrderItemRequest, ProcessOrderItemResponse,
        OrderItem, OrderItemResult, OrderItemResult, ProcessOrderItemSource
    >>,
    app: OnceLock<Arc<ServiceApp>>,
}

#[derive(Clone)]
pub struct GeneratedService {
    inner: Arc<GeneratedServiceInner>,
}

#[derive(Clone)]
pub struct ServiceMakers {
    pub get_inventory_item_data: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a ProcessStreamConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<GetInventoryItemData>> + Send + 'a>> + Send + Sync>,
    pub process_order_item_source: Arc<dyn for<'a> Fn(
        MessageContext,
        RuntimeEnvironment,
        &'a GrpcEndpointConfig,
    ) -> Pin<Box<dyn Future<Output = RuntimeResult<ProcessOrderItemSource>> + Send + 'a>> + Send + Sync>,
    pub inventory_service_api_data_source: ServiceInfrastructureMaker<GrpcDataConnectorConfig, Arc<TonicDataSource>>,
}

pub type ServiceInfrastructureMaker<C, T> = Arc<dyn for<'a> Fn(
    MessageContext,
    RuntimeEnvironment,
    &'a C,
) -> Pin<Box<dyn Future<Output = RuntimeResult<T>> + Send + 'a>> + Send + Sync>;

impl Default for ServiceMakers {
    fn default() -> Self {
        Self {
            get_inventory_item_data: Arc::new(|context, environment, config| {
                Box::pin(async move { make_get_inventory_item_data(context, environment, config).await })
            }),
            process_order_item_source: Arc::new(|context, environment, config| {
                Box::pin(async move { make_process_order_item_source(context, environment, config).await })
            }),
            inventory_service_api_data_source: Arc::new(|_context, environment, config| {
                Box::pin(async move { TonicDataSource::from_config(environment, config) })
            }),
        }
    }
}

fn connector_config(
    environment: &RuntimeEnvironment,
    connector_id: i32,
) -> RuntimeResult<Arc<RuntimeDataConnectorConfig>> {
    environment.runtime_config().data_connector_by_id(connector_id).ok_or_else(||
        RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not configured"
        ))
    )
}
fn grpc_connector_config(environment: &RuntimeEnvironment, connector_id: i32) -> RuntimeResult<GrpcDataConnectorConfig> {
    match connector_config(environment, connector_id)?.as_ref() {
        RuntimeDataConnectorConfig::Grpc(config) => Ok(config.clone()),
        _ => Err(RuntimeError::InvalidConfiguration(format!(
            "data connector {connector_id} is not gRPC"
        ))),
    }
}

pub struct ServiceFunctions {
    pub get_inventory_item_data: GetInventoryItemData,
    pub process_order_item_source: ProcessOrderItemSource,
}

pub async fn init_functions(
    context: MessageContext,
    config: &Config,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
) -> RuntimeResult<ServiceFunctions> {
    let maker_group_context = context.child();
    let (maker_error_sender, maker_error_receiver) = mpsc::channel::<RuntimeError>();
        let get_inventory_item_data_maker = makers.get_inventory_item_data.clone();
        let get_inventory_item_data_context = maker_group_context.clone();
        let get_inventory_item_data_group_context = maker_group_context.clone();
        let get_inventory_item_data_environment = environment.clone();
        let get_inventory_item_data_error_sender = maker_error_sender.clone();
        let get_inventory_item_data_future = async move {
            let result = (get_inventory_item_data_maker)(
                    get_inventory_item_data_context,
                    get_inventory_item_data_environment,
                    &config.streams.get_inventory_item_data,
                ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    get_inventory_item_data_group_context.cancel();
                    get_inventory_item_data_error_sender
                        .send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
        let process_order_item_source_maker = makers.process_order_item_source.clone();
        let process_order_item_source_context = maker_group_context.clone();
        let process_order_item_source_group_context = maker_group_context.clone();
        let process_order_item_source_environment = environment.clone();
        let process_order_item_source_error_sender = maker_error_sender.clone();
        let process_order_item_source_future = async move {
            let result = (process_order_item_source_maker)(
                    process_order_item_source_context,
                    process_order_item_source_environment,
                    &config.endpoints.process_order_item,
                ).await;
            match result {
                Ok(value) => Some(value),
                Err(error) => {
                    process_order_item_source_group_context.cancel();
                    process_order_item_source_error_sender
                        .send(error)
                        .expect("function maker error receiver was dropped");
                    None
                }
            }
        };
    let (
        get_inventory_item_data,
        process_order_item_source,
    ) = tokio::join!(
        get_inventory_item_data_future,
        process_order_item_source_future,
    );
    maker_group_context.cancel();
    drop(maker_error_sender);
    if let Ok(error) = maker_error_receiver.try_recv() {
        return Err(error);
    }
    let get_inventory_item_data = get_inventory_item_data.ok_or_else(|| RuntimeError::InvalidConfiguration(
        "function maker get_inventory_item_data failed without an error".to_string(),
    ))?;
    let process_order_item_source = process_order_item_source.ok_or_else(|| RuntimeError::InvalidConfiguration(
        "function maker process_order_item_source failed without an error".to_string(),
    ))?;
    Ok(ServiceFunctions {
        get_inventory_item_data,
        process_order_item_source,
    })
}
macro_rules! infrastructure_maker_future {
    ($maker:expr, $context:expr, $environment:expr, $config:expr, $group:expr, $errors:expr) => ({
        let maker = $maker.clone();
        let context = $context.clone();
        let environment = $environment.clone();
        let config = $config;
        let group = $group.clone();
        let errors = $errors.clone();
        async move {
            match (maker)(context, environment, &config).await {
                Ok(value) => Some(value),
                Err(error) => {
                    group.cancel();
                    errors.send(error).expect("infrastructure maker error receiver was dropped");
                    None
                }
            }
        }
    });
}

pub async fn init_infrastructure(
    context: MessageContext,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
) -> RuntimeResult<ServiceInfrastructure> {
    let maker_group_context = context.child();
    let (maker_error_sender, maker_error_receiver) = mpsc::channel::<RuntimeError>();
    let inventory_service_api_data_source_future = infrastructure_maker_future!(
        makers.inventory_service_api_data_source, maker_group_context, environment,
        grpc_connector_config(&environment, 1)?, maker_group_context, maker_error_sender
    );
    let (
        inventory_service_api_data_source,
    ) = tokio::join!(
        inventory_service_api_data_source_future,
    );
    maker_group_context.cancel();
    drop(maker_error_sender);
    if let Ok(error) = maker_error_receiver.try_recv() {
        return Err(error);
    }
    Ok(ServiceInfrastructure {
        inventory_service_api_data_source: inventory_service_api_data_source.ok_or_else(|| RuntimeError::InvalidConfiguration("infrastructure maker inventory_service_api_data_source failed without an error".to_owned()))?,
    })
}

pub fn init_runtime(
    config: &Config,
    environment: RuntimeEnvironment,
    functions: ServiceFunctions,
    infrastructure: ServiceInfrastructure,
) -> RuntimeResult<ServiceRuntime>  {
    let process_inventory_item = Arc::new(InputStream::<OrderItem, OrderItemResult, OrderItemResult>::new(&config.streams.process_inventory_item, environment.clone()));
    let (get_inventory_item_data, get_inventory_item_error) = process_inventory_item.stream().process(&config.streams.get_inventory_item_data, functions.get_inventory_item_data)?;
    let _ = &get_inventory_item_error;
    let merge_inventory_result = get_inventory_item_data.merge(&config.streams.merge_inventory_result, &[get_inventory_item_error.clone()])?;
    process_inventory_item.set_source(&merge_inventory_result)?;
    Ok(ServiceRuntime {
      streams: ServiceStreams {
        process_order_item: process_inventory_item.clone(),
        get_inventory_item_data,
        get_inventory_item_error,
        merge_inventory_result,
      },
      handlers: ServiceHandlers {
        process_order_item_source: functions.process_order_item_source,
      },
      data_connectors: ServiceDataConnectors {
        inventory_service_api_data_source: infrastructure.inventory_service_api_data_source,
      },
    })
}

impl GeneratedService {
    pub async fn new(
        config: &Config,
        environment: RuntimeEnvironment,
        config_loader: ConfigLoader<Config>,
        custom_makers_init: fn(MessageContext, &mut ServiceMakers) -> RuntimeResult<()>,
        custom_functions_init: fn(MessageContext, &mut ServiceFunctions) -> RuntimeResult<()>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let mut app = ServiceApp::new(environment, config.service())?;
        let context = MessageContext::new();
        let mut makers = ServiceMakers::default();
        custom_makers_init(context.clone(), &mut makers)?;
        let mut functions = init_functions(
            context.clone(), config, app.environment().clone(), &makers,
        ).await?;
        custom_functions_init(context, &mut functions)?;
        let infrastructure = init_infrastructure(
            MessageContext::new(), app.environment().clone(), &makers,
        ).await?;
        let runtime = init_runtime(
            config, app.environment().clone(), functions, infrastructure,
        )?;
        let process_order_item_endpoint = make_grpc_source_endpoint_consumer(
            runtime.streams.process_order_item.as_ref().clone(),
            runtime.handlers.process_order_item_source.clone(),
        )?;

        let service = Self {
            inner: Arc::new(GeneratedServiceInner {
                runtime,
                process_order_item_endpoint,
                app: OnceLock::new(),
            }),
        };
        app.register_data_source(Arc::clone(
            &service.inner.runtime.data_connectors.inventory_service_api_data_source,
        ))?;

        let weak: Weak<GeneratedServiceInner> = Arc::downgrade(&service.inner);
        config_loader.set_reload_handler(move |config, runtime_config| {
            let Some(inner) = weak.upgrade() else {
                return Ok(());
            };
            let app = inner.app.get().ok_or_else(||
                "service application is not initialized".to_owned()
            )?;
            app.validate_reload(&config.service())
                .map_err(|error| error.to_string())?;
            app.environment().publish_runtime_config(runtime_config);
            Ok(())
        });
        app.add_component(Arc::new(config_loader))?;
        app.add_grpc_service(InventoryServiceApiServer::new(service.clone()))?;
        let app = Arc::new(app);
        service.inner.app.set(app).map_err(|_| {
            "service application initialized twice".to_owned()
        })?;
        Ok(service)
    }

    pub async fn run(self) -> Result<(), Box<dyn std::error::Error>> {
        let app = self.inner.app.get().ok_or_else(||
            "service application is not initialized".to_owned()
        )?;
        app.start(MessageContext::new()).await?;
        #[cfg(unix)]
        {
            let mut terminate = tokio::signal::unix::signal(
                tokio::signal::unix::SignalKind::terminate(),
            )?;
            tokio::select! {
                result = tokio::signal::ctrl_c() => result?,
                _ = terminate.recv() => {},
            }
        }
        #[cfg(not(unix))]
        tokio::signal::ctrl_c().await?;
        app.stop(MessageContext::new()).await?;
        Ok(())
    }
}


#[tonic::async_trait]
impl InventoryServiceApi for GeneratedService {
    async fn process_order_item(
        &self,
        request: Request<ProcessOrderItemRequest>,
    ) -> Result<Response<ProcessOrderItemResponse>, Status> {
        let context = MessageContext::from_tonic_request(&request);
        let response = self.inner.process_order_item_endpoint
            .handle(context, request.into_inner())
            .await
            .map_err(|error| Status::internal(error.to_string()))?;
        Ok(Response::new(response))
    }
}