// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::service_generated::GeneratedService;


use futures_util::{Stream as FuturesStream, StreamExt};

fn grpc_request_stream<T>(receiver: tokio::sync::mpsc::Receiver<T>)
    -> impl FuturesStream<Item = T> + Send
where T: Send + 'static {
    futures_util::stream::unfold(receiver, |mut receiver| async move {
        receiver.recv().await.map(|value| (value, receiver))
    })
}


pub struct GrpcResponseStream<T> {
    receiver: tokio::sync::mpsc::Receiver<Result<T, Status>>,
    context: MessageContext,
}

impl<T> FuturesStream for GrpcResponseStream<T> {
    type Item = Result<T, Status>;
    fn poll_next(self: Pin<&mut Self>, cx: &mut std::task::Context<'_>)
        -> std::task::Poll<Option<Self::Item>> {
        self.get_mut().receiver.poll_recv(cx)
    }
}

impl<T> Drop for GrpcResponseStream<T> {
    fn drop(&mut self) { self.context.cancel(); }
}

struct GrpcResponseSender<T>(tokio::sync::mpsc::Sender<Result<T, Status>>);

#[tonic::async_trait]
impl<T: Send + 'static> servicelib::datasource::grpc::Sender<T> for GrpcResponseSender<T> {
    async fn send(&self, context: MessageContext, value: T)
        -> servicelib::datasource::grpc::HandlerResult {
        tokio::select! {
            _ = context.cancelled() => Err(Box::new(Status::cancelled("RPC cancelled")) as _),
            result = self.0.send(Ok(value)) => result.map_err(|_| Box::new(Status::cancelled("response stream closed")) as _),
        }
    }
}


pub struct ServiceServers;

impl ServiceServers {
    pub fn register(app: &mut ServiceApp, service: GeneratedService) -> RuntimeResult<()> {
        let _ = (&app, &service);
        app.add_grpc_service(InventoryServiceApiServer::new(service.clone()))?;
        Ok(())
    }
}


#[tonic::async_trait]
impl InventoryServiceApi for GeneratedService {


    async fn process_order_item(
        &self,
        request: Request<inventory_service_api::inventoryserviceapi::processorderitem::ProcessOrderItemRequest>,
    ) -> Result<Response<inventory_service_api::inventoryserviceapi::processorderitem::ProcessOrderItemResponse>, Status> {
        let context = MessageContext::from_tonic_request(&request);

        let request = request.into_inner();


        let response = self.inner.endpoints.process_order_item_endpoint
            .handle(context, request)
            .await
            .map_err(|error| Status::internal(error.to_string()))?;
        Ok(Response::new(response))

    }

}