// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use std::sync::Arc;

use servicelib::{
    MessageContext, Stream,
    operators::{InputStream, SinkStream, SinkStreamWithResult},
    runtime::{
        config::{ GrpcEndpointConfig, ProcessStreamConfig,  },
        environment::{RuntimeEnvironment, RuntimeResult},
    },
};
use example_model::types::*;





use crate::internal::{config::Config, functions::*};

pub struct ServiceStreams {
    pub process_order_item: Arc<InputStream<OrderItem, OrderItemResult, OrderItemResult>>,
    pub get_inventory_item_data: Stream<OrderItemResult>,
    pub get_inventory_item_error: Stream<OrderItemResult>,
    pub merge_inventory_result: Stream<OrderItemResult>,
}

pub struct ServiceHandlers {
    pub process_order_item: ProcessOrderItem,
}

pub struct ServiceDataConnectors {
}

pub struct ServiceRuntime {
    pub streams: ServiceStreams,
    pub handlers: ServiceHandlers,
    pub data_connectors: ServiceDataConnectors,
}

#[derive(Clone)]
pub struct ServiceMakers {
    pub get_inventory_item_data: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &ProcessStreamConfig,
    ) -> RuntimeResult<GetInventoryItemData> + Send + Sync>,
    pub process_order_item: Arc<dyn Fn(
        MessageContext,
        RuntimeEnvironment,
        &GrpcEndpointConfig,
    ) -> RuntimeResult<ProcessOrderItem> + Send + Sync>,
}

impl Default for ServiceMakers {
    fn default() -> Self {
        Self {
            get_inventory_item_data: Arc::new(make_get_inventory_item_data),
            process_order_item: Arc::new(make_process_order_item),
        }
    }
}

pub struct ServiceFunctions {
    pub get_inventory_item_data: GetInventoryItemData,
    pub process_order_item: ProcessOrderItem,
}

pub fn init_functions(
    context: MessageContext,
    config: &Config,
    environment: RuntimeEnvironment,
    makers: &ServiceMakers,
) -> RuntimeResult<ServiceFunctions> {
    Ok(ServiceFunctions {
        get_inventory_item_data: (makers.get_inventory_item_data)(context.clone(), environment.clone(), &config.streams.get_inventory_item_data)?,
        process_order_item: (makers.process_order_item)(context.clone(), environment.clone(), &config.endpoints.process_order_item)?,
    })
}

pub fn init_runtime(
    config: &Config,
    environment: RuntimeEnvironment,
    functions: ServiceFunctions,
) -> RuntimeResult<ServiceRuntime>  {
    let process_inventory_item = Arc::new(InputStream::<OrderItem, OrderItemResult, OrderItemResult>::new(&config.streams.process_inventory_item, environment.clone()));
    let (get_inventory_item_data, get_inventory_item_error) = process_inventory_item.stream().process(&config.streams.get_inventory_item_data, functions.get_inventory_item_data)?;
    let _ = &get_inventory_item_error;
    let merge_inventory_result = get_inventory_item_data.merge(&config.streams.merge_inventory_result, &[get_inventory_item_error.clone()])?;
    process_inventory_item.set_source(&merge_inventory_result)?;
    Ok(ServiceRuntime {
      streams: ServiceStreams {
        process_order_item: process_inventory_item.clone(),
        get_inventory_item_data,
        get_inventory_item_error,
        merge_inventory_result,
      },
      handlers: ServiceHandlers {
        process_order_item: functions.process_order_item,
      },
      data_connectors: ServiceDataConnectors {
      },
    })
}