// Code generated by servicegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use super::imports::*;
use super::functions_generated::ServiceFunctions;

pub struct GeneratedSharedCaseFunction<F>(pub Arc<F>);

impl<T, F> servicelib::operators::case::BuildSwitchFunction<T> for GeneratedSharedCaseFunction<F>
where
    F: servicelib::operators::case::BuildSwitchFunction<T>,
{
    fn select(&self, value: &T) -> usize {
        servicelib::operators::case::BuildSwitchFunction::select(self.0.as_ref(), value)
    }
}


pub struct ServiceStreams {
    pub process_inventory_item: Arc<InputStream<OrderItem, OrderItemResult, OrderItemResult>>,
    pub get_inventory_item_data: Stream<OrderItemResult>,
    pub get_inventory_item_error: Stream<String>,
    pub map_inventory_item_error: Stream<OrderItemResult>,
    pub merge_inventory_result: Stream<OrderItemResult>,
}

impl ServiceStreams {
    #[inline(never)]
    pub fn init_streams(
        config: &Config,
        environment: &RuntimeEnvironment,
        functions: &ServiceFunctions,
    ) -> RuntimeResult<Self> {
        let _ = (config, environment, functions);
    let process_inventory_item = Arc::new(InputStream::<OrderItem, OrderItemResult, OrderItemResult>::new(&config.streams.process_inventory_item, environment.clone()));
    let (get_inventory_item_data, get_inventory_item_error) = process_inventory_item.stream().process(&config.streams.get_inventory_item_data, functions.get_inventory_item_data.clone())?;
    let _ = &get_inventory_item_error;
    let map_inventory_item_error = get_inventory_item_error.map(&config.streams.map_inventory_item_error, functions.get_inventory_item_error.clone())?;
    let merge_inventory_result = get_inventory_item_data.merge(&config.streams.merge_inventory_result, &[map_inventory_item_error.clone()])?;

        let streams = Self {
            process_inventory_item: process_inventory_item,
            get_inventory_item_data,
            get_inventory_item_error,
            map_inventory_item_error,
            merge_inventory_result,
        };
        streams.build()?;
        Ok(streams)
    }

    pub fn build(&self) -> RuntimeResult<()> {
        self.process_inventory_item.set_source(&self.merge_inventory_result)?;
        Ok(())
    }
}