[package]
name = "inventoryservice"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
async-trait = "0.1"
axum = "0.8"
example-model = { git = "https://github.com/gorundebug/rustexample.git", tag = "v0.2.67" }
inventory-service-api = { git = "https://github.com/gorundebug/rustexample.git", tag = "v0.2.67" }
mimalloc = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
servicelib-gorundebug = { git = "https://github.com/gorundebug/rustservicelib.git", tag = "v0.2.67" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tonic = "0.12"
tracing = "0.1"
tracing-subscriber = "0.3"
