# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= 18081
SERVICEGEN_DEPENDENCY_PROXY_BASE := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository
export CARGO_REGISTRIES_CRATES_IO_INDEX := sparse+$(SERVICEGEN_DEPENDENCY_PROXY_BASE)/cargo-proxy/
export SERVICEGEN_MAVEN_CENTRAL_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/maven-central
endif

.PHONY: generate build test lint fmt clean help

generate: ## Generate transport bindings when this package owns a schema
	@if [ -x ./generate-openapi.generated.sh ]; then \
	  ./generate-openapi.generated.sh; \
	fi

build: generate ## Build this standalone Rust package
	@cargo build

test: generate ## Test this standalone Rust package
	@cargo test --all-targets

lint: ## Check formatting and Clippy warnings
	@cargo fmt -- --check
	@cargo clippy --all-targets -- -D warnings

fmt: ## Format Rust sources
	@cargo fmt

clean: ## Remove Rust build artifacts
	@cargo clean

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'