services:
  orderservice:
    image: orderservice-rust:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        CARGO_REGISTRIES_CRATES_IO_INDEX: ${CARGO_REGISTRIES_CRATES_IO_INDEX:-https://github.com/rust-lang/crates.io-index}
        DEPENDENCY_MAVEN_CENTRAL_URL: ${DEPENDENCY_MAVEN_CENTRAL_URL:-https://repo1.maven.org/maven2}
        DEPENDENCY_APT_DEBIAN_URL: ${DEPENDENCY_APT_DEBIAN_URL:-}
        DEPENDENCY_APT_DEBIAN_SECURITY_URL: ${DEPENDENCY_APT_DEBIAN_SECURITY_URL:-}
      additional_contexts:
        rustservicelib-source: "${RUSTSERVICELIB_SOURCE_CONTEXT:-https://github.com/gorundebug/rustservicelib.git#v0.2.31}"
        module-model_rust-source: "${EXAMPLE_MODEL_SOURCE_CONTEXT:-https://github.com/gorundebug/rustexample.git#v0.2.31}"
        module-order_service_api-source: "${ORDER_SERVICE_API_SOURCE_CONTEXT:-https://github.com/gorundebug/rustexample.git#v0.2.31}"
        module-inventory_service_api-source: "${INVENTORY_SERVICE_API_SOURCE_CONTEXT:-https://github.com/gorundebug/rustexample.git#v0.2.31}"
    environment:
      - DEBUG=${DEBUG:-0}
      - ORDER_SERVICE_HTTP_PORT
      - ORDER_SERVICE_GRPC_PORT
    ports:
      - "${ORDER_SERVICE_HOST_HTTP_PORT:-9091}:${ORDER_SERVICE_HTTP_PORT:-9091}"
      - "${ORDER_SERVICE_HOST_GRPC_PORT:-9201}:${ORDER_SERVICE_GRPC_PORT:-9201}"