// Code generated by servicegen. DO NOT EDIT.
#[path = "order_item_serde.rs"]
mod order_item_serde;
pub use order_item_serde::OrderItemSerde;
#[path = "order_item_result_serde.rs"]
mod order_item_result_serde;
pub use order_item_result_serde::OrderItemResultSerde;
#[path = "order_processed_serde.rs"]
mod order_processed_serde;
pub use order_processed_serde::OrderProcessedSerde;