[package]
name = "inventory-service-api"
version = "0.2.50"
edition = "2024"
rust-version = "1.85"
build = "build.rs"

[lib]
name = "inventory_service_api"


[dependencies]
serde = { version = "1", features = ["derive"] }
prost = "0.13"
tonic = "0.12"

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"