# Code generated by servicegen. DO NOT EDIT.
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(abspath ../tools)
BUF := $(TOOLS_DIR)/buf
PROTOC ?= $(TOOLS_DIR)/protoc
ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= 18081
export GOPROXY := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/go-proxy/
export GOSUMDB := off
endif

.PHONY: all gen-proto fmt-proto

all: gen-proto

gen-proto:
	@find . -type f -name 'go.generated.proto.mk' | while read mkfile; do \
		dir=$$(dirname $$mkfile); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C $$dir -f $$(basename $$mkfile) gen MODULE_DIR="$(MODULE_DIR)" PROTOC="$(PROTOC)"; \
	done

fmt-proto:
	@find . -type f -name '*.proto' | while read protofile; do \
		$(BUF) format -w $$protofile; \
	done